ステップ7: タスクを登録・更新・削除できるよう実装
Fablic/training pull request #1014
Opened 2021-06-25 02:04 UTC by connectShinyaOno-0039

**課題**
https://github.com/Fablic/training#%E3%82%B9%E3%83%86%E3%83%83%E3%83%977-%E3%82%BF%E3%82%B9%E3%82%AF%E3%82%92%E7%99%BB%E9%8C%B2%E6%9B%B4%E6%96%B0%E5%89%8A%E9%99%A4%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%82%88%E3%81%86
上記リンクの「ステップ7: タスクを登録・更新・削除できるようにしよう」

**実装内容**
・rails g scaffold_controllerコマンドでコントローラ、ビューを作成
（モデルとマイグレーションファイルがすでに存在したため、rails g scaffoldコマンドを使用せず）
・作成、更新、削除後、それぞれflashメッセージを画面に表示
・タスクの一覧画面は「 http://localhost:3000/ 」で表示されるように実装
・削除の処理は論理削除で実装
・一覧画面はtasksテーブルの「deleted_at」がNULLのみを表示
・画面設計で不備が見つかったため、修正しました
```
画面設計の修正内容
・一覧画面：詳細、編集へのリンクボタンと削除ボタンがなかったので追加
・詳細画面：この画面がなかったため追加
・新規作成画面：戻るボタンを追加
・編集画面：戻るボタンと詳細ボタン（詳細画面へのリンク）を追加
```

**共有事項**
・当初プルリクを2回に分ける予定でしたが、rails g scaffold_controllerコマンドで本課題の概ねの実装ができてしまったため、プルリクを分けておりません。

・rails g scaffold_controllerコマンドで自動で作成されたテスト系のファイルは、本課題の対象外のため削除しました。

・https://jira.rakuten-it.com/jira/browse/RAKUCRE-4903
上記リンク先のJIRAに修正した画面設計を添付しております。
修正内容に問題ない場合、下記JIRA（ステップ4）に添付しなおします。
https://jira.rakuten-it.com/jira/browse/RAKUCRE-4900

2021-06-25 07:04 UTC, R-KazumaInazaki requested changes
レビューしました！
修正してほしいものと、しなくてよいものあるので確認してください！

参考でいくつかリンクを貼りましたが、全部読むと長いので軽く目を通すくらいで見てみてください。

2021-06-25 07:08 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
> +    task_params["status_id"] = 1 # 「未着手」固定
modelに定数を定義します！

2021-06-25 07:09 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
> +    end
こちら修正不要承知しました！

2021-06-25 07:09 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
> +    task_params = params[:task].permit(:task_name, :priority_id, :label, :limit_date, :detail)
参考をもとにrequireを使った書き方に修正します！

2021-06-25 07:10 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
> +    now = DateTime.now
Time.currentに修正します！

2021-06-25 07:11 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
> +    end
確かに使用してないです。
こちら削除します！

2021-06-25 07:12 UTC, connectShinyaOno-0039 commented on tasks/app/views/tasks/_form.html.erb
> +<%= form_with(model: task) do |form| %>
承知しました。
こちら共通化を試してみます！

2021-06-25 07:18 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
> +    @tasks = Task.where(deleted_at: nil)
こちらscopeとして定義します！

2021-06-25 09:00 UTC, connectShinyaOno-0039 commented
レビュー修正を行いましたので、お手隙の際にご確認お願いいたします。

レビュー修正内容
```
・削除されていないタスクの検索をmodelでscopeで定義
・modelに定数を定義（未着手）
・requireを使った書き方に修正
・現在時刻の取得をTime.currentに修正
・def task_paramsの削除
・_form.html.erbでフォームの共通化
・詳細画面にも削除機能実装（画面設計も修正）
```
また、自分で気になった点もいくつか修正しております。
```
・画面左上に秒数が非表示になるように修正
・期限を入力する箇所をdatetime_fieldに変更
```

2021-06-28 02:35 UTC, R-KazumaInazaki requested changes
再度指摘したのでご確認お願いします…！

2021-06-28 02:35 UTC, R-KazumaInazaki commented on tasks/app/views/tasks/edit.html.erb
>  <%= link_to '戻る', '/' %>
修正しなくて良いのですが、`'/'`は、`root_path`と書くこともできますので参考までに！

2021-06-28 02:43 UTC, connectShinyaOno-0039 commented on tasks/app/models/task.rb
> +    scope :getAll, -> { where(deleted_at: nil) }
スネークケース「:without_deleted」に修正します！

2021-06-28 02:43 UTC, connectShinyaOno-0039 commented on tasks/app/models/master_task_status.rb
> +    NOT_STARTED = 1
他のステータスと優先度についても定数を定義します！

2021-06-28 02:44 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
> -    end
共通化します！

2021-06-28 02:44 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
>          format.html { redirect_to @task, notice: "タスクを更新しました。" }
こちら今後の実装で意識します！

2021-06-28 02:45 UTC, connectShinyaOno-0039 commented on tasks/app/views/tasks/_form.html.erb
> +  <% end %>
step9で修正承知しました！
一旦このままにします！

2021-06-28 02:46 UTC, connectShinyaOno-0039 commented on tasks/app/views/tasks/edit.html.erb
>  <%= link_to '戻る', '/' %>
なるほど！承知しました！

2021-06-28 04:36 UTC, connectShinyaOno-0039 commented
再度、レビュー修正を行いましたので、お手隙の際にご確認お願いいたします。

修正内容
```
・スコープ名をスネークケース「:without_deleted」に修正
・MasterTaskStatusとMasterTaskPriorityの各定数を定義
・task_paramsを共通化
・ハッシュに代入時、キーを文字列ではなくシンボルで指定するように修正
```

2021-06-28 04:55 UTC, R-KazumaInazaki approved these changes
[![LGTM](https://lgtm.lol/p/431)](https://lgtm.lol/i/431)

2021-06-28 04:58 UTC, merged