ステップ14: ページネーションを追加
Fablic/training pull request #1048
Opened 2021-07-15 00:18 UTC by connectShinyaOno-0039

**課題**
https://github.com/Fablic/training#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9714-%E3%83%9A%E3%83%BC%E3%82%B8%E3%83%8D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%97%E3%82%88%E3%81%86
上記リンクの「ステップ14: ページネーションを追加しよう」

**実装内容**
・Kaminariのgemを使用してページネーションの実装
・ja.ymlで日本語化
・ページネーションのrspec作成
・rspecで共通処理（デフォルトのソート）をprivateメソッドで共通化

**画面キャプチャ**

【1ページ目】
<img width="886" alt="ページネーション1ページ目" src="https://user-images.githubusercontent.com/85857723/125708773-d85885d5-0827-429a-bfd7-b1041759d988.png">

【2ページ目】
<img width="908" alt="ページネーション2ページ目" src="https://user-images.githubusercontent.com/85857723/125708785-70bb22d7-ccc2-404d-9056-b57540ea09cc.png">

【3ページ目】
<img width="902" alt="ページネーション3ページ目" src="https://user-images.githubusercontent.com/85857723/125708791-ffcdf0f7-ea67-4c3a-96ec-d87ab4980299.png">

2021-07-15 06:51 UTC, R-KazumaInazaki requested changes
レビューしたのでご確認お願いします！

2021-07-15 06:51 UTC, R-KazumaInazaki commented on tasks/app/controllers/tasks_controller.rb
> +    @tasks = Kaminari.paginate_array(@task_list).page(params[:page]).per(PER)
Modelに以下のように定義することで、毎回perメソッドを呼ばなくても良くなると思うので、特に理由がなければこちらの設定をしましょう。
https://github.com/kaminari/kaminari#configuring-default-per_page-value-for-each-model-by-paginates_per

デフォルト値を参照したい時があると思いますが、`Task.default_per_page`で取れそうです。

2021-07-15 06:51 UTC, R-KazumaInazaki commented on tasks/spec/controllers/tasks_controller_spec.rb
> +    let!(:task_list) { create_list(:task_list_item, 12) }
`let!`ではなく`let`でよさそう

2021-07-15 06:51 UTC, R-KazumaInazaki commented on tasks/spec/controllers/tasks_controller_spec.rb
> +        sort_list.take_while { |task| sort_list.index(task) < TasksController::PER }
ここでやっていることは、`配列内の最初の10個のオブジェクトを取得する`だと思いますが、もっと簡単にかけると思います。
indexから配列を取得するだけであれば、`sort_list[0]`で最初のオブジェクトが取得できるように、`sort_list[0..9]`もしくは`sort_list[0, 10]`と指定することで最初から10番目までのオブジェクトが取れると思います。

2021-07-15 06:51 UTC, R-KazumaInazaki commented on tasks/spec/controllers/tasks_controller_spec.rb
> +        sort_list.drop_while { |task| sort_list.index(task) < TasksController::PER }
今回はデータが12個しかないので問題ないですが、データが22個あった場合は`task_list_next_page `に12個のオブジェクトが入ります。
こちらも書き方を変えましょう。

また、take_whileもdrop_whileも、selectで代用することが可能です。
selectの場合、条件を満たしても満たさなくても必ず最後のオブジェクトまでチェックします。
なので、まずはselectで考えて、無駄だと思ってから*_whileを使うようにしましょう。

2021-07-15 06:51 UTC, R-KazumaInazaki commented on tasks/spec/controllers/tasks_controller_spec.rb
> +    end
sortではなくsort_byを使うことで、より簡潔にかけそうです。
`target_list.sort_by { |a| a.created_at }`
また、上記のようにブロック内でオブジェクトに対して単一のメソッドを呼ぶ場合は、
`target_list.sort_by(&:created_at)`と省略して書くこともできます。

参考（記事のコメント欄）
https://qiita.com/zom/items/b22510a86ef63b18af00#%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88

2021-07-15 06:51 UTC, R-KazumaInazaki commented on tasks/spec/controllers/tasks_controller_spec.rb
>        expect(response).to redirect_to '/tasks'
今回の範囲ではないので直さなくて良いですが…できればパスは文字列ではなく`tasks_path`のような書き方がいいですね
あまり無いですがルーティングを変更した時に修正する必要が出てきそうなので

2021-07-15 07:17 UTC, connectShinyaOno-0039 commented on tasks/app/controllers/tasks_controller.rb
> +    @tasks = Kaminari.paginate_array(@task_list).page(params[:page]).per(PER)
承知しました！
こちら修正します！

2021-07-15 07:20 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/tasks_controller_spec.rb
> +    let!(:task_list) { create_list(:task_list_item, 12) }
こちらも修正します！

2021-07-15 07:25 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/tasks_controller_spec.rb
> +        sort_list.take_while { |task| sort_list.index(task) < TasksController::PER }
なるほど！
こちらも修正します！

2021-07-15 07:26 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/tasks_controller_spec.rb
> +        sort_list.drop_while { |task| sort_list.index(task) < TasksController::PER }
確かに22個のデータだとダメですね、、
こちらも修正します！

2021-07-15 07:44 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/tasks_controller_spec.rb
> +    end
承知しました！
こちらも修正します！

2021-07-15 08:00 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/tasks_controller_spec.rb
>        expect(response).to redirect_to '/tasks'
こちらそっと修正します

2021-07-15 08:18 UTC, connectShinyaOno-0039 commented
レビュー修正を行いましたので、お手隙の際にご確認お願いいたします！

修正内容
・モデルにページネーションのデフォルト値を記載
・let!からletに修正
・配列の取得方法の修正
・sort_byを使用するように修正
・tasks_pathに修正

2021-07-15 10:00 UTC, R-KazumaInazaki requested changes
再度指摘したのでご確認お願いします…！

2021-07-15 10:00 UTC, R-KazumaInazaki commented on tasks/spec/controllers/tasks_controller_spec.rb
> +        sort_list.select { |task| sort_list.index(task) >= Task.default_per_page && sort_list.index(task) < Task.default_per_page * 2 }
ここも65行目と同じ書き方でいいと思います。
`sort_list[Task.default_per_page, Task.default_per_page * 2]`

2021-07-15 10:00 UTC, R-KazumaInazaki commented on tasks/spec/controllers/tasks_controller_spec.rb
> +        expect(response).to redirect_to "#{tasks_path}/#{Task.last.id}"
修正していただいてありがたいのですが、ここの書き方は式展開ではなく
`task_path(id: task.id)`
のように書けると思います！

2021-07-16 00:22 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/tasks_controller_spec.rb
> +        sort_list.select { |task| sort_list.index(task) >= Task.default_per_page && sort_list.index(task) < Task.default_per_page * 2 }
こちら修正します！

2021-07-16 00:22 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/tasks_controller_spec.rb
> +        expect(response).to redirect_to "#{tasks_path}/#{Task.last.id}"
こちら修正します！

2021-07-16 00:28 UTC, connectShinyaOno-0039 commented
再レビューの修正を行いましたので、お手隙の際にご確認お願いいたします！

修正内容
・ページネーションテストの「2ページ目の表示の場合」の配列の取得方法の修正
・リダイレクト検証を「task_path(id: task.id)」の記載に修正
（createは「task_path(id: Task.last.id)」に修正）

2021-07-16 00:43 UTC, R-KazumaInazaki approved these changes
確認しました！LGTM！

2021-07-16 00:48 UTC, merged