ステップ18: ユーザの管理画面を実装しよう（rspecの作成）
Fablic/training pull request #1063
Opened 2021-08-03 00:17 UTC by connectShinyaOno-0039

**課題**
https://github.com/Fablic/training#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9718-%E3%83%A6%E3%83%BC%E3%82%B6%E3%81%AE%E7%AE%A1%E7%90%86%E7%94%BB%E9%9D%A2%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%97%E3%82%88%E3%81%86--%E3%82%B9%E3%82%AD%E3%83%83%E3%83%97%E5%8F%AF%E8%83%BD
上記リンクの「ステップ18: ユーザの管理画面を実装しよう」のrspecの作成

**実装内容**
・fakerの導入
・管理画面のrspecの実装

2021-08-03 08:37 UTC, R-KazumaInazaki requested changes
いくつか指摘しました。
指摘箇所以外にも同様の観点で修正できる箇所があると思うので、横展開で確認をお願いします。

2021-08-03 08:37 UTC, R-KazumaInazaki commented on tasks/spec/controllers/admin_users_controller_spec.rb
> +        expect(user.reload.email).to eq 'update@user.com'
reloadは一度すれば大丈夫かも

2021-08-03 08:37 UTC, R-KazumaInazaki commented on tasks/spec/controllers/admin_users_controller_spec.rb
> +      let(:normalUserParams) { { user_name: '変更後ユーザ名', email: 'update@user.com' } }
スネークケースで書きましょう
`normal_user_params`

2021-08-03 08:37 UTC, R-KazumaInazaki commented on tasks/spec/controllers/admin_users_controller_spec.rb
> +        expect(other_user.reload.deleted_at).to_not eq nil
`.to_not eq nil`とするのであれば`.to be_present`で良さそう

2021-08-03 08:37 UTC, R-KazumaInazaki commented on tasks/spec/models/task_spec.rb
> +        expect(task.update!(deleted_at: deleted_at)).to eq true
`update!`で実際に更新せずとも、createしたレコードに値を代入して`task.valid?`すればupdate時のvalidationの確認ができたと思うので確認してください。

2021-08-03 08:44 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/admin_users_controller_spec.rb
> +        expect(user.reload.email).to eq 'update@user.com'
確かに大丈夫でした！
こちら修正します！

2021-08-03 08:44 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/admin_users_controller_spec.rb
> +      let(:normalUserParams) { { user_name: '変更後ユーザ名', email: 'update@user.com' } }
こちら修正します！

2021-08-03 08:47 UTC, connectShinyaOno-0039 commented on tasks/spec/controllers/admin_users_controller_spec.rb
> +        expect(other_user.reload.deleted_at).to_not eq nil
確かに、、
こちら修正します！

2021-08-03 09:04 UTC, connectShinyaOno-0039 commented on tasks/spec/models/task_spec.rb
> +        expect(task.update!(deleted_at: deleted_at)).to eq true
なるほど！承知しました！
こちらも修正します！

2021-08-04 00:00 UTC, connectShinyaOno-0039 commented
お疲れ様です！
レビュー修正を行いましたので、お手隙の際にご確認お願いいたします。

修正内容
・複数回reloadを実行していた箇所を1回のみに修正
・キャラメルケースをスネークケースに修正
・.to_not eq nilを.to be_presentに修正
・update!せず、create後に対象の値を代入してバリデーションチェックを行うように修正

2021-08-04 00:16 UTC, R-KazumaInazaki approved these changes
LGTM!

2021-08-04 00:20 UTC, merged