ステップ13: ログイン/ログアウト機能を実装しよう
Fablic/training pull request #1082
Opened 2021-08-23 01:45 UTC by k-kiosk

2021-08-24 11:22 UTC, UYO123 requested changes
三単現の s の付け方が怪しいです。
specは日本語で書いても大丈夫です。

2021-08-24 11:22 UTC, UYO123 commented on config/locales/ja.yml
> +        danger: ログインに失敗しました
[imo] failure とかの方が好きです。

2021-08-24 11:22 UTC, UYO123 commented on app/controllers/sessions_controller.rb
> +  skip_before_action :login_required
[must] ログインした後にログインページを表示させないようにしてください。

2021-08-24 11:22 UTC, UYO123 commented on spec/requests/sessions_spec.rb
> +    it 'has user id in session' do
[must]
一般的に
- テスト対象については describe
- 条件に関しては context
- 期待される結果については it や example 

を用います。
it が条件として記載されているのでより細かく context を利用して書いてみてください。

2021-08-25 00:39 UTC, k-kiosk commented on config/locales/ja.yml
> +        danger: ログインに失敗しました
https://github.com/Fablic/training/pull/1082/commits/5b0f5c44970a0e25523ff7f4d56a0acbb08eaf8d
successの反義語として`failure`が適切だと思うので修正しました。
flashのキー名は、[Bootstrapのcolors](https://getbootstrap.com/docs/4.3/utilities/colors/)に対応させていて、そのままにしています。

2021-08-25 01:38 UTC, k-kiosk commented on spec/requests/sessions_spec.rb
> +    it 'has user id in session' do
ここは、「createアクションが実行された結果、sessionにuser idを持つこと」という期待される結果を意図して書きました。

>it が条件として記載されているので
条件と解釈されたのはどの部分でしょうか？（僕の英語力がイマイチな可能性もありますね...）

2021-08-25 01:39 UTC, k-kiosk commented on app/controllers/sessions_controller.rb
> +  skip_before_action :login_required
https://github.com/Fablic/training/pull/1082/commits/2e00cee41666d90c82c51f178cae9e0ff2cdbe7f
こちらで対応しました！

2021-08-25 01:42 UTC, k-kiosk commented
@UYO123 
ご指摘いただいた箇所について、修正と質問（specの`it`の使い方）をしました🙇‍♂️

>三単現の s の付け方が怪しいです。

僕もあまり自信ないです。明らかにおかしい点があればご指摘いただけると嬉しいです！

2021-08-25 05:19 UTC, UYO123 approved these changes
![LGTM](https://image.lgtmoon.dev/137570)

英語一緒にがんばりましょう🔥

2021-08-25 05:19 UTC, UYO123 commented on spec/requests/sessions_spec.rb
> +    it 'has user id in session' do
すみません。 session にuser_id を持っていた場合の処理としての注釈の勘違いです💦

2021-08-25 05:19 UTC, UYO123 commented on spec/requests/tasks_spec.rb
> +      it 'deletes a task' do
ここも s はつかないです。

2021-08-25 05:19 UTC, UYO123 commented on spec/requests/tasks_spec.rb
>      it 'updates a task' do
例えばここは s がつかないです。

2021-08-25 05:42 UTC, k-kiosk commented on spec/requests/tasks_spec.rb
>      it 'updates a task' do
@UYO123 
主語が三人称単数（it）かつ現在形なので、動詞にはsがつく理解だったのですが、ここではどのような条件でsがつかないのでしょうか？

ちなみにRSpecを使っている有名OSSの[GitLab](https://github.com/gitlabhq/gitlabhq)や[Mastodon](https://github.com/mastodon/mastodon)を見てみたところ、`it 'updates... `や`it 'deletes... `のテストケースはいくつか見つかりました（有名OSSだからといって、全て正しい文法ではないとは思いますが😐）

2021-08-25 08:44 UTC, UYO123 commented on spec/requests/tasks_spec.rb
>      it 'updates a task' do
そうですね。
これも勘違いです💦
it なので何も問題ないです_:(´ཀ`」 ∠):
英語がんばります

2021-08-25 08:48 UTC, merged