Mvincent yap step8 11
Fablic/training pull request #1166
Opened 2021-10-21 01:59 UTC by mvincent-yap

rails test + rspec test OK
```
root@8ac7e829c363:/myapp# rails test
Running via Spring preloader in process 78796
Run options: --seed 54352

# Running:

........................

Finished in 4.252447s, 5.6438 runs/s, 8.9360 assertions/s.
24 runs, 38 assertions, 0 failures, 0 errors, 0 skips
root@8ac7e829c363:/myapp# rspec
**.................

Finished in 2.73 seconds (files took 2.76 seconds to load)
19 examples, 0 failures, 2 pending

root@8ac7e829c363:/myapp# 
```

レビューポイント：
　　i18nの設定はあっています？　
　　　　　t('task.name') じゃなくてTask.human_attribute_name(:status)  を利用しました
　　spec/system のテストの細か過ぎないか？足りないか？

2021-10-21 05:10 UTC, rakumiki requested changes
いくつかコメントしました！

2021-10-21 05:10 UTC, rakumiki commented on myapp/Gemfile
> +gem 'enum_help'
enum で i18n を使えるようにするためのgemなんですね 📝

2021-10-21 05:10 UTC, rakumiki commented on myapp/config/locales/views/en.yml
> +  actions:
`list:` を追加したほうが良さそうです
![スクリーンショット 2021-10-21 12 21 09](https://user-images.githubusercontent.com/83994878/138206124-4c010012-0d19-42fc-97bf-808fb0763a5c.png)

2021-10-21 05:10 UTC, rakumiki commented on myapp/config/locales/views/en.yml
> +ja:
ファイル名が en.yml なので、`en:` ですかね？

2021-10-21 05:10 UTC, rakumiki commented on myapp/config/locales/models/task_ja.yml
> +
不要な改行は消しておきましょう

2021-10-21 05:10 UTC, rakumiki commented on myapp/app/models/task.rb
> +  def finished_at_is_after_started_at
`ActiveModel::Validator` を継承してつくるカスタムバリデーションと、`presense: true` などの標準のバリデーションを組み合わせて書いてもいいかもしれません
https://railsguides.jp/active_record_validations.html#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%90%E3%83%AA%E3%83%87%E3%83%BC%E3%82%BF

2021-10-21 05:10 UTC, rakumiki commented on myapp/app/views/tasks/index.html.erb
> +        <td><%= l(task.finished_at.to_date) %></td>
`started_at` はバリデーションで存在チェックをしているので、`finished_at` と同じ書き方で良さそうです

2021-10-21 05:10 UTC, rakumiki commented on myapp/app/views/tasks/show.html.erb
> +  <strong><%= Task.human_attribute_name(:status) %></strong>
引数は `started_at` ですね

2021-10-21 05:10 UTC, rakumiki commented on myapp/app/views/tasks/show.html.erb
> +  <strong><%= Task.human_attribute_name(:status) %></strong>
引数は `finished_at` ですね

2021-10-21 05:10 UTC, rakumiki commented on myapp/app/models/task.rb
>    validates :finished_at, { presence: true }
`started_at` , `finished_at` に存在しない日付 (11/31)を入力すると別の日付になってしまうのでこれもチェックするといいかもしれませんね

2021-10-21 05:10 UTC, rakumiki commented on myapp/spec/models/task_spec.rb.tmp
> +# frozen_string_literal: true
このファイルは不要なら削除しておきたいですね

2021-10-21 06:56 UTC, mvincent-yap commented on myapp/Gemfile
> +gem 'enum_help'
はい

2021-10-21 07:21 UTC, rakumiki commented on myapp/docker-compose.debug.yml
> +    command: bash -c "rdbg --open --nonstop -c -- rails s -p 3000 -b '0.0.0.0'"
おー、これ使って VSCode でリモートデバッグできるようになるんですね 😄

2021-10-21 07:56 UTC, rakumiki commented on myapp/spec/system/tasks_spec.rb
> +        expect(page).to have_content 'Task was successfully created.'
i18n の観点でこのメッセージも日本語化できていると良さそうです

2021-10-22 04:50 UTC, higuching approved these changes
LGTM!
研修なので修正は任意ですがいくつか`No Newline at End of File`が出てますね
VSCodeにはオプション設定すれば自動的にやってくれるみたいです
https://qiita.com/facultyoflaw11/items/14c16f1b624ffd2f383c

2021-10-22 09:09 UTC, rakumiki requested changes

2021-10-22 09:09 UTC, rakumiki commented on myapp/app/controllers/tasks_controller.rb
> +    params[:direction] ||= 'ASC'
ステップ10の課題は 
```
・現在IDの順で並んでいますが、これを作成日時の降順で並び替えてみましょう
・並び替えがうまく行っていることをsystem specで書いてみましょう
```
 なので、デフォルトのソートキーと方向を合わせて修正する必要がありそうです。system spec も書いておきましょう

2021-10-22 09:09 UTC, rakumiki commented on myapp/app/helpers/tasks_helper.rb
> +  def get_sort_direction(sort_name)
ソート対象を抽象化できているのがいいですね

2021-10-22 09:09 UTC, rakumiki commented on myapp/app/helpers/tasks_helper.rb
> +    'ASC'
L5 で `request.params[:sort] != sort_name.to_s` を判定していることから L6 の`request.params[:sort] == sort_name.to_s` が常に `true` になるので、 L6-8 は
```
request.params[:direction] == 'ASC' ? 'DESC' : 'ASC'
```
のようにも書けそうです

2021-10-25 05:09 UTC, mvincent-yap commented on myapp/config/locales/views/en.yml
> +  actions:
修正しました

2021-10-25 05:09 UTC, mvincent-yap commented on myapp/config/locales/views/en.yml
> +ja:
修正しました

2021-10-25 05:09 UTC, mvincent-yap commented on myapp/config/locales/models/task_ja.yml
> +
修正しました

2021-10-25 05:09 UTC, mvincent-yap commented on myapp/app/models/task.rb
> +  def finished_at_is_after_started_at
修正しました

2021-10-25 05:09 UTC, mvincent-yap commented on myapp/app/views/tasks/index.html.erb
> +        <td><%= l(task.finished_at.to_date) %></td>
修正しました

2021-10-25 05:10 UTC, mvincent-yap commented on myapp/app/views/tasks/show.html.erb
> +  <strong><%= Task.human_attribute_name(:status) %></strong>
修正しました

2021-10-25 05:10 UTC, mvincent-yap commented on myapp/app/views/tasks/show.html.erb
> +  <strong><%= Task.human_attribute_name(:status) %></strong>
修正しました

2021-10-25 05:10 UTC, mvincent-yap commented on myapp/app/models/task.rb
>    validates :finished_at, { presence: true }
修正しました

2021-10-25 05:10 UTC, mvincent-yap commented on myapp/spec/models/task_spec.rb.tmp
> +# frozen_string_literal: true
削除しました

2021-10-25 05:10 UTC, mvincent-yap commented on myapp/spec/system/tasks_spec.rb
> +        expect(page).to have_content 'Task was successfully created.'
修正しました

2021-10-25 05:26 UTC, mvincent-yap commented on myapp/app/controllers/tasks_controller.rb
> +    params[:direction] ||= 'ASC'
修正しました

2021-10-25 05:34 UTC, mvincent-yap commented on myapp/app/helpers/tasks_helper.rb
> +    'ASC'
修正しました

2021-10-25 06:59 UTC, rakumiki requested changes

2021-10-25 06:59 UTC, rakumiki commented on myapp/app/views/tasks/_form.html.erb
> +    <%= form.date_field :started_at %>
日付の選択がしやすくなりました 👍

2021-10-25 06:59 UTC, rakumiki commented on myapp/app/models/task.rb
> +  attr_accessor :start_tmp
この `start_tmp` という属性は何かに使っていますか？

2021-10-25 06:59 UTC, rakumiki commented on myapp/app/controllers/tasks_controller.rb
> +    params[:direction] ||= 'ASC'
作成日時の降順なので、 `ASC` -> `DESC` にする必要があります
```
ascending order : 昇順
descending order : 降順
```

2021-10-25 06:59 UTC, rakumiki commented on myapp/app/models/task.rb
> +  def finished_at_is_after_started_at
ありがとうございます！ `finished_at_is_after_started_at` と `finished_at_cannot_be_in_the_past` は使わなかくなったので消しておくといいと思います！

2021-10-26 00:21 UTC, mvincent-yap commented on myapp/app/models/task.rb
> +  attr_accessor :start_tmp
ah、いろいろ試して　消して忘れました。

2021-10-26 00:21 UTC, mvincent-yap commented on myapp/app/controllers/tasks_controller.rb
> +    params[:direction] ||= 'ASC'
修正した

2021-10-26 00:33 UTC, rakumiki approved these changes
LGTM!

2021-10-26 00:42 UTC, merged