Mvincent yap step17 21
Fablic/training pull request #1183
Opened 2021-11-01 04:14 UTC by mvincent-yap

見た目や翻訳部分は無視してください。

ステップ17: ログイン/ログアウト機能を実装しよう
ステップ18: ユーザの管理画面を実装しよう
ステップ19: ユーザにロールを追加しよう
ステップ20: タスクにラベルをつけられるようにしよう
ステップ21: メンテナンス機能を作ろう.  
      ```./bin/rake maintenance:start["Sorry try again later"]```
      ```./bin/rake maintenance:end ```

<img width="335" alt="Screen Shot 2021-11-01 at 13 09 09" src="https://user-images.githubusercontent.com/91441643/139620528-81025738-fa80-48a9-a96a-4c16cb752414.png">

<img width="1259" alt="Screen Shot 2021-11-01 at 13 10 34" src="https://user-images.githubusercontent.com/91441643/139620625-5646a0c1-79ef-4e70-8be5-5beebb44c042.png">
<img width="1247" alt="Screen Shot 2021-11-01 at 13 11 28" src="https://user-images.githubusercontent.com/91441643/139620673-d7e11819-6f23-4647-848b-85f3b11f2974.png">

<img width="952" alt="Screen Shot 2021-11-01 at 13 13 30" src="https://user-images.githubusercontent.com/91441643/139620802-7b688340-042b-48fd-a119-7101072e434b.png">

2021-11-01 06:01 UTC, rakumiki commented
ラベルを登録しようとすると、エラーが出てUserを入力できないようになっています。
ログイン中のユーザーのIDを常に設定するようにするといいと思います。
![スクリーンショット 2021-11-01 14 59 47](https://user-images.githubusercontent.com/83994878/139628209-9309d522-420e-44fc-8c7f-2437e9e74eed.png)

2021-11-01 06:04 UTC, rakumiki commented
step 19で
> 管理ユーザが1人もいなくならないように削除の制御をしましょう
こちらが実装されておらず、すべての管理ユーザーを削除できてしまうので修正をお願いします

2021-11-01 06:06 UTC, rakumiki commented
メンテナンスを開始しようとするとエラーが発生してしまうようです
CLI でメンテナンスを実施する場合、ユーザーの指定は必要ないのではないかと思ったのですがいかがでしょうか？

```
# ./bin/rake maintenance:start["Sorry try again later"]
Running via Spring preloader in process 481
maintenance message - Sorry try again later
rake aborted!
ActiveRecord::InvalidForeignKey: Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`myapp_development`.`maintenances`, CONSTRAINT `fkeyMaintenanceOwner` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`))
/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/usr/local/bundle/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `block (2 levels) in execute'
...
```

2021-11-01 08:22 UTC, nagamine-r reviewed
本質的な箇所は少ないですが、いくつかコメントしてます。
ローカルで実際に動かしてみたくなったので、ちょっと追加でコメントするかもしれないです。

2021-11-01 08:22 UTC, nagamine-r commented on myapp/app/views/labels/edit.html.erb
> +<h1 class="title has-text-primary">
細かいですが…インデントが気になりました！

2021-11-01 08:22 UTC, nagamine-r commented on myapp/app/views/labels/index.html.erb
> +<h1 class="title has-text-primary">
こちらもインデントが気になりました

2021-11-01 08:22 UTC, nagamine-r commented on myapp/app/views/labels/show.html.erb
> +<%= link_to t('actions.back'), labels_path, class:"delete is-large is-pulled-right" %>
こちらも、インデントが気になりました

2021-11-01 08:22 UTC, nagamine-r commented on myapp/app/views/layouts/application.html.erb
> +<% end  %>
細かいところばかりすみません。
こちら、インデントの規則性が分からず気になりました

2021-11-01 08:22 UTC, nagamine-r commented on myapp/app/views/sessions/new.html.erb
> +<%= form_tag '/login' do %>
インデントが気になります…

2021-11-01 08:22 UTC, nagamine-r commented on myapp/app/views/shared/_label_component.html.erb
> +<% end%>
インデント気になります

2021-11-01 08:22 UTC, nagamine-r commented on myapp/app/views/tasks/_searchbox.html.erb
> +</h1>
インデント気になりました

2021-11-02 02:43 UTC, mvincent-yap commented
@rakumiki 

> メンテナンスを開始しようとするとエラーが発生してしまうようです
CLI でメンテナンスを実施する場合、ユーザーの指定は必要ないのではないかと思ったのですがいかがでしょうか？

修正しました

> ラベルを登録しようとすると、エラーが出てUserを入力できないようになっています。 ログイン中のユーザーのIDを常に設定するようにするといいと思います。

修正しました

2021-11-02 04:26 UTC, mvincent-yap commented on myapp/app/views/labels/edit.html.erb
> +<h1 class="title has-text-primary">
修正しました

2021-11-02 04:26 UTC, mvincent-yap commented on myapp/app/views/labels/index.html.erb
> +<h1 class="title has-text-primary">
修正しました

2021-11-02 04:26 UTC, mvincent-yap commented on myapp/app/views/labels/show.html.erb
> +<%= link_to t('actions.back'), labels_path, class:"delete is-large is-pulled-right" %>
修正しました

2021-11-02 04:27 UTC, mvincent-yap commented on myapp/app/views/layouts/application.html.erb
> +<% end  %>
修正しました

2021-11-02 04:27 UTC, mvincent-yap commented on myapp/app/views/sessions/new.html.erb
> +<%= form_tag '/login' do %>
修正しました

2021-11-02 04:28 UTC, mvincent-yap commented on myapp/app/views/shared/_label_component.html.erb
> +<% end%>
修正しました

2021-11-02 04:28 UTC, mvincent-yap commented on myapp/app/views/tasks/_searchbox.html.erb
> +</h1>
修正しますした

2021-11-02 09:35 UTC, rakumiki requested changes

2021-11-02 09:35 UTC, rakumiki commented on myapp/app/controllers/application_controller.rb
> +    redirect_to maintenance_path if logged_in? && !admin?
if の条件に入らない場合（ログアウトしていた状態からログインした場合や adminユーザーの場合)にRailsのエラー画面になってしまうので、その場合もメンテナンス中であることがわかった方がよいと思います

2021-11-02 09:35 UTC, rakumiki commented on myapp/app/controllers/sessions_controller.rb
> +      flash.alert = t('messages.invalid_login')
flash メッセージが表示されないようになってしまっているので、修正をお願いします

2021-11-04 05:58 UTC, mvincent-yap commented on myapp/app/controllers/sessions_controller.rb
> +      flash.alert = t('messages.invalid_login')
修正しました

2021-11-04 06:17 UTC, nagamine-r reviewed
これまた細かいですが…いくつかコメントいれました！
また、今回はあくまでトレーニングなので大丈夫ですが
試験した内容が書かれていてもよいかもと思いました

2021-11-04 06:17 UTC, nagamine-r commented on myapp/app/views/layouts/application.html.erb
> +    <% if ! notice.blank? %>
`notice.present?` じゃまずいですかね…？（ `!` がぱっと分かりづらく…）

2021-11-04 06:17 UTC, nagamine-r commented on myapp/app/views/layouts/application.html.erb
> +    <% if ! alert.blank? %>
`present?` 使えますか…？

2021-11-04 06:17 UTC, nagamine-r commented on myapp/app/views/sessions/new.html.erb
> +                <% if ! alert.blank? %>
presentじゃまずいでしょうか…

2021-11-04 06:21 UTC, mvincent-yap commented on myapp/app/views/layouts/application.html.erb
> +    <% if ! notice.blank? %>
ah present?機能　知らなかった。修正します

2021-11-04 06:25 UTC, mvincent-yap commented on myapp/app/views/layouts/application.html.erb
> +    <% if ! alert.blank? %>
修正し

2021-11-04 06:25 UTC, mvincent-yap commented on myapp/app/views/sessions/new.html.erb
> +                <% if ! alert.blank? %>
修正し

2021-11-05 07:23 UTC, nagamine-r commented on myapp/db/schema.rb
> -    t.index ['created_by'], name: 'fkeyMaintenanceOwner'
RSpecは通っているようですがminitestがコケているようでして…大丈夫でしょうか？
```
$ rails test

中略

Finished in 3.858249s, 6.2204 runs/s, 0.0000 assertions/s.
24 runs, 0 assertions, 0 failures, 24 errors, 0 skips
```

2021-11-05 09:10 UTC, rakumiki requested changes
いくつかコメントしました。
タスクの削除ができなくなってしまっているようですので、修正をお願いします
![スクリーンショット 2021-11-05 18 03 08](https://user-images.githubusercontent.com/83994878/140486122-16b5d734-ece2-438b-811f-c50508bf8a4b.png)
ているようですので修正をお願いします

2021-11-05 09:10 UTC, rakumiki commented on myapp/app/views/labels/index.html.erb
> +            <td><%= link_to  label.tasks.count.to_s, tasks_path('q[labels_id_eq]':label.id), class: 'button' %></td>
ラベルごとのタスクの数からラベルの検索結果が表示できていいですね 👍

2021-11-05 09:10 UTC, rakumiki commented on myapp/app/views/labels/index.html.erb
> +          <th><%= sort_link(@q, :name) %></th>
ラベル名でのソートがうまくいっていないようなので、ご確認いただけますか？
![スクリーンショット 2021-11-05 12 59 02](https://user-images.githubusercontent.com/83994878/140456041-755cc8ff-f211-4c9c-9413-957a9c74e02f.png)

2021-11-05 09:10 UTC, rakumiki commented on myapp/app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag 'https://unpkg.com/bulmaswatch/journal/bulmaswatch.min.css' %>
https://jenil.github.io/bulmaswatch/
ここから持ってきているんですね

2021-11-05 09:10 UTC, rakumiki commented on myapp/app/views/sessions/new.html.erb
> +                    <%= label_tag :username, 'Username', class: 'label' %>
`Username` だと何を入力するのか伝わりづらいので 管理画面と同じように `メールアドレス`と表示しておいたほうがよさそうです

2021-11-05 09:10 UTC, rakumiki commented on myapp/app/views/users/index.html.erb
> +  </div>
`<div class="section">` が閉じていないので、最後に `</div>` が必要そうです

2021-11-05 09:10 UTC, rakumiki commented on myapp/app/views/sessions/new.html.erb
> +                      <%= text_field_tag :username, '', class: 'input', required:true %>
`email_field_tag` を使うとメールアドレスのバリデーションができます

2021-11-05 09:10 UTC, rakumiki commented on myapp/app/views/tasks/index.html.erb
> +          <th><%= sort_link(@q, 'user_name') %></th>
usersテーブルの nameカラムでソートしたい時は `user_name`でいけるんですね 📝

2021-11-05 09:10 UTC, rakumiki commented on myapp/app/models/task.rb
> +  scope :due_today, -> { unfinished.where(finished_at: Time.zone.today.strftime('%Y-%m-%d')) }
終了日を今日で設定したときに UTC時刻でDBに登録されるので、そのタスクが overdue となってしまうようです。
rubyプロセスのタイムゾーンや DBサーバーのタイムゾーンをJSTで統一しておいたほうがいいかもしれません

参考: https://qiita.com/aosho235/items/a31b895ce46ee5d3b444
https://github.com/search?p=1&q=org%3AFablic+localtime&type=Code

2021-11-05 10:19 UTC, rakumiki commented on myapp/app/controllers/tasks_controller.rb
> +  around_action :skip_bullet, only: %i[destroy], if: -> { defined?(Bullet) }
[質問]これを書いている意図はどういうものですか？

2021-11-05 10:19 UTC, rakumiki commented on myapp/app/controllers/tasks_controller.rb
> +    @q = @q.send(params[:dash_search]) if params[:dash_search].present? && %w[unfinised overdue due_today].include?(params[:dash_search])
typo: `unfinised` -> `unfinished`

2021-11-05 10:19 UTC, rakumiki commented on myapp/app/controllers/tasks_controller.rb
> +    @q = @q.send(params[:dash_search]) if params[:dash_search].present? && %w[unfinised overdue due_today].include?(params[:dash_search])
models/task.rb で以下のように定義しておくと、 `params` に `unfinished: true`などを追加することで検索できるようになります。
https://github.com/activerecord-hackery/ransack/#using-scopesclass-methods
```
  def self.ransackable_scopes(auth_object = nil)
    %i[unfinished overdue due_today]
  end
```

2021-11-09 06:16 UTC, rakumiki commented on myapp/app/views/labels/index.html.erb
> +          <th><%= sort_link(@q, :name) %></th>
データを登録しなおしたら、ソートできるようになりました。ゴミデータが入っていたのかもしれないです..

2021-11-10 00:31 UTC, mvincent-yap commented on myapp/app/controllers/tasks_controller.rb
> +    @q = @q.send(params[:dash_search]) if params[:dash_search].present? && %w[unfinised overdue due_today].include?(params[:dash_search])
修正しました

2021-11-10 00:31 UTC, mvincent-yap commented on myapp/app/controllers/tasks_controller.rb
> +  around_action :skip_bullet, only: %i[destroy], if: -> { defined?(Bullet) }
削除した時にBullet (N+1エラー）ならないように入れた

2021-11-10 00:31 UTC, mvincent-yap commented on myapp/app/models/task.rb
> +  scope :due_today, -> { unfinished.where(finished_at: Time.zone.today.strftime('%Y-%m-%d')) }
dockerfile 修正しましたのでdocker-compose build api でtimezone=JSTになります

2021-11-10 00:31 UTC, mvincent-yap commented on myapp/app/views/sessions/new.html.erb
> +                      <%= text_field_tag :username, '', class: 'input', required:true %>
修正した

2021-11-10 00:31 UTC, mvincent-yap commented on myapp/app/views/users/index.html.erb
> +  </div>
修正した

2021-11-10 00:31 UTC, mvincent-yap commented on myapp/app/views/sessions/new.html.erb
> +                    <%= label_tag :username, 'Username', class: 'label' %>
 修正した

2021-11-10 00:31 UTC, mvincent-yap commented on myapp/db/schema.rb
> -    t.index ['created_by'], name: 'fkeyMaintenanceOwner'
rspec+rails test  修正した
```
root@19056689e0cc:/myapp# tails test
........................
Finished in 8.242651s, 2.9117 runs/s, 4.6102 assertions/s.
24 runs, 38 assertions, 0 failures, 0 errors, 0 skips

root@19056689e0cc:/myapp# rspec
**.......................**.......................

Finished in 5.71 seconds (files took 3.29 seconds to load)
50 examples, 0 failures, 4 pending
```

> いくつかコメントしました。 タスクの削除ができなくなってしまっているようですので、修正をお願いします ![スクリーンショット 2021-11-05 18 03 08](https://user-images.githubusercontent.com/83994878/140486122-16b5d734-ece2-438b-811f-c50508bf8a4b.png)

2021-11-10 00:32 UTC, mvincent-yap commented
> いくつかコメントしました。 タスクの削除ができなくなってしまっているようですので、修正をお願いします ![スクリーンショット 2021-11-05 18 03 08](https://user-images.githubusercontent.com/83994878/140486122-16b5d734-ece2-438b-811f-c50508bf8a4b.png)

修正しました

2021-11-11 00:32 UTC, rakumiki approved these changes
LGTM!

2021-11-11 02:40 UTC, nagamine-r approved these changes
![LGTM](https://image.lgtmoon.dev/140655)

2021-11-11 04:43 UTC, merged