ステップ7: タスクを登録・更新・削除できるようにしよう
Fablic/training pull request #1249
Opened 2022-02-24 08:13 UTC by hayato-kudo

## 追加点
１、タスクの一覧画面、作成画面、詳細画面、編集画面を作成
　　  - controllerとviewには基本的な機能（index,new,create,show,edit,update,destroy）を追加しております。
　　  - 作成、更新、削除後はそれぞれflashメッセージを画面に表示。
２、http://localhost:3000/ でタスクの一覧画面が表示されるように指定しました。
３、fablicopをインストールしました。
　　  - .rubocop.ymlは`fablicop init`コマンドで作成されたものです。

以上が追加点になります。ご確認の程よろしくお願い致します。

2022-02-25 01:51 UTC, R-KazumaInazaki requested changes
指摘しましたので確認お願いします。
また、以下のファイルは不要なので削除してください。
`myapp/log/development.log`
また、rubocopコマンドは実行しましたでしょうか？

2022-02-25 01:51 UTC, R-KazumaInazaki commented on myapp/config/routes.rb
> +  root 'tasks#index'
rootで設定してもよいのですが、indexだけ`localhost:3000/`で、show等は`localhost:3000/tasks/1`ってなっていると実装しづらいので、
resourcesのpathオプションで設定してみてください。

2022-02-25 01:58 UTC, hayato-kudo commented on myapp/config/routes.rb
> +  root 'tasks#index'
ご確認ありがとうございます。
承知致しました。

2022-02-25 02:45 UTC, hayato-kudo commented on myapp/config/routes.rb
> +  root 'tasks#index'
一点ご質問がございます。
仕様書には「http://localhost:3000/ でタスクの一覧画面が表示されるようにしましょう」と書いてあるのですが、
なぜ、

- indexだけlocalhost:3000/で、show等はlocalhost:3000/tasks/1ってなっていると実装しづらい
となるのでしょうか。ご教授お願い致します。

仕様書：https://github.com/Fablic/training/blob/hayato-kudo/steps_jp.md

2022-02-25 03:27 UTC, R-KazumaInazaki commented on myapp/config/routes.rb
> +  root 'tasks#index'
>rubocopにつきましては、bundle exec rubocopコマンドで起動を確認しました。

起動の確認だけでなく、rubocopによる指摘も確認して対応してほしいです。

>なぜ、indexだけlocalhost:3000/でshow等はlocalhost:3000/tasks/1ってなっていると実装しづらい
>となるのでしょうか。ご教授お願い致します。

exceptしているのでTaskのCRUDなのにGETのtasks_pathが使えない、同じTaskのCRUDなのにindexだけURLにtasksが含まれていないため共通化もしづらい、等が挙げられます。
であれば、GETのtasks_pathも使えてTaskのCRUDでURLを統一できるpathの方が良いです。

2022-02-25 03:49 UTC, R-KazumaInazaki commented on myapp/config/routes.rb
> +  root 'tasks#index'
rubocopに関してはzoomで確認しました。
全て対応すると大変なので、今後、修正を行ったファイルに関して対応をしていくようにお願いします。

2022-02-28 02:45 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +<%= link_to 'Back', '/' %>
以下の箇所と書き方が異なりますが、理由はありますか？
https://github.com/Fablic/training/blob/76bb67aa169af549a24d8406c89548bd7adc86ef/myapp/app/views/tasks/new.html.erb#L6

2022-02-28 02:45 UTC, hayato-kudo commented
## 修正点
１、routes
pathで指定してあげることによって、indexはlocalhost:3000/・show等はlocalhost:3000/1となり実装しやすく致しました。
２、`myapp/log/development.log`削除
３、rubocop実行時に出た指摘内容を修正致しました。
　　  - 改行・空白・# frozen_string_literal: true

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-02-28 02:48 UTC, hayato-kudo commented on myapp/app/views/tasks/show.html.erb
> +<%= link_to 'Back', '/' %>
実装時にBackが使用できず、一時的に'/'に書き換えており、戻すのを忘れておりました。
もう一度修正致します。

2022-02-28 02:52 UTC, hayato-kudo commented
## 修正点
１、show.html.erb
Backボタンのリンクを修正致しました。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-02-28 02:58 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-02-28 03:02 UTC, merged