ステップ11: バリデーションを設定してみよう
Fablic/training pull request #1255
Opened 2022-03-07 01:09 UTC by hayato-kudo

## 仕様書
https://github.com/Fablic/training/blob/hayato-kudo/steps_jp.md#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9711-%E3%83%90%E3%83%AA%E3%83%87%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%97%E3%81%A6%E3%81%BF%E3%82%88%E3%81%86

## 追加点
### **１、taskのmodelにバリデーションを追加しました。**
１、task_nameにNotnull制約を追加しました。
２、descriptionにNotnull制約を追加しました。
### **２、バリデーションエラーのメッセージを表示**
<img width="770" alt="スクリーンショット 2022-03-04 16 43 58" src="https://user-images.githubusercontent.com/99626087/156720926-eb8b7df4-f61c-4361-a4b3-42a5ce61107b.png">
上記の画像の通り、バリデーションエラーになった時のエラー画面を追加致しました。

### **３、バリデーションに対してモデルのテスト**
<img width="1012" alt="スクリーンショット 2022-03-07 9 49 37" src="https://user-images.githubusercontent.com/99626087/156950327-3c352db3-2c9f-49bb-a1d8-16e605fa9e7e.png">

上記の画像の通りバリデーションのテストを実行致しました。

### **４、tasks_controllerのcreateアクションのletを削除致しました。**
削除した理由は、showアクションは登録する前の処理だからcreateでDBに保存する必要がないため不要と判断し削除致しました。

以上が追加点と修正点になります。ご確認の程よろしくお願い致します。

2022-03-07 04:45 UTC, R-KazumaInazaki requested changes
指摘のコメントいれましたのでご確認お願いします。
コメント以外に、以下の確認もお願いします。

rspecについて、エラーパターンは網羅していますが、正常パターンも追加お願いします。
バリデーションについて、例えばステータスの必須チェックや日付の整合性チェック等、アプリケーションとして必要そうなチェックが実装されていませんが、このあたりどのように考えたか確認させてください。

2022-03-07 04:45 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +    validates :description, presence: true
string型、text型のカラムは文字数のチェックもお願いします。

2022-03-07 04:45 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220304044654_change_cloumns_notnull_add_tasks.rb
> +  end
この書き方でrollbackやredoは動きますか？

2022-03-07 05:20 UTC, hayato-kudo commented on myapp/app/models/task.rb
> +    validates :description, presence: true
承知致しました。
修正致します。

2022-03-07 05:21 UTC, hayato-kudo commented on myapp/db/migrate/20220304044654_change_cloumns_notnull_add_tasks.rb
> +  end
できませんでした。
なぜできないのか原因が分かりましたので、対応致します。

2022-03-08 01:38 UTC, hayato-kudo commented
## 修正点
### **１、文字数チェックのバリデーション追加**
task_nameとdescriptionにそれぞれ文字制限を追加しました。
task_name・・・30文字
description・・・100文字
追加した理由は、元々stringとtext型に文字制限が付いていることを知らず255文字以上入力すると、認識していないエラーが出てしまったため、それぞれ自分でバリデーションを追加しました。

### **２、rollbackとredoができない問題を修正**
原因・・redoやrollbackする時に前の情報（task_nameやdescription）が無かったため、upとdownを使って修正しました。

### **３、ends_onにバリデーション追加**
ends_onに「開始日より後に設定されている場合登録できないよう設定する」バリデーションを追加しました。追加した理由は、アプリケーションとして正しい動きにするためです。

### **４、テストケース作成**
それぞれのバリデーションの正常系のパターンが無かったため追加致しました。
また、新たに追加したends_onのテストケースも追加致しました。
<img width="1083" alt="スクリーンショット 2022-03-08 9 32 18" src="https://user-images.githubusercontent.com/99626087/157147564-a9742e1b-fa64-4aa8-a49d-4d5df78afb3b.png">
上記の画像の通りテストケースを作成致しました。

### **５、備考**
今回の実装でstatusとpriorityとlabelにはバリデーションを設定しませんでした。
理由としましては、
status・・・要件では入力することが必須になっておりますが、次のステップ13にてstatusに関する実装があるため、そちらで対応しようと思っております。
priority・・・priorityをソートできるようにする実装がありますが、そちらのステップはスキップする予定ですので今回は何もバリデーションを設定しなくて良いと考えております。
label・・・ステップ20でラベルに関する実装があるため、必要であればそちらで追加していきたいと考えております。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-08 02:21 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  def integrative_check?
ruby、railsでメソッド名の最後に`?`がついていると、`true`もしくは`false`を返すようなメソッドに見えます。

また、このメソッド名だとどの項目をチェックしているのかわかりません。
6行目の`validate :integrative_check?`だけを見た時に、ends_onがstarts_onよりも後でなければいけない。ことがわかるメソッド名にしましょう。`ends_on_must_be_after_starts_on`等。

2022-03-08 02:23 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +    errors.add(:ends_on, 'は開始日より後の日程に設定してください。') if starts_on > ends_on
このエラーメッセージ、日本語を直接書かずにi18nを使って書いてください。

2022-03-08 02:24 UTC, R-KazumaInazaki commented on myapp/spec/models/task_spec.rb
> +    context '説明文が99文字の時' do
100文字、ではなく99文字でチェックをした理由はありますか？

2022-03-08 02:27 UTC, hayato-kudo commented on myapp/app/models/task.rb
> +  def integrative_check?
承知致しました。
修正致します。

2022-03-08 02:28 UTC, hayato-kudo commented on myapp/app/models/task.rb
> +    errors.add(:ends_on, 'は開始日より後の日程に設定してください。') if starts_on > ends_on
承知致しました。
修正致します。

2022-03-08 02:31 UTC, hayato-kudo commented on myapp/spec/models/task_spec.rb
> +    context '説明文が99文字の時' do
特にございません。確認不足でした。
修正致します。

2022-03-08 03:06 UTC, hayato-kudo commented
## 修正点
### **１、ends_onのバリデーションのメソッド名変更**
integrative_check?のメソッド名ではどの項目をチェックしているか分かりずらかったので、変更致しました。

### **２、ends_onのバリデーションエラーメッセージの修正**
日本語でエラーを直接記載するのではなく、i18nを使用して日本語を表示させるよう修正致しました。

### **３、テストケース修正**
descriptionの文字制限（正常系）のテストが間違っていたため修正致しました。

<img width="1018" alt="スクリーンショット 2022-03-08 11 33 02" src="https://user-images.githubusercontent.com/99626087/157158215-99e79e2c-51d7-4944-bbd2-3c1186630573.png">


以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-08 04:44 UTC, R-KazumaInazaki commented on myapp/config/locales/activerecord/ja.yml
> +          end_date_error: は開始日より後の日程に設定してください。
こちらでも呼び出せるのですが、この設定の仕方は、Taskモデルで共通のバリデーションメッセージを設定する時の階層です。
今回の場合はTaskモデルの中でもends_onカラムにだけ起きるエラーであるため、
階層は以下のようになります。
また、end_date_errorは先程のメソッド名の指摘と同様で、メソッド名が抽象的、ends_onからend_dateに変わってしまってる、以下の階層に修正した場合にends_onとend_dateで冗長的になっている、の3点の問題があります。
ここではメソッド名と同じく、`must_be_after_starts_on`としてあげると良いでしょう。
```suggestion
          attributes:
            ends_on:
              must_be_after_starts_on: は開始日より後の日程に設定してください。
```

2022-03-08 04:57 UTC, hayato-kudo commented on myapp/config/locales/activerecord/ja.yml
> +          end_date_error: は開始日より後の日程に設定してください。
承知致しました。
修正致します。

2022-03-08 05:21 UTC, hayato-kudo commented on myapp/config/locales/activerecord/ja.yml
> +          end_date_error: は開始日より後の日程に設定してください。
お疲れ様です。
ご質問がございます。
```
ja:
  activerecord:
    models:
      task: タスク
    attributes:
      task:
        task_name: タスク名
        description: 説明文
        starts_on: 開始日
        ends_on: 終了日
        priority: 優先度
        label: ラベル
        status: ステータス
    errors:
      models:
        task:
          attributes:
            ends_on:
              must_be_after_starts_on: は開始日より後の日程に設定してください。
```
のように記載致しましたが、
<img width="866" alt="スクリーンショット 2022-03-08 14 15 53" src="https://user-images.githubusercontent.com/99626087/157171210-e5aeaee8-f3b0-4bbf-9f31-26b98ba71d99.png">

なぜエラーになってしまうのかご教授お願い致します。

2022-03-08 05:32 UTC, hayato-kudo commented on myapp/config/locales/activerecord/ja.yml
> +          end_date_error: は開始日より後の日程に設定してください。
こちら解決致しました。
エラーメッセージの方の修正を忘れていました。

2022-03-08 05:38 UTC, hayato-kudo commented
## 修正点
### **１、ends_onのバリデーションエラーメッセージ修正**
ends_onカラムにだけエラーメッセージが起こるため階層を修正致しました。また、メソッドがends_onからend_dateに変わってしまっていたため、メソッド名を統一しました。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-08 06:14 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  def ends_on_must_be_after_starts_on
指摘漏れていたのですが、
こちらのメソッドはpublicではなく、privateで実装してください。

2022-03-08 06:17 UTC, hayato-kudo commented on myapp/app/models/task.rb
> +  def ends_on_must_be_after_starts_on
承知致しました。
修正致します。

2022-03-08 06:32 UTC, hayato-kudo commented on myapp/app/models/task.rb
> +  def ends_on_must_be_after_starts_on
なぜprivateで実装するのか
この日付逆転チェックはこのバリデーションでしか使われていないから。他の人が見た時にpublicだとどっか他に定義されているんじゃ無いかと混乱してしまう可能性があるからprivateで実装する。

2022-03-08 06:38 UTC, hayato-kudo commented
## 修正点
### **１、ends_on_must_be_after_starts_onメソッドをprivateで実装**
なぜprivateなのか・・・このメソッド（日付逆転チェック）はこのバリデーションでしか使用おらず、publicだと他に人が見た時に他でも呼び出されているのでは無いかと混乱してしまうため、privateで実装致しました。

以上が修正点になります。ご確認の程よろしくお願いたします。

2022-03-08 06:41 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  def ends_on_must_be_after_starts_on
>他に定義されているんじゃ無いか

定義ではなく呼び出しですね。

2022-03-08 06:41 UTC, R-KazumaInazaki approved these changes
LGTM

2022-03-08 06:43 UTC, merged