ステップ13: ステータスを追加して、検索できるようにしよう
Fablic/training pull request #1258
Opened 2022-03-10 02:34 UTC by hayato-kudo

## 仕様書
https://github.com/Fablic/training/blob/hayato-kudo/steps_jp.md#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9713-%E3%82%B9%E3%83%86%E3%83%BC%E3%82%BF%E3%82%B9%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%97%E3%81%A6%E6%A4%9C%E7%B4%A2%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%82%88%E3%81%86

## 追加点
### **1-1、ステータス（未着手・着手中・完了）を追加**
タスクを登録・編集の時に、プルダウンでstatus（未着手・着手中・完了）が選択できよう追加致しました。
また、statusは必須項目とするため、バリデーションを追加しました。

### **1-2、emun設定**
その際にはstatusをenumで設定したため、データの型をintegerに変更しました。既存のstatusカラムのデータの型を変更しようとしましたエラーが出てしまったため、一度カラム自体を削除して、もう一度追加する方法でカラムを追加しました。

### **1-3、enum日本語化**
emunで設定したものをi18nで日本語化するため、enum_helpというgemを追加しました。

### **2-1、一覧画面でタイトルとステータスで検索ができるようにしよう**
一覧画面（index.html.erb）にタスク名とステータスで検索できる検索フォームを追加しました。

### **3-1、検索インデックスを追加**
statusカラムに検索インデックスを貼りました。

### **4-1、検索に対してmodel specを追加**
新しく検索機能を実装したためテスト追加致しました。
<img width="943" alt="スクリーンショット 2022-03-10 11 09 08" src="https://user-images.githubusercontent.com/99626087/157576847-702781e1-52f2-4b3a-82b3-50a99225d367.png">

テストは上記の通りになります。
以上が追加点になります。ご確認の程よろしくお願い致します。

2022-03-10 06:40 UTC, hayato-kudo commented
## 修正点
### **１、cotrollerのテストケース追加**
検索機能の実装でcontrollerのテストケースを追加するのを忘れていましたので、追加致しました。
<img width="911" alt="スクリーンショット 2022-03-10 15 38 01" src="https://user-images.githubusercontent.com/99626087/157603705-12f805d4-a7f1-46b9-b7f5-18804c614e8f.png">

上記の画像が追加したテストケースとなっております。
### **２、enum_helpを使用せずに日本語化**
enumの日本語化において、enum_helpのgemを使用し日本語していましたが、enum_helpは使わないとのご指摘を頂いたので、メソッドを使い日本語化しました。

以上が修正点になります。ご確認の程よろしくお願致します。

2022-03-11 00:35 UTC, hayato-kudo commented
## 修正点
### **１、enumでi18n日本語化**
こちらメソッドを使用してstatusの値（yet_started・being_worked・done）を日本語化してましたが、メソッドを使わなくても日本語化できるやり方があり、そちらの方が分かりやすく書けたため修正致しました。


index.html.erb
<img width="848" alt="スクリーンショット 2022-03-11 9 26 31" src="https://user-images.githubusercontent.com/99626087/157778152-8fb1aedc-c619-4329-a908-e48d619167d3.png">

show.html.erb
<img width="190" alt="スクリーンショット 2022-03-11 9 27 34" src="https://user-images.githubusercontent.com/99626087/157778244-826fda35-f562-4cee-a208-ea82f975f5b2.png">

上記がstatusを日本語化した画像になります。

以上が修正点になります。
ご確認の程よろしくお願い致します。

2022-03-11 02:48 UTC, R-KazumaInazaki requested changes
レビューしました！

2022-03-11 02:48 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +            end
インデントがおかしいです。

2022-03-11 02:48 UTC, R-KazumaInazaki commented on myapp/config/locales/activerecord/ja.yml
> +  enums:
階層をactiverecordの配下に変えてください。

2022-03-11 02:48 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220309013101_remove_status_to_tasks.rb
> +class RemoveStatusToTasks < ActiveRecord::Migration[5.0]
この3つのmigrationファイル、１つにできませんか？

2022-03-11 02:48 UTC, R-KazumaInazaki commented on myapp/spec/requests/tasks_spec.rb
> +    subject(:task_name_status_serch) { get tasks_path, params: { status: 0 } }
searchのスペルが間違っています。

2022-03-11 02:48 UTC, R-KazumaInazaki commented on myapp/spec/requests/tasks_spec.rb
> +  describe 'status_partial_search' do
検索はindexの機能なので、indexのテストに書きましょう。

2022-03-11 02:48 UTC, R-KazumaInazaki commented on myapp/spec/requests/tasks_spec.rb
> +  describe 'status_partial_search' do
テストのパターンが足りません。
不正な値で検索した時のパターン、タイトル検索のパターン、タイトル検索とステータス検索を組み合わせた時のパターンを追加してください。

2022-03-11 02:51 UTC, hayato-kudo commented on myapp/config/locales/activerecord/ja.yml
> +  enums:
修正致します。

2022-03-11 02:51 UTC, hayato-kudo commented on myapp/app/controllers/tasks_controller.rb
> +            end
修正致します。

2022-03-11 02:56 UTC, hayato-kudo commented on myapp/spec/requests/tasks_spec.rb
> +    subject(:task_name_status_serch) { get tasks_path, params: { status: 0 } }
修正致します。

2022-03-11 03:05 UTC, hayato-kudo commented on myapp/db/migrate/20220309013101_remove_status_to_tasks.rb
> +class RemoveStatusToTasks < ActiveRecord::Migration[5.0]
修正致します。

2022-03-11 03:06 UTC, hayato-kudo commented on myapp/spec/requests/tasks_spec.rb
> +  describe 'status_partial_search' do
承知致しました。
テストを追加致します。

2022-03-11 03:27 UTC, hayato-kudo commented on myapp/spec/requests/tasks_spec.rb
> +  describe 'status_partial_search' do
テストパターンについてご質問がございます。

```
不正な値で検索した時のパターン = 選択肢以外を選択した時
タイトル検索のパターン = ステータスが無い時
```

の認識で合ってますでしょうか。

2022-03-11 03:50 UTC, R-KazumaInazaki commented on myapp/spec/requests/tasks_spec.rb
> +  describe 'status_partial_search' do
> 不正な値で検索した時のパターン = 選択肢以外を選択した時

定義されている3つのステータス以外の値が送信された時のパターン

> タイトル検索のパターン = ステータスが無い時

ステータスは未選択、タイトルのみの検索パターン
です。

2022-03-11 03:53 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/index.html.erb
> +  <%= select_tag(:status, options_for_select(Task.statuses.keys.map { |k| [t("enums.task.status.#{k}"), k]})) %>
これだと検索した時、必ず絞り込みをしなければならず、
一覧画面を開いた直後の、絞り込みを行っていない状態の一覧画面に戻ることができません。
ステータスの絞り込みを行わずに検索できるようにしてください。

2022-03-14 01:13 UTC, hayato-kudo commented on myapp/app/views/tasks/index.html.erb
> +  <%= select_tag(:status, options_for_select(Task.statuses.keys.map { |k| [t("enums.task.status.#{k}"), k]})) %>
修正します。

2022-03-14 08:08 UTC, hayato-kudo commented
## 修正点
### **１、tasks_controllerのインデント修正**
### **２、jaファイルのenumの階層を修正**
enumはActiveRecordで継承されているため、ActiveRecord配下に追加致しました。
### **３、３つのmigrationファイルを１つにまとめる。**
statusカラムの削除・statusカラムの追加・statusカラムにadd_indexの追加のmigrateを１つのファイルにまとめることで、見やすく致しました。
### **４、検索機能に対してのテスト追加**
<img width="1117" alt="スクリーンショット 2022-03-14 15 16 05" src="https://user-images.githubusercontent.com/99626087/158129467-5b6e099a-12a4-4ae7-8033-58874799f7c5.png">

上記の画像のテストを作成致しました。

### **５、検索機能の追加**
検索機能としての最低限の機能を実装追加しました。ステータスが「未選択」の時にはタスク名だけで検索できること、ステータスが「未選択」だけで値が送られた時には全て表示する機能を追加しました。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-15 03:41 UTC, R-KazumaInazaki requested changes

2022-03-15 03:41 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if ['yet_started','being_worked','done'].include?(params[:status])
この配列、ここで定義せずにModelに定義したenumから参照してほしいです。

2022-03-15 03:41 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  enum status: { not_selected: 0, yet_started: 1, being_worked: 2, done: 3 }
これ、タスクを作成するフォームで未選択が選択できてしまい、
データベースにも保存されてしまいます。

2022-03-15 03:41 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220309013101_remove_status_to_tasks.rb
> +class RemoveStatusToTasks < ActiveRecord::Migration[5.0]
migrationファイルの名前と中身の処理が一致していません。

2022-03-15 03:41 UTC, R-KazumaInazaki commented on myapp/spec/requests/tasks_spec.rb
> +    context 'タスク名とステータスを同時検索した時' do
これは修正しなくて良いですが、AND検索をテストするときはパターンとして、
- 両方の条件に一致するデータは検索に引っかかること
- 片方の条件に一致するデータは検索に引っかからないこと（←今回はこちらのパターンがない）

の２パターンはほしいです。

2022-03-15 05:13 UTC, hayato-kudo commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if ['yet_started','being_worked','done'].include?(params[:status])
修正致します。

2022-03-15 05:13 UTC, hayato-kudo commented on myapp/app/models/task.rb
> +  enum status: { not_selected: 0, yet_started: 1, being_worked: 2, done: 3 }
修正致します。

2022-03-15 05:14 UTC, hayato-kudo commented on myapp/spec/requests/tasks_spec.rb
> +    context 'タスク名とステータスを同時検索した時' do
承知致しました。
確認しておきます。

2022-03-15 08:12 UTC, hayato-kudo commented
## 修正点
### **１、Modelで定義したenumから参照**
そのまま配列で書いていましたが、modelからenumを参照しました。
### **２、enumの未選択削除**
enumの未選択を削除して、viewに未選択を追加しました。
### **３、migrationファイルの名前変更**
migrationファイルの名前と中身の処理が一致していなかったので、統一致しました。

以上が変更点になります。ご確認の程よろしくお願い致します。

2022-03-15 08:28 UTC, R-KazumaInazaki requested changes

2022-03-15 08:28 UTC, R-KazumaInazaki commented on myapp/.byebug_history
> +q
不要なファイルは削除してください。
あと、このファイルはよく生成されるのでgitignoreしてもいいと思います。

2022-03-15 08:28 UTC, R-KazumaInazaki commented on myapp/spec/requests/tasks_spec.rb
> +      subject(:task_name_status_search) { get tasks_path, params: { status: 0 } }
未選択の時のparamsは`status: 0`ではないと思います。

2022-03-15 08:37 UTC, hayato-kudo commented on myapp/.byebug_history
> +q
修正致します。

2022-03-15 08:43 UTC, hayato-kudo commented
## 修正点
### **１、byebug_historyのファイルを削除**
削除と同時に今後pushされないように、gitignoreに追加致しました。
### **２、tasks_controllerのテストを修正**
未選択をenumから削除したことで、テストの変更が必要になったため、修正致しました。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-15 08:54 UTC, hayato-kudo commented
## 修正点
### **１、controllerのテスト修正**
未選択はenumから削除したため、enumで未選択は使用できなくなりました。
そのため、未選択のテストの修正を行いました。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-15 08:56 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-03-15 08:57 UTC, merged