ステップ14: ページネーションを追加しよう
Fablic/training pull request #1260
Opened 2022-03-11 01:35 UTC by hayato-kudo

## 仕様書
https://github.com/Fablic/training/blob/hayato-kudo/steps_jp.md#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9714-%E3%83%9A%E3%83%BC%E3%82%B8%E3%83%8D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%97%E3%82%88%E3%81%86

## 追加点
### **１、ページネーションの追加**
kaminariというgemを使って、ページネーションを追加しました。
同時に、ページネーションの日本語をja.ymlに追加しました。

### 1ページ目
<img width="828" alt="スクリーンショット 2022-03-11 10 31 07" src="https://user-images.githubusercontent.com/99626087/157784484-8257bcc2-0bf0-4abd-bf0a-f9fa27a64022.png">

### 2ページ目
<img width="688" alt="スクリーンショット 2022-03-11 10 31 27" src="https://user-images.githubusercontent.com/99626087/157784514-0c3588e8-b019-4c40-8e11-edd9ab7dab8f.png">

以上が追加点になります。ご確認の程よろしくお願い致します。

2022-03-11 02:30 UTC, R-KazumaInazaki requested changes
レビューしました。
コメント以外の指摘ですが、specが無いので追加しましょう。

2022-03-11 02:30 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +               Task.all.page(params[:page]).per(5)
１ページに表示する数はモデル側で定義してください。
参考：
https://github.com/kaminari/kaminari#configuring-default-per_page-value-for-each-model-by-paginates_per

2022-03-11 02:30 UTC, R-KazumaInazaki commented on myapp/config/locales/activerecord/ja.yml
> +  views:
ja.yml、
activerecordとviewでディレクトリ切り分けているのでは…？
https://github.com/Fablic/training/tree/hayato-kudo/myapp/config/locales

2022-03-11 02:34 UTC, hayato-kudo commented on myapp/app/controllers/tasks_controller.rb
> +               Task.all.page(params[:page]).per(5)
承知致しました。
修正致します。

2022-03-11 02:39 UTC, hayato-kudo commented on myapp/config/locales/activerecord/ja.yml
> +  views:
修正致します。

2022-03-16 06:20 UTC, hayato-kudo commented
## 修正点
### **１、ページ数の設定**
1ページに表示する数をデフォルトで変更したかったためmodel側で定義しました。
### **２、ja.ymlを修正**
activerecordとviewでディレクトリ切り分けているので、ページネーションの日本語をview/ja.ymlに追加しました。
### **３、kaminariのspec追加**
kaminariのspecが不足していたため、追加しました。
<img width="720" alt="スクリーンショット 2022-03-16 15 17 22" src="https://user-images.githubusercontent.com/99626087/158528625-500f3796-5642-4e0c-a17d-075442f29c83.png">

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-23 08:36 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  paginates_per 5
privateを消す必要はないと思います。
今作業しているブランチであわせて修正してください。

2022-03-23 08:36 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-03-23 08:43 UTC, hayato-kudo commented on myapp/app/models/task.rb
> +  paginates_per 5
修正致します。

2022-03-23 08:47 UTC, merged