ステップ17: ログイン/ログアウト機能を実装しよう
Fablic/training pull request #1271
Opened 2022-03-24 09:10 UTC by hayato-kudo

## 仕様書
https://github.com/Fablic/training/blob/hayato-kudo/steps_jp.md#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9717-%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%83%AD%E3%82%B0%E3%82%A2%E3%82%A6%E3%83%88%E6%A9%9F%E8%83%BD%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%97%E3%82%88%E3%81%86

## 追加点
### **１、ログイン機能の実装**
<img width="273" alt="スクリーンショット 2022-03-24 18 09 21" src="https://user-images.githubusercontent.com/99626087/159881825-29888d51-d3d6-4eb8-b2fb-1f6096706616.png">

ユーザーのemailとpasswordの両方が一致していればサインインできるよう実装しました。
その際にページに遷移してもログイン状態を保ちたかったので、session[:user_id]にuser.idを入れました。
また、ログインしてない場合はログイン画面にリダイレクトするよう設定しました。
### **２、ログアウト機能実装**
ログイン後タスク一覧ページに遷移し、ログアウトボタンを設置しました。
<img width="749" alt="スクリーンショット 2022-03-24 18 06 06" src="https://user-images.githubusercontent.com/99626087/159881250-567a06da-b432-4a91-8972-7c165c1b2d0a.png">

### **３、ログイン機能に対するテスト追加**
session_specにログイン機能・ログアウト機能のテスト追加しました。
<img width="861" alt="スクリーンショット 2022-03-24 17 50 59" src="https://user-images.githubusercontent.com/99626087/159881521-d7ae7394-c13c-46fa-9967-c10eea51ce1d.png">
上記の画像の通りテストを追加しました。

以上が追加点になります。ご確認の程よろしくお願い致します。

2022-03-25 00:20 UTC, YutaOda commented on myapp/app/controllers/sessions_controller.rb
> +      redirect_to tasks_path, notice: "you have successfully login"
他が日本語なので日本語にしましょう。
あるべきで言えばi18n対応すべき（他のnoticeも可能なら）なのでja.ymlに移動できるとベスト

2022-03-25 00:21 UTC, YutaOda commented on myapp/app/controllers/sessions_controller.rb
> +  def new
不要？

2022-03-25 00:41 UTC, YutaOda commented on myapp/app/controllers/tasks_controller.rb
> +      redirect_to  tasks_path
ユーザーが異なる場合一覧ページに戻ってるかと思います。
ユーザーが本来到達できないページへ遷移しようとしている場合、404ページに遷移が正しい挙動かなと思います。

（ちなみにIDが存在しない場合、どこにいきますか？こちらももし一覧へ遷移している場合は404へ飛ばすようにしたいです）

補足
以下の2つが挙動が異なると「このIDは存在するんだ」ということが伝わってしまう。
・IDが存在するけど所有者が異なる
・IDが存在しない
→研修なので分かりにくいですが、実在するサービスだとそれがきっかけで不正アクセスへの取っ掛かりになる可能性があるので注意。

補足の補足
ID,PWの組み合わせエラーも、一昔前はIDが存在してPWが異なる場合「パスワードが違います」と出ていたが、
近年は「IDかパスワードが違います」と言うようになった。
これも同じ話で、IDが存在することが悪い人に伝わらないようにする配慮ですね。

2022-03-25 00:42 UTC, YutaOda commented on myapp/app/helpers/sessions_helper.rb
> +module SessionsHelper
このmoduleはなんのためのものでしょう？

2022-03-25 00:50 UTC, YutaOda commented on myapp/app/controllers/tasks_controller.rb
> +    unless @task.user.id == current_user.id
↑で作るかもしれないユーザーIDでの絞り込みを29行目で使えば
・存在したらその画面に遷移
・存在しなければエラー
とシンプルにできそう（unlessを書く必要がなくなるのでは）

2022-03-25 00:50 UTC, YutaOda commented on myapp/spec/views/sessions/new.html.erb_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
pendのspecしかないですが、これは必要でしょうか

2022-03-25 00:52 UTC, YutaOda commented on myapp/spec/helpers/sessions_helper_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
（書いてあることを日本語にして言っているだけですが）
pendのspecしかないですが、これは必要でしょうかor何かケースを追加すべき？

2022-03-25 00:52 UTC, YutaOda commented on myapp/app/controllers/tasks_controller.rb
> +               Task.where(user_id: current_user.id).includes([:user]).where(status: params[:status]).task_name_partial_search(params[:task_name]).page(params[:page])
task_name_partial_search同様、
where(user_id: current_user.id).includes([:user])
あたりをscopeに入れるともう少しスッキリできそうです。

2022-03-25 01:09 UTC, hayato-kudo commented on myapp/app/controllers/sessions_controller.rb
> +      redirect_to tasks_path, notice: "you have successfully login"
修正致します。

2022-03-25 01:10 UTC, hayato-kudo commented on myapp/app/controllers/tasks_controller.rb
> +      redirect_to  tasks_path
修正致します。

2022-03-25 01:12 UTC, hayato-kudo commented on myapp/app/controllers/sessions_controller.rb
> +  def new
newアクションは必要ないので、削除致します。

2022-03-25 01:17 UTC, hayato-kudo commented on myapp/app/controllers/tasks_controller.rb
> +    unless @task.user.id == current_user.id
修正致します。

2022-03-25 01:19 UTC, hayato-kudo commented on myapp/spec/views/sessions/new.html.erb_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
これはcontroller作成時に自動で作られてしまったものでした。
必要ないので削除します。

2022-03-25 01:22 UTC, hayato-kudo commented on myapp/spec/helpers/sessions_helper_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
こちらもsessionのcontrollerを作成したときに作られてしまいました。
削除致します。

2022-03-25 01:22 UTC, hayato-kudo commented on myapp/app/controllers/tasks_controller.rb
> +               Task.where(user_id: current_user.id).includes([:user]).where(status: params[:status]).task_name_partial_search(params[:task_name]).page(params[:page])
修正致します。

2022-03-25 03:46 UTC, hayato-kudo commented on myapp/app/controllers/tasks_controller.rb
> +      redirect_to  tasks_path
render "public/404.html"にして404ページにrenderするように設定していますが、なぜか500にrenderしてしまっています。
`Completed 500 Internal Server Error in 33ms (ActiveRecord: 2.2ms)`
どのようにすれば404にrenderされるかご教授お願い致します。

2022-03-25 09:00 UTC, hayato-kudo commented
## 修正点
### **１、ログイン・ログアウトのフラッシュメッセージをi18n化**
ログイン・ログアウトのフラッシュメッセージが英語表記だったので日本語に修正致しました。

<img width="770" alt="スクリーンショット 2022-03-25 10 34 57" src="https://user-images.githubusercontent.com/99626087/160077443-f411e124-0d5b-4b2e-b87c-299d445de987.png">

<img width="307" alt="スクリーンショット 2022-03-25 16 45 10" src="https://user-images.githubusercontent.com/99626087/160077470-a5b95f4d-66ab-451f-a6b0-644cf2875be1.png">

### **２、sessions_controller修正**
ログイン(create)とログアウト(destroy)だけ実装したかったのでnewアクションは削除しました。

### **３、投稿者以外がタスクの詳細・編集ができないこと**
投稿者以外がタスクの詳細と詳細と編集ページに遷移した時に404にrenderするように設定しました。

### **４、tasks_controllerのshowアクション修正**
unlessを使わなくて、if文でシンプルに処理を書けたので修正致しました。

### **５、tasks_controllerのindexアクション修正**
可読性を上げるために、scopeを使いました。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-28 00:46 UTC, hayato-kudo commented
## 修正点
### **１、ログイン失敗時のエラーメッセージ追加**
ログイン失敗時にエラーメッセージを追加しました。i18n化を使って日本語で表示しています。

<img width="385" alt="スクリーンショット 2022-03-28 9 36 18" src="https://user-images.githubusercontent.com/99626087/160308882-785a2da5-9b45-4bc9-a3be-3af35e1f1ac1.png">

### **２、コメントアウト削除**
コメントアウトしていた不要なところを削除しました。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-28 04:35 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いします。

2022-03-28 04:35 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      render_404
specにパターンがないので追加してください。
editも同様です。

2022-03-28 04:35 UTC, R-KazumaInazaki commented on myapp/app/controllers/sessions_controller.rb
> +      redirect_to login_form_path, notice: (t 'users.flash.create.error_notice')
redirectではなくrenderのほうが良いと思います。

2022-03-28 04:35 UTC, R-KazumaInazaki commented on myapp/app/controllers/application_controller.rb
> +    User.find_by(id: session[:user_id])
session[:user_id]の中身があるかチェックしてください。
この実装だと毎回SQLが叩かれてしまうので修正してください。

2022-03-28 04:35 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +  def logged_in_user
ここに書いてしまうと、他にログインが必要な画面が実装された時に、
そのコントローラにも実装する必要が出てきてしまいます。

2022-03-28 07:10 UTC, hayato-kudo commented on myapp/app/controllers/tasks_controller.rb
> +      render_404
ログインしているuserのidと、user.idが一致していたらタスクの詳細を見れる処理をspecに記載する時は
まず最初にログインしているユーザーに紐付けてタスクを作成する考え方で合ってますでしょうか。

2022-03-29 00:27 UTC, hayato-kudo commented
## 修正点
### **１、tasks_controllerのspec追加**
showとeditのテストが不足していたため追加致しました。
<img width="416" alt="スクリーンショット 2022-03-29 9 18 47" src="https://user-images.githubusercontent.com/99626087/160508156-95b94820-c29b-49bf-848c-a2b82f65d4d1.png">

上記の画像の通り追加しました。

### **２、tasks_controller修正**
find_byではエラーが起きた時に明確にならないため、findに修正しました。


以上が修正点になります。ご確認のほどよろしくお願い致します。

2022-03-29 01:18 UTC, R-KazumaInazaki requested changes

2022-03-29 01:18 UTC, R-KazumaInazaki commented on myapp/app/controllers/application_controller.rb
> +    def logged_in_user
インデントがおかしいです。

2022-03-29 01:18 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +                  .page(params[:page])
このようにメソッドチェーンを改行するときは、ドットの開始位置をあわせましょう
```suggestion
                Task.includes([:user])
                    .user_id_search(current_user.id)
                    .task_name_partial_search(params[:task_name])
                    .where(status: params[:status])
                    .page(params[:page])
```

2022-03-29 01:18 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +                  .user_id_search(current_user.id)
current_user.tasksでユーザーに紐づくタスクを取得できます。
そうすれば、`includes([:user])`は必要なくなり、`user_id_search`のように検索する必要もなくなります。

2022-03-29 01:18 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +                  .page(params[:page])
こちらもインデント揃えてください。

2022-03-29 01:18 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  scope :user_id_search, -> (user_id) { where(user_id: user_id) }
このメソッドは不要になります。

2022-03-29 01:18 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/index.html.erb
> +  <%= t '.label' %>:<%= text_field_tag :label %>
これは次のステップの内容なので、戻しておいてください。

2022-03-29 01:18 UTC, R-KazumaInazaki commented on myapp/app/views/sessions/new.html.erb
> +<%= alert %>
alertも移動して良さそう

2022-03-29 01:21 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    if @task.user.id == current_user.id
こちらの指摘が対応されてないです
https://github.com/Fablic/training/pull/1271#discussion_r834865268

2022-03-29 01:21 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    if @task.user.id == current_user.id
こちらも同様です。
https://github.com/Fablic/training/pull/1271#discussion_r834865268

2022-03-29 03:04 UTC, hayato-kudo commented
## 修正点
### **１、user_id_searchメソッド削除**
user_idを探すメソッドではなく、current_user.tasksで紐付くタスクを取得できるのでuser_id_searchメソッドは不要になり削除しました。
### **２、tasks_controller修正**
https://github.com/Fablic/training/pull/1271#discussion_r834865268
の対応ができていなかったので、こちらを修正致しました。
また、updateとdestroyに関しても、if文をネストさせ、@taskに値が入っている時と入っていない時の処理を追加しました。

以上が修正点になります。ご確認の程よろしくお願い致します。

2022-03-29 03:10 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-03-29 04:01 UTC, YutaOda approved these changes
対応ありがとうございます！
LGTMです！

2022-03-29 04:17 UTC, merged