Kenta kanbe step05
Fablic/training pull request #1287
Opened 2022-04-25 06:30 UTC by kentakanbe

## 要件（仕様書など）
作りたいアプリケーションのイメージを考える
## 修正概要
DB設計、画面設計の作成、追加
## 実装内容
■ DB設計
 - モデル図追加
 - READMEにデータスキーマ記載

■ 画面設計
 - 基本画面イメージの追加
## 動作確認（操作内容、画面キャプチャなど）
なし

2022-04-25 23:57 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-04-25 23:57 UTC, R-KazumaInazaki commented on myapp/README.md
> +|  label_id  |  INT  |    |    |  -1 |
tasksとlabelsがER図上、n対nの関係ですが、label_idカラムで持つと実現できないと思います。

2022-04-25 23:57 UTC, R-KazumaInazaki commented on myapp/README.md
> +|  password  |  VARCHAR(256)  |  NO  |    |    |
パスワードはそのままの文字列で保存するイメージですか？
もし暗号化して保存する場合、それがわかるような、例えばencrypted_passwordのほうが扱いやすいです。

2022-04-25 23:57 UTC, R-KazumaInazaki commented on myapp/README.md
> +|  termination_date  |  DATETIME  |  NO  |    |    |
個人差ありますが、
`*_date`はDATE型のカラムのように見えます。
DATETIME型の時はcreated_atやupdated_atと同様に、`*_at`がわかりやすいです。
参考
https://techracho.bpsinc.jp/hachi8833/2017_11_01/47310

2022-04-25 23:57 UTC, R-KazumaInazaki commented on myapp/README.md
> +|  label  |  VARCHAR(256)  |  NO  |    |    |
たぶんラベルの名前が入るカラムだと思いますが、このカラムを使うときに`label.label`と冗長なコードとなってしまいます。
`label.name`等のほうが伝わりやすいです。

2022-04-25 23:57 UTC, R-KazumaInazaki commented on myapp/README.md
> +|  status  |  INT  |  NO  |    |    |
priorityやstatusはINT型では過剰です。
TINYINT(4)でつくりましょう。
参考
https://www.for-engineer.life/entry/rails-int-migration/

2022-04-26 01:55 UTC, kentakanbe commented on myapp/README.md
> +|  label_id  |  INT  |    |    |  -1 |
中間テーブルとしてtasks_labelsを追加いたしました。
※テーブル名に関しては、has_many: throughを使用する場合にはテーブル名の結合ではなく、意味のわかるテーブル名を命名した方が良いと認識しておりますが、今回の場合はそのまま結合した文字列の方がわかりやすいのではないかと考え(適切な命名が思いつかなかった為...)、そちら採用しております。
■ 参照したURL
https://qiita.com/at_sushi/items/0423b3714bcd0894476e

2022-04-26 01:57 UTC, kentakanbe commented on myapp/README.md
> +|  password  |  VARCHAR(256)  |  NO  |    |    |
ご指摘の通りです。
暗号化する想定のため、「encrypted_password」に変更いたしました。

2022-04-26 02:00 UTC, kentakanbe commented on myapp/README.md
> +|  label  |  VARCHAR(256)  |  NO  |    |    |
ご指摘の通りです。
「name」に変更いたしました。

2022-04-26 02:00 UTC, kentakanbe commented on myapp/README.md
> +|  termination_date  |  DATETIME  |  NO  |    |    |
ご指摘ありがとうございます！
上記、確認いたしました。今後気を付けて参ります。
該当カラム名も「termination_at」に変更しました。

2022-04-26 02:04 UTC, kentakanbe commented on myapp/README.md
> +|  status  |  INT  |  NO  |    |    |
ご指摘の通りです。失礼いたしました。
今後も無駄な容量を確保せずパフォーマンス面を考慮するよう注意いたします。
tasks.priority, statusと、labels.colorに関しても「TINYINT(4)」に変更しました。
※ラベルカラーに関して、一旦は255色で十分ではと考えたため

2022-04-26 02:59 UTC, R-KazumaInazaki commented on myapp/README.md
> +|  label_id  |  INT  |    |    |  -1 |
なるほど！自分もあまり意識したことがなかったです。
記事を参考にするなら、labeling、などが良さそうですね。
いったん今回はtasks_labelsで良いと思います！

2022-04-26 03:01 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-04-26 03:05 UTC, merged