ステップ20: タスクにラベルをつけられるようにしよう
Fablic/training pull request #1316
Opened 2022-06-07 05:53 UTC by kentakanbe

## 要件（仕様書など）
[ステップ20: タスクにラベルをつけられるようにしよう](https://github.com/Fablic/training/blob/develop/steps_jp.md#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9720-%E3%82%BF%E3%82%B9%E3%82%AF%E3%81%AB%E3%83%A9%E3%83%99%E3%83%AB%E3%82%92%E3%81%A4%E3%81%91%E3%82%89%E3%82%8C%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%82%88%E3%81%86)
## 修正概要
※ 以下、本ステップの内容とは別にリファクタリングを実施しております。
該当コミット -> https://github.com/Fablic/training/commit/1797ed8a9aff10ff27e2bdb985cb745e9d2012d6

## 実装内容

## 動作確認（操作内容、画面キャプチャなど）

2022-06-09 03:52 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-06-09 03:52 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +    <% @task.labels.each do |label| %>
もしlabelsのnameだけを取り出したいのであれば、pluckが便利です。
結果が配列で来るので、join等で操作がしやすいです。
実装したいことが実現できるかわかりませんが試してみてください。
```
pry(main)> @task.labels.pluck(:name)
=> [
    [0] "label1",
    [1] "label2"
]
pry(main)> @task.labels.pluck(:name).join(" ")
=> "label1 label2"
```

2022-06-09 03:52 UTC, R-KazumaInazaki commented on myapp/config/locales/views/tasks/ja.yml
>        priority_select: '選択して下さい(優先度)'
使ってない？なら消すか、将来的にselect boxになる気はするので合わせても良さそう

2022-06-09 03:52 UTC, R-KazumaInazaki commented on myapp/spec/controllers/tasks_controller_spec.rb
> +        let!(:tasks_label) { create(:tasks_label, task_id: for_search_task.id, label_id: for_search_label.id) }
tasks_labelは多対多を実現するための副次的なレコードなので、taskのfactoryにtraitを実装するのが良いと思いました。
以下の記事は1対多ですが、参考になると思います。
https://dev.to/n350071/rspec-factorybot-transient-trait-with-argument-2djd

2022-06-09 03:52 UTC, R-KazumaInazaki commented on myapp/spec/controllers/tasks_controller_spec.rb
> +        let!(:for_search_task) { create(:task, data_for_search_task) }
変数名でfor_が先にくるのはあまり直感的ではなく、変数そのものの正体がわかりづらいです。
この場合であれば、`task_for_search`が良さそうです。

2022-06-09 03:52 UTC, R-KazumaInazaki commented on myapp/spec/models/label_spec.rb
> +  describe 'Association' do
もしかしたら人によるかもですが、associationのテストは不要だと思います。
理由として、associationを直接テストしなくても、controller等で間接的に利用されるからです。

2022-06-09 03:52 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  scope :extract_matched_label, ->(label_id) { where(labels: { id: label_id }) if label_id.present? }
スクリーンショットを見ると、label1で検索をした時に、test02は2つのラベルを持ってるはずなのにlabel1しか表示されなくなっています。
こちら原因を特定して、可能であれば修正をお願いします。
（時間かかりそうであれば、研修なのでスキップでも良いです）

2022-06-10 07:45 UTC, kentakanbe commented on myapp/app/views/tasks/show.html.erb
> +    <% @task.labels.each do |label| %>
上記ご教示頂き有難うございます！
確かに不必要なデータまで保持するのは無駄ですね。。
pluckで取得するよう修正いたしました！

2022-06-10 07:46 UTC, kentakanbe commented on myapp/config/locales/views/tasks/ja.yml
>        priority_select: '選択して下さい(優先度)'
上記、新規タスク作成画面における「ステータス選択プルダウン」への表示文字列として使用しておりました。
動作として問題はないですが、画面上での表記揺れをなくす為、以下定義を分けました。
・form(タスク新規作成・編集テンプレート)
・search(タスク検索テンプレート)

■ 修正前(「選択して下さい({項目名})」「指定可({項目名})」が混在)
<img width="630" alt="スクリーンショット 2022-06-10 16 42 32" src="https://user-images.githubusercontent.com/103913705/173016268-243ebf05-d985-48a8-8e61-9d46e0f666cc.png">


■ 修正後(「選択して下さい({項目名})」または「指定可({項目名})」に統一)
<img width="630" alt="スクリーンショット 2022-06-10 16 41 35" src="https://user-images.githubusercontent.com/103913705/173016285-bbcb09fd-d86c-4c5b-970a-e12584f46895.png">

2022-06-10 07:46 UTC, kentakanbe commented on myapp/spec/controllers/tasks_controller_spec.rb
> +        let!(:tasks_label) { create(:tasks_label, task_id: for_search_task.id, label_id: for_search_label.id) }
ご教示頂き有難うございます！
とても勉強になります(自身でももっと勉強しておきます...！)
trait / transient を使用し作成する形に修正いたしました。

2022-06-10 07:46 UTC, kentakanbe commented on myapp/spec/controllers/tasks_controller_spec.rb
> +        let!(:for_search_task) { create(:task, data_for_search_task) }
上記ご指摘頂き、有難うございます！
変数名に関してもパッと見て理解できるよう、わかりやすい名前になるよう意識します。
全体を通じてforが先頭に来ている変数名を変更いたしました。

2022-06-10 07:46 UTC, kentakanbe commented on myapp/spec/models/label_spec.rb
> +  describe 'Association' do
ご指摘頂き、有難うございます！
確かに過剰ですね...association関連テストを削除いたしました。

2022-06-10 07:52 UTC, kentakanbe commented on myapp/app/models/task.rb
> +  scope :extract_matched_label, ->(label_id) { where(labels: { id: label_id }) if label_id.present? }
上記ご指摘頂き、有難うございます！
また動作確認不足失礼いたしました。

■ 原因：「whereによる絞り込み」
searchメソッドにてincludes(:labels)として関連ラベルデータを同時に取得しているが、後続のwhere句によって検索時に指定したlabels.idによる絞り込みを行ない、条件に一致するデータのみ@tasksに格納しておりました。
viewにてtask.labelsとしてラベルデータを取得していますが、この時点でSQLの発行はされず(N+1回避の点では正常ですが)、search時に格納したラベルデータを取得する為、ご指摘頂いた現象(検索時に指定したラベルのみ表示される)が発生しております。

(例)1タスクに2つのラベルが設定されている状態(task.id = 1に対して、label.id = 1, 2 が紐づく)で、検索時にlabel.id = 1を指定した場合
→where句でlabel.id = 1を指定する為、結果にはラベルデータとしてlabel.id = 1のみ格納される(その他ラベルであるlabel.id = 2は格納されていない)

■ 解決方法
現在の実装では、条件に一致するタスクデータは特定できているので、一致したタスクデータのtask.idを配列で取得し、そのidを利用して、再度includes(:labels)を使用したタスク及びラベルデータの取得を行う形に修正しました。

2022-06-10 08:14 UTC, kentakanbe commented on myapp/spec/controllers/tasks_controller_spec.rb
>              subject.call
上記、アドバイス頂いた通り、1タスクに対して複数ラベル設定されている場合の試験に変更いたしました。

2022-06-10 08:15 UTC, kentakanbe commented on myapp/spec/controllers/tasks_controller_spec.rb
> +          it 'input_search_paramsによるバリデーション後の値を使用し、検索条件に一致するデータを1件(ラベル2つ設定)取得していること' do
上記、アドバイス頂いた通り、1タスクに対して複数ラベル設定されている場合の試験に変更いたしました。

2022-06-10 08:22 UTC, kentakanbe commented
お忙しいところご確認頂き有難うございます！
以下、対応いたしましたのでご確認頂けますと幸いです。
- https://github.com/Fablic/training/pull/1316/commits/b3f3bbd17b901dabc27d275378255c4c7f0ff740

2022-06-10 09:58 UTC, kentakanbe commented on myapp/app/views/tasks/show.html.erb
> +    <% @task.labels.each do |label| %>
先程のご指摘頂いた内容で修正いたしました！
※動作確認済
■ タスク一覧画面
<img width="671" alt="スクリーンショット 2022-06-10 18 46 09" src="https://user-images.githubusercontent.com/103913705/173041335-6d36ad17-6ad9-4a9e-9c0f-72c82451778d.png">

2022-06-13 03:54 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +    <% @task.labels.pluck(:name).each do |name| %>
こちらも修正できそう。

2022-06-13 03:54 UTC, R-KazumaInazaki commented on myapp/spec/factories/task.rb
> +        labels { Label.first || create(:label, name: 'sample_label01') }
テストの中で使う時に、factory側で処理を行ってしまうと見通しが悪くなってしまいます。
同じラベルに紐づくタスクを作るなら、テスト側でラベルを作り、それを引数で渡すような使い方が良いです。
そうなると、こちらのtraitは不要になるかなと思います。

2022-06-13 03:54 UTC, R-KazumaInazaki commented on myapp/spec/models/task_spec.rb
> +  describe 'Dependent' do
dependentのテストもAssociationと同様の理由で不要だと思っています！

2022-06-13 03:54 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +                              includes(:labels)
この行の`includes(:labels)`は無くても良さそう？

2022-06-13 05:51 UTC, kentakanbe commented on myapp/app/views/tasks/show.html.erb
> +    <% @task.labels.pluck(:name).each do |name| %>
上記ご指摘の通りでございます。確認不足失礼いたしました...！
こちらもjoinを使用する形へ修正しました。
※動作確認済

■ タスク詳細画面
<img width="586" alt="スクリーンショット 2022-06-13 14 50 28" src="https://user-images.githubusercontent.com/103913705/173288224-41919f5b-7bc2-4fe0-b8f6-bb224a15cbaa.png">

2022-06-13 06:00 UTC, kentakanbe commented on myapp/spec/factories/task.rb
> +        labels { Label.first || create(:label, name: 'sample_label01') }
上記ご教示頂き有難うございます！
確かにテスト側で設定するラベルを明確に指定することで、見通しは大分改善されますね。。
とても勉強になります！今後の実装にも活かして参ります。
ご指摘頂いた内容で修正いたしました！

2022-06-13 06:01 UTC, kentakanbe commented on myapp/spec/models/task_spec.rb
> +  describe 'Dependent' do
失礼致しました！
ご指摘頂いた通り、dependentに関しても削除いたしました。

2022-06-13 06:38 UTC, kentakanbe commented on myapp/app/models/task.rb
> +                              includes(:labels)
ユーザが検索時にラベルを指定した場合、extract_matched_labelにてlabels.idをwhere句の検索条件として指定する為、この時点でもJOIN(includes(:labels))が必要であると考えております。
※27行目：includes(:labels)を無くした場合、`Mysql2::Error: Unknown column 'labels.id' in 'where clause'`が発生することを確認

上記、もし認識違いございましたらご指摘頂けますと幸いです...！

2022-06-13 06:51 UTC, kentakanbe commented
レビュ指摘対応及び回答を記載いたしました。
再度となり大変申し訳ございませんが、お手隙の際にご確認頂けますと幸いです。

2022-06-13 07:21 UTC, R-KazumaInazaki commented on myapp/spec/models/task_spec.rb
> +        let!(:task02_for_search) { create(:task, :with_label, data02) }
今更ですが、このように中身の値が変化するならそれぞれのテストでcreate(:task)を呼んだほうが、このテストではこのデータを用意している、というのがわかりやすくて良いですね！
ただ、先の研修に進んでほしいので今回はこのままで良いです〜

2022-06-13 07:22 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-06-13 07:35 UTC, kentakanbe commented on myapp/spec/models/task_spec.rb
> +        let!(:task02_for_search) { create(:task, :with_label, data02) }
上記ご指摘頂き有難うございます！
ご指摘の通りだと思います。。
確かに実装を進めていく中でletによる変数化に拘りすぎて、一部わかりづらくなってしまっているのではないかと感じる部分が自分の中でもございました。
改めてこの研修を通じてご指摘を受けてきた、Rpsecにおいては「何よりもわかりやすさを重視すべき」という点を意識して今後の業務に当たって参ります。

2022-06-13 07:37 UTC, merged