Step3〜Step6 プルリクエスト
Fablic/training pull request #1353
Opened 2022-08-08 00:44 UTC by connect-yuma-nakamura

■対応内容
- STEP3
  - 環境変数 COMPOSE_PROJECT_NAME 設定
  - config/database.yml のDB接続を環境変数を使用するよう修正
- STEP5
  - ReadMeへDB設計、画面設計を記載
- STEP6
  - モデル生成 (Tasks、Users）
- その他
  - gitignore作成
    → 研修に記載されているコマンドでは明示的にgitignoreの生成をスキップしていたのですが、tmp配下やログファイルなど自動生成、自動変更されるファイルがあまりにも多くgit管理上良くないと判断し、追加しました。

2022-08-08 11:17 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。
またPRの説明欄について、次回から以下の項目を追記していただけると幸いです。
- 要件
  1. 各STEPに記載されている課題をそのまま転記で問題ありません
- 動作確認（スクリーンショット等）
  1. 実装したものを確認する手順を記載してください
  2. 画面を作成・修正した場合は画面のスクリーンショットを、テーブルを作成・修正した場合は変更後のテーブル構成がわかるスクリーンショットを添付してください

2022-08-08 11:17 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220805081451_create_tasks.rb
> +      t.string :title, :limit => 128, :null => false, :default => ''
ハッシュの書き方について、現場に合わせる形となってしまいますが、
以下のように`=>`を使わない書き方で統一していただきたいです。
```suggestion
      t.string :title, limit: 128, null: false, default: ''
```

2022-08-09 00:24 UTC, connect-yuma-nakamura commented on myapp/db/migrate/20220805081451_create_tasks.rb
> +      t.string :title, :limit => 128, :null => false, :default => ''
> レビューしましたのでご確認お願いいたします。
またPRの説明欄について、次回から以下の項目を追記していただけると幸いです。
> 
> 要件
> 各STEPに記載されている課題をそのまま転記で問題ありません
> 動作確認（スクリーンショット等）
> 実装したものを確認する手順を記載してください
> 画面を作成・修正した場合は画面のスクリーンショットを、テーブルを作成・修正した場合は変更後のテーブル構成がわ> かるスクリーンショットを添付してください
追記しました。

> ハッシュの書き方について、現場に合わせる形となってしまいますが、
> 以下のように=>を使わない書き方で統一していただきたいです。
ご指摘のように```=>```を使用しない記述に修正しました。

2022-08-09 01:26 UTC, R-KazumaInazaki approved these changes
LGTM！

（次回以降もですが、LGTMしてもらえたらご自身でマージお願いいたします）

2022-08-09 01:56 UTC, merged