Step7
Fablic/training pull request #1359
Opened 2022-08-10 05:56 UTC by nanae-kusakari

下記を対応いたしましたので、お手数ですがご確認をお願いいたします。

■要件
ステップ7: タスクを登録・更新・削除できるようにしよう
* タスクの一覧画面、作成画面、詳細画面、編集画面を作成しましょう
    * rails generate コマンドでコントローラとビューを作成します
    * コントローラとビューに必要な実装を追加しましょう
    * 作成、更新、削除後はそれぞれflashメッセージを画面に表示させましょう
* routes.rb を編集して、 http://localhost:3000/ でタスクの一覧画面が表示されるようにしましょう
* Gemfile で [RuboCop](https://github.com/rubocop/rubocop)（Rubyの静的コード解析ツール） か [fablicop](https://github.com/Fablic/fablicop)をインストールしましょう。設定やコマンド実行方法は各READMEから確認しましょう。
* GitHub上でPRを作成してレビューしてもらいましょう
    * 今後、PRが大きくなりそうだったらPRを2回以上に分けることを検討しましょう

■対応内容
・タスク一覧画面、作成画面、詳細画面、編集画面、削除機能の実装
・実装していく中で下記の画面設計を変更したため、READMEに反映
　　- ボタン名
　　- 表示項目
　　- タスク作成画面URLが誤っていたため修正 　　
・日本語、日本時間に対応できるようapplication.rbに設定を追記し、/locales/en.ymlをja.ymlに変更して中身を追記
・gemfileにfablicopの設定を追加

■確認方法
1. 下記コマンドでDockerを起動 
　docker-compose up --build
2. 下記コマンドでDBを作成
　 docker-compose exec api rails db:create
3. 下記コマンドでテーブルを作成 
　docker-compose exec api rails db:migrate
4. 下記コマンドでデータを作成
　 docker-compose exec api rails c  
　 Task.create(name: 'Step6', detail: 'タスクモデルを作成しましょう', status: 1, priority: 1);
5. READMEに記載のタスク一覧画面URL（http://localhost:3001）を開き、各画面へ遷移

![タスク一覧画面](https://user-images.githubusercontent.com/110373388/183825897-6f85d986-8e5d-41c0-9f3b-f7a49479e7ff.png)
![タスク詳細画面](https://user-images.githubusercontent.com/110373388/183825941-37862382-0e80-49c5-86eb-b8927d29fc0f.png)
![タスク編集画面](https://user-images.githubusercontent.com/110373388/183825968-c80bf09c-1c60-4f81-ac56-1fff1d551760.png)
![タスク作成画面](https://user-images.githubusercontent.com/110373388/183826006-6a60efdc-ff48-4ca4-9a9b-e7782445e2fa.png)
![タスク削除ダイアログ](https://user-images.githubusercontent.com/110373388/183826030-30d9f054-dada-460f-a710-7c049cee71a9.png)

2022-08-17 05:49 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/README.md
> +| button | 2 | 新規登録 |  | ボタン | | タスク詳細画面へ遷移 |
詳細→新規登録に変更していますが、どちらの機能も画面に存在しています。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    end
おそらくgenerateコマンドで生成されたものだと思いますが、
```
format.json { render :show, status: :ok, location: @task }
```
こちらの記述は`jbuilder`というgemによって、`http://localhost:3001/tasks.json`等のURLにアクセスするとjsonを返すようにする処理となっています。
（現在はjbuilderファイルが生成されてないのでアクセスするとエラーが返ってきてしまう）

今回の研修では不要ですので、生成されないようにgemを消すか、処理を削除するようにお願いします。
他のアクションも対応お願いします。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +end
最終行は改行をいれるようにしてください。
使われているエディターがvscodeであれば、保存時に自動で改行をいれる設定もありますので試してみてください。（おそらく他のエディターでもあると思います。）

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.new()
引数をいれない場合のメソッドの後ろに、`()`は基本的に不要です。

```suggestion
    @task = Task.new
```

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  enum priority: { 低: 1, 中: 2, 高: 3 }
フォームの表示を日本語にするためにこの設定をいれたかと思いますが、
enumはキー名を使って新しくモデルにクラスメソッドを生成します。
今回の場合だと、`Task.低`のようなメソッドが生成されます。
rubyは日本語で変数名やメソッド名、クラス名を設定できますが、現場では使用していないため、ここでは英語で設定しましょう。

enum含めてビューの日本語化には次のステップで出てくるi18nで可能ですので、ここでは`low, middle, high`などの英語で設定しましょう。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_form.html.erb
> +    <%= f.select :status, Task.statuses.keys.map {|k| [k, k]} %>
ブロックの`{}`を使う際は内側に半角スペースをいれてください。
```suggestion
    <%= f.select :status, Task.statuses.keys.map { |k| [k, k] } %>
```

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_form.html.erb
> +    <%= f.select :priority, Task.priorities.keys.map {|k| [k, k]} %>
ブロックの`{}`を使う際は内側に半角スペースをいれてください。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_form.html.erb
> +<%end%>
最終行は改行をいれるようにしてください。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_task.html.erb
> +<div id='<%= dom_id task %>'>
こちらの部分テンプレート、他で利用しないのであれば`show.html.erb`に記載しても良いと思います。
使い回すから、という理由理以外にもビューを細かく分けることの利点はありますが、
それであればindex等もすべて同じ実装の方針に統一してほしいです。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/index.html.erb
> +<%= link_to '新規登録', new_task_path %>
最終行は改行をいれるようにしてください。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/index.html.erb
> +    <%end%>
`<% %>`の内側には半角スペースを入れましょう。
```suggestion
    <% end %>
```

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +
エディターで見ると、この行にスペースが残っています。
空行にはスペースを残さないようにお願いします。
他の箇所も同様に確認お願いします。

使われているエディターがvscodeであれば、保存時に自動で無駄なスペースを削除してくれる設定もありますので試してみてください。（おそらく他のエディターでもあると思います。）

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/config/application.rb
> +    # 言語を日本語に設定
このあたりの設定、ステップ9の内容に見えます。
今回の実装は戻さなくて良いので、今後はステップごとに指定された作業のみ実施していただくようお願いします。

2022-08-17 05:49 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +<%= link_to '一覧に戻る', tasks_path %>
最終行は改行をいれるようにしてください。

2022-08-17 08:23 UTC, nanae-kusakari commented on myapp/README.md
> +| button | 2 | 新規登録 |  | ボタン | | タスク詳細画面へ遷移 |
失礼しました。
詳細ボタンについて記載し、新規登録ボタンのレイヤーが誤っていたので修正しました。
https://github.com/Fablic/training/pull/1359/files#diff-3315def260651dc67c2478cabcc1c5d6ec96aecbd2d389ecf0206fe657430515:~:text=%7C%20button%20%7C%202%20%7C%20%E8%A9%B3%E7%B4%B0%20%7C%20%20%7C%20%E3%83%9C%E3%82%BF%E3%83%B3,%E4%BD%9C%E6%88%90%E7%94%BB%E9%9D%A2%E3%81%B8%E9%81%B7%E7%A7%BB%20%7C

2022-08-17 08:31 UTC, nanae-kusakari commented on myapp/app/controllers/tasks_controller.rb
> +    end
ご説明ありがとうございます。仕組みについて理解しました。
jbuilderファイルについては理解しきれていないので、合間を見てもう少し調査してみます。

全体的に、jsonで返却する処理は削除しました。

2022-08-17 08:33 UTC, nanae-kusakari commented on myapp/app/controllers/tasks_controller.rb
> +end
保存時に改行を入れる設定を追加し、全体的に最終行に改行が入るよう修正しました。

2022-08-17 08:38 UTC, nanae-kusakari commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.new()
()を削除しました。
`def new
    @task = Task.new
  end`

2022-08-17 08:43 UTC, nanae-kusakari commented on myapp/app/models/task.rb
> +  enum priority: { 低: 1, 中: 2, 高: 3 }
enumを英語に変更しました。
次のステップで日本語化すると思うので、READMEは修正していません。

メソッド生成の仕組みについても理解し、現場でも使用していないとのこと、承知しました。

2022-08-17 08:45 UTC, nanae-kusakari commented on myapp/app/views/tasks/index.html.erb
> +<%= link_to '新規登録', new_task_path %>
保存時に改行を入れる設定を追加し、全体的に最終行に改行が入るよう修正（保存）しました。

2022-08-17 08:47 UTC, nanae-kusakari commented on myapp/app/views/tasks/index.html.erb
> +    <%end%>
半角スペースを追加しました。

2022-08-17 08:47 UTC, nanae-kusakari commented on myapp/app/controllers/tasks_controller.rb
> +
空行のスペースを削除する設定をいれ、全体的に不要スペースを削除しました。

2022-08-17 08:48 UTC, nanae-kusakari commented on myapp/config/application.rb
> +    # 言語を日本語に設定
承知しました。以後気をつけます。

2022-08-17 08:48 UTC, nanae-kusakari commented on myapp/app/views/tasks/show.html.erb
> +<%= link_to '一覧に戻る', tasks_path %>
保存時に改行を入れる設定を追加し、全体的に最終行に改行が入るよう修正（保存）しました。

2022-08-17 08:55 UTC, nanae-kusakari commented
レビューありがとうございます。
指摘内容について対応いたしましたので、お手数ですが再度ご確認をお願いいたします。

2022-08-18 00:17 UTC, R-KazumaInazaki requested changes
再レビューしました。1点コメントしてますのでご対応お願いいたします。

2022-08-18 00:17 UTC, R-KazumaInazaki commented on .vscode/settings.json
> +}
個人の設定はPushしないようお願いします。
vscodeの設定の仕方が問題だと思いますが、作業ディレクトリに設定ファイルを置かないようにできたと思います。

2022-08-18 02:38 UTC, nanae-kusakari commented on .vscode/settings.json
> +}
設定ファイルをマージ対象から削除しました。
設定ファイルの置き場の設定がまだできていないので、後ほど設定します。

2022-08-18 04:34 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-08-18 04:51 UTC, merged