Yuma nakamura step7
Fablic/training pull request #1360
Opened 2022-08-10 06:04 UTC by connect-yuma-nakamura

■要件
### ステップ7: タスクを登録・更新・削除できるようにしよう

- タスクの一覧画面、作成画面、詳細画面、編集画面を作成しましょう
  - `rails generate` コマンドでコントローラとビューを作成します
  - コントローラとビューに必要な実装を追加しましょう
  - 作成、更新、削除後はそれぞれflashメッセージを画面に表示させましょう
- `routes.rb` を編集して、 `http://localhost:3000/` でタスクの一覧画面が表示されるようにしましょう
- `Gemfile` で [RuboCop](https://github.com/rubocop/rubocop)（Rubyの静的コード解析ツール） か [fablicop](https://github.com/Fablic/fablicop)をインストールしましょう。設定やコマンド実行方法は各READMEから確認しましょう。
- GitHub上でPRを作成してレビューしてもらいましょう
  - 今後、PRが大きくなりそうだったらPRを2回以上に分けることを検討しましょう
  
■対応内容
- 一覧画面、作成画面、詳細画面、編集画面追加
- rubocop導入
  
■確認方法
1. docker立ち上げ
    1. 以下コマンド実行
    　``` cd myapp ```
　　``` docker-compose up --build ```
1. タスク一覧画面確認
    1. ブラウザで以下にアクセス
    　``` http://localhost:3001 ```
    　→タスク一覧画面が表示されること
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183825108-6c2cb26e-a0d6-4b53-86b6-2c4771fd17fe.png">

2. タスク作成画面確認
    1. タスク一覧画面の作成ボタンを押下
    2. 各項目を入力
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183825436-9423de3e-cfee-4fe2-9bb1-9b5fe5faf1e4.png">

    3. 作成ボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183825487-a22ca640-c5c5-4477-8a00-017f66fb94b1.png">

3. タスク詳細画面確認
    1. タスク一覧画面の詳細ボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183826048-1bc4f893-aaa9-46a6-98d3-fc2f6d7ad911.png">

4. タスク編集画面確認
    1. タスク詳細画面の編集ボタンを押下
    2. 任意の項目を修正
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183826335-79abd85c-6e69-449e-8af1-dbfa53ecc72a.png">

    3. 更新ボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183826424-b020a995-4c74-4944-9556-fa24e219c852.png">

5. タスク削除機能確認
    1. タスク一覧画面の詳細ボタンを押下
    2. タスク詳細画面の削除ボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183826643-49afc498-1585-45c7-b2fd-fe8de23e55f6.png">

    3. OKボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183826718-0bd6a824-08e3-4639-9063-3b84fa0ea7f2.png">

  　

2022-08-17 08:12 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/README.md
> +| label | 2 | ラベル | tasks.label | 文字列 | | |
一覧画面以外の画面にも項目の追加や変更があると思いますので、そちらも更新お願いいたします。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +  def list
設計のURLに合わせて`list`、というアクションにされたのだと思いますが、
一覧画面のアクションはRailsのデフォルトである`index`にしてください。
Railsのデフォルトから逸れてしまうと、何をするアクションなのかぱっとみで分かりづらくなってしまい、
またRailsが用意しているメソッドも利用できなくなると言った、不便なこともあります。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      .joins(:user)
このPR全体に言えることですが、
ユーザーに関する実装は先のステップ16の内容です。
今回の実装は戻さなくて良いので、今後はステップごとに指定された作業のみ実施していただくようお願いします。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      )
ここはselectで項目を指定するのではなく、`all`で全項目取得するようにしましょう。
コントローラやビューの処理では`all`ですべて取得し、
ビューにカスタマイズ性を持たせる実装をよく見かけます。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    end
おそらくgenerateコマンドで生成されたものだと思いますが、
```
format.json { render :show, status: :ok, location: @task }
```
こちらの記述は`jbuilder`というgemによって、`http://localhost:3001/tasks.json`等のURLにアクセスするとjsonを返すようにする処理となっています。
（現在はjbuilderファイルが生成されてないのでアクセスするとエラーが返ってきてしまう）

今回の研修では不要ですので、生成されないようにgemを消すか、処理を削除するようにお願いします。
他のアクションも対応お願いします。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      .first
`where(id: params[:id]).first`は使わずに、`find`か`find_by`を利用してください。
また、一覧と同様でselectは使わないようにしましょう。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    end
このPR全体に言えることですが、ユーザーに関する実装は先のステップ16の内容です。
部分的に実装しているような状態となっており、ここでの指摘が難しいため、お手数ですが該当ステップでの実装をお願いいたします。
削除はしなくて良いので、コメントアウトしていただけると、該当ステップで差分にも出るので見やすいです。
他の箇所もご対応お願いします。

また、今後はステップごとに指定された作業のみ実施していただくようお願いします。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    end
ステータスに関する実装もユーザーと同様で、step13での内容です。
このタイミングでの指摘がしづらいので、該当ステップになりましたら実装お願いいたします。
削除はしなくて良いので、コメントアウトしていただけると、該当ステップで差分にも出るので見やすいです。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      )
この程度の長さであれば1行でも問題ありません。

また、改行する時は以下のようにメソッドチェインごとに改行すると見やすいです。
もしpermitの引数が長くなることを懸念している場合、引数部分を変数に格納することで対応するのが良いです。
```suggestion
    task = params.require(:task)
                 .permit(:title, :content, :label, :user_id, :status)
```

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +    <body>
すべてのビューに関して、html, head, bodyタグは`app/views/layouts/application.html.erb`側に記載されておりますので不要です。
デフォルトで、各ビューを読み込む前にapplication.html.erbを読み込みます。
そちらのファイル内に`<%= yield %>`と記載されている箇所で、各アクションに対応したビューが読み込まれる仕様となっております。

また、インデントに関してもhtmlファイルではないので、半角スペース2つで問題ありません。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +            <%= link_to("一覧へ", "/") %>
link_toを使う時、パスを文字列で指定するのではなく、`tasks_path`といったメソッドを可能な限り用いて実装してください。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +            <% end %>
formに関して、newとeditで同様となるはずです。（イメージと異なる可能性がありますが、ここでは合わせるようにお願いします）
ビューに同様の処理が出てくる場合、部分テンプレートを利用してください。
Railsでは`partial`といったものが用意されています。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/list.html.erb
> +                <%= link_to("作成", tasks_new_path()) %>
メソッドに引数がない場合の`()`は省略して問題ありません。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +            <p><%= @item[:title] %></p>
titleなどのattributeにはハッシュの形式で取得するのではなく、メソッドを用いて取得してください。
```suggestion
            <p><%= @item.title %></p>
```

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +            <%= link_to("編集", tasks_edit_path(@item)) %>
ここだけではありませんが、文字列の中に変数展開などが出てこない場合、`""`ではなく`''`を使ってください。
`''`を利用することで、この文字列の中に変数展開や`\n`などの特殊文字が出ないことを明確にできます。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/config/routes.rb
> +  get 'tasks/edit/:id', to:'tasks#edit', as:'tasks_edit'
`resources :tasks`と記載することで、これらの設定がすべて可能です。
もしresourceの仕様から外れるものがある場合でも、カスタマイズや上書きができますので利用してみてください。

2022-08-17 08:12 UTC, R-KazumaInazaki commented on myapp/config/rubocop/rubocop.yml
> +# 自動生成ファイル除外
rubocopですが、アプリケーション上に導入されてないようです。
`myapp/Gemfile`にrubocopかfablicopを記載し、bundle installで導入してください。
後出しにはなってしまいますが、現場でも利用しているfablicopをおすすめしています。
（fablicopはラクマが作成したもので、rubocopに色々な設定を加えたgemです）

2022-08-17 09:32 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      )
すみません、こちらのコメントについて、`all`はモデルから全件取得するためのメソッドであり、伝えたいことが間違っておりました。
正しくは以下のとおりです。

---

ビューで表示するものだけをselectで指定する実装は基本的にはしません。
今後表示させたい項目が増えた場合に、コントローラを修正する必要が出てきてしまい、
この1箇所であればまだ小規模ですが、これがアプリケーション全体となると大きな問題となります。
selectでの指定はせず、全項目を取得しましょう。

2022-08-18 04:52 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +      .joins(:user)
承知しました。ステップで指定があった作業のみ着手します

2022-08-18 06:46 UTC, connect-yuma-nakamura commented on myapp/README.md
> +| label | 2 | ラベル | tasks.label | 文字列 | | |
失礼いたしました。

2022-08-18 06:55 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +  def list
Railsのデフォルトに合わせるとのこと承知しました。
listからindexへ修正しました。

2022-08-18 06:55 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      .joins(:user)
承知しました。以後気をつけます。

2022-08-18 07:11 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      )
理由まで詳細にいただきありがとうございます。
メンテナンス性を意識した実装、気をつけます。
修正しました。

2022-08-18 07:22 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    end
自動生成ソースをベースに作成し、そのまま放置していました。
失礼いたしました。
GemFileからjbuilderを削除し、該当ソースを全て削除しました。

2022-08-18 07:26 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/list.html.erb
> +                <%= link_to("作成", tasks_new_path()) %>
メソッドと変数の違いがつきやすいかと思い、カッコをつけていました。
ラクマ案件としてはつけないことが多いのかと捉えましたので全て削除しました。

2022-08-18 07:35 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/show.html.erb
> +            <p><%= @item[:title] %></p>
メソッドを用いて取得するよう、全体的に修正しました。

2022-08-18 07:40 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/show.html.erb
> +            <%= link_to("編集", tasks_edit_path(@item)) %>
基本的にシングルクォーテーションを使用するよう全体的に修正しました。

2022-08-18 07:57 UTC, connect-yuma-nakamura commented on myapp/config/routes.rb
> +  get 'tasks/edit/:id', to:'tasks#edit', as:'tasks_edit'
```resources :tasks```を使用するように修正しました。

2022-08-18 08:34 UTC, connect-yuma-nakamura commented on myapp/config/rubocop/rubocop.yml
> +# 自動生成ファイル除外
fablicopを導入し、対応しました。

2022-08-18 10:48 UTC, R-KazumaInazaki requested changes
再レビューしました。
また、1回目のレビューの対応が一部されておりませんのでご確認ください。
（コメントが多くて申し訳ないのですが、ページの中央辺りに`7 hidden conversations`といったところで折りたたまれています）

2022-08-18 10:48 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    respond_to do |format|
`respond_to`メソッドですが、これはリクエストされるフォーマットによって処理を分けたい時に利用するメソッドです。
jsonの処理を削除し、htmlからのリクエストのみ受けるように修正したと思いますので、こちらも合わせて修正しましょう。

2022-08-18 10:48 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      if @task.save
1回目のレビューで見逃していましたが、
27行目のupdateと30行目のsaveは同じ役割で、詳細な処理は異なりますがどちらもDBへの更新処理を行っています。
どちらか片方で行うようにしてください。

2022-08-18 10:48 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +        format.html { redirect_to('/', notice: 'タスク作成成功') }
https://github.com/Fablic/training/pull/1360#discussion_r947569658
こちらの指摘と同様で、redirect_toでのパス指定も文字列ではなくメソッドを用いるようにしてください。

2022-08-18 10:48 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.joins(:user).all.where(id: params[:id]).first
https://github.com/Fablic/training/pull/1360#discussion_r947548480
こちらの指摘が対応できてないように見えます。
対応お願いいたします。

2022-08-18 10:48 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    task_params =
https://github.com/Fablic/training/pull/1360#discussion_r947558521
こちらの指摘対応ができてないように見えます。
対応お願いいたします。

2022-08-18 10:48 UTC, R-KazumaInazaki commented on myapp/config/routes.rb
> +  patch 'tasks/:id', to: 'tasks#update', as: 'update_task'
こちらの設定の場合、resourcesによるパスの生成と、4〜6行目の独自で書いたものによるパスの生成と2重に行われてしまいます。
resourcesによってcreate, update, deleteのパスは生成されているため、4〜6行目は不要かと思います。
また、3行目について、
このようなルートパスへの設定は`root`というメソッドが用意されているため、そちらを利用するようにしてください。

設定したルーティングは`rails routes`コマンドで確認できます。
```
                                tasks GET    /tasks(.:format)                                                                         tasks#index
                                      POST   /tasks(.:format)                                                                         tasks#create
                             new_task GET    /tasks/new(.:format)                                                                     tasks#new
                            edit_task GET    /tasks/:id/edit(.:format)                                                                tasks#edit
                                 task GET    /tasks/:id(.:format)                                                                     tasks#show
                                      PATCH  /tasks/:id(.:format)                                                                     tasks#update
                                      PUT    /tasks/:id(.:format)                                                                     tasks#update
                                      DELETE /tasks/:id(.:format)                                                                     tasks#destroy
                                      GET    /                                                                                        tasks#index
                          create_task POST   /tasks(.:format)                                                                         tasks#create
                          delete_task DELETE /tasks/:id(.:format)                                                                     tasks#delete
                          update_task PATCH  /tasks/:id(.:format)                                                                     tasks#update
```

2022-08-19 00:30 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      .first
すみません、対応漏れていました。
find_byを使用するよう修正しました。

2022-08-19 02:17 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    end
ユーザに関する対応箇所をコメントアウトしました。
今後は他対応は控えます。

2022-08-19 02:25 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    end
ステータスに関する対応箇所をコメントアウトしました。
ユーザと同様、今後は関係のない対応を控えます。

2022-08-19 02:28 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      )
確かに1行にしても長くないため、改行を削除しました。

2022-08-19 02:41 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/edit.html.erb
> +    <body>
なるほど！お教えいただきありがとうございます。
html、head、bodyタグを削除しました。
また、インデントもvscodeの設定変更、html修正しました。

2022-08-19 02:45 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/edit.html.erb
> +            <%= link_to("一覧へ", "/") %>
他``` '/' ```の使用箇所も全てroot_pathを使用するよう修正しました。

2022-08-19 03:35 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/edit.html.erb
> +            <% end %>
同様のイメージがもしかしたら合っていないかもしれないですが、部分テンプレートを用いて共通化しましたので再度ご確認をお願いします。

2022-08-19 03:36 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    respond_to do |format|
respond_toを削除しました。

2022-08-19 03:37 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      if @task.save
すみません、こちら削除しました。

2022-08-19 03:37 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +        format.html { redirect_to('/', notice: 'タスク作成成功') }
全体的にroot_pathを使用するよう修正しました。

2022-08-19 03:39 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    task_params =
そちらの指摘は対応漏れです。（閉じているコメントが全て漏れていました。失礼しました。）
2回目のレビュー指摘とともに対応しました。

2022-08-19 03:41 UTC, connect-yuma-nakamura commented on myapp/config/routes.rb
> +  patch 'tasks/:id', to: 'tasks#update', as: 'update_task'
```rails routes```で確認した上で自分の意図しているものがなかったため追加していました。
基本的にrailsで自動生成されるものに合わせて製造するよう、パスに関して見直し、修正しました。

2022-08-19 05:07 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      format.html { redirect_to(root_path, notice: 'タスク作成成功') }
respond_to削除時に`format`の削除も漏れていると思われます。
この状態だとエラーになると思いますのでご確認お願いいたします。

2022-08-19 05:26 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      format.html { redirect_to(root_path, notice: 'タスク作成成功') }
失礼しました、、。
docker内に過去の資産が残っていたようで、正常に動作したため気づきませんでした。
修正後、コンテナ、イメージ、ボリュームを削除して正常に動作することが確認できました。

2022-08-19 05:29 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-08-19 05:31 UTC, merged