Step7_一覧、詳細、登録、編集画面作成
Fablic/training pull request #1361
Opened 2022-08-10 08:00 UTC by kazuma-gushiken

下記を対応いたしましたので、お手数ですがご確認のほど、お願いいたします。

■要件
ステップ7: タスクを登録・更新・削除できるようにしよう
* タスクの一覧画面、作成画面、詳細画面、編集画面を作成しましょう
    * rails generate コマンドでコントローラとビューを作成します
    * コントローラとビューに必要な実装を追加しましょう
    * 作成、更新、削除後はそれぞれflashメッセージを画面に表示させましょう
* routes.rb を編集して、 http://localhost:3000/ でタスクの一覧画面が表示されるようにしましょう
* Gemfile で [RuboCop](https://github.com/rubocop/rubocop)（Rubyの静的コード解析ツール） か [fablicop](https://github.com/Fablic/fablicop)をインストールしましょう。設定やコマンド実行方法は各READMEから確認しましょう。
* GitHub上でPRを作成してレビューしてもらいましょう
    * 今後、PRが大きくなりそうだったらPRを2回以上に分けることを検討しましょう
   
■対応内容
・タスク一覧画面、作成画面、詳細画面、編集画面、削除機能の実装
・画面設計の変更をREADMEに反映
　　- ボタン名
　　- 表示項目
　　- タスク作成画面URLが誤っていたため修正 　　
・日本語対応
　　- application.rbに設定を追記
　　- /locales/en.ymlをja.ymlに変更して中身を追記
・gemfileにfablicopの設定を追加

■確認方法
・下記コマンドでDockerを起動 
　docker-compose up --build
・下記コマンドでDBを作成
　 docker-compose exec api rails db:create
・下記コマンドでテーブルを作成 
　docker-compose exec api rails db:migrate
・下記コマンドでデータを作成
　 docker-compose exec api rails c  
　 Task.create(name: 'Rails研修', description: 'RubyOnRailsの研修を行う');
・READMEに記載のタスク一覧画面URL（http://localhost:3001/ ）を開き、各画面へ遷移

■画面スクリーンショット
＜タスク一覧画面＞
<img width="648" alt="タスク一覧画面" src="https://user-images.githubusercontent.com/110374131/183847066-65005d00-2045-4bc3-b3cc-aaaf30cb84ef.png">

＜タスク作成画面＞
<img width="647" alt="タスク作成画面" src="https://user-images.githubusercontent.com/110374131/183847103-fcabb5b5-f270-4c05-8ed2-41f1a5fcaebc.png">

＜タスク詳細画
<img width="645" alt="タスク詳細画面" src="https://user-images.githubusercontent.com/110374131/183847146-cad2bb10-441b-4f7b-be33-96f07a8b0744.png">
面＞

＜タスク編集画面＞
<img width="649" alt="タスク編集画面" src="https://user-images.githubusercontent.com/110374131/183847174-f74b3f93-e64a-495d-a445-c503966b3190.png">

＜タスク削除ダイアログ＞
<img width="641" alt="タスク削除ダイアログ" src="https://user-images.githubusercontent.com/110374131/183847218-742ed0fe-6775-48ad-81f4-cbfea8dd97ba.png">

2022-08-17 08:16 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    end
おそらくgenerateコマンドで生成されたものだと思いますが、
```
format.json { render :show, status: :ok, location: @task }
```
こちらの記述は`jbuilder`というgemによって、`http://localhost:3001/tasks.json`等のURLにアクセスするとjsonを返すようにする処理となっています。
（現在はjbuilderファイルが生成されてないのでアクセスするとエラーが返ってきてしまう）

今回の研修では不要ですので、生成されないようにgemを消すか、処理を削除するようにお願いします。
他のアクションも対応お願いします。

2022-08-17 08:19 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_form.html.erb
> +  <%end%>
最終行は改行をいれるようにしてください。
使われているエディターがvscodeであれば、保存時に自動で改行をいれる設定もありますので試してみてください。（おそらく他のエディターでもあると思います。）

2022-08-17 08:24 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-08-17 08:24 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_form.html.erb
> +  <%end%>
最終行は改行をいれるようにしてください。
使われているエディターがvscodeであれば、保存時に自動で改行をいれる設定もありますので試してみてください。（おそらく他のエディターでもあると思います。）

2022-08-17 08:24 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    end
おそらくgenerateコマンドで生成されたものだと思いますが、
```
format.json { render :show, status: :ok, location: @task }
```
こちらの記述は`jbuilder`というgemによって、`http://localhost:3001/tasks.json`等のURLにアクセスするとjsonを返すようにする処理となっています。
（現在はjbuilderファイルが生成されてないのでアクセスするとエラーが返ってきてしまう）

今回の研修では不要ですので、生成されないようにgemを消すか、処理を削除するようにお願いします。
他のアクションも対応お願いします。

2022-08-17 08:24 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_task.html.erb
> +<div id='<%= dom_id task %>'>
こちらの部分テンプレート、他で利用しないのであれば`show.html.erb`に記載しても良いと思います。
使い回すから、という理由理以外にもビューを細かく分けることの利点はありますが、
それであればindex等もすべて同じ実装の方針に統一してほしいです。

2022-08-17 08:24 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/index.html.erb
> +    <%end%>
`<% %>`の内側には半角スペースを入れましょう。
```suggestion
    <% end %>
```

2022-08-17 08:24 UTC, R-KazumaInazaki commented on myapp/config/application.rb
> +
こちらの日本語化対応はステップ9で実施する内容となっています。
このタイミングだとレビューがしづらいので、該当ステップになりましたら実装お願いします。

2022-08-18 06:40 UTC, kazuma-gushiken commented on myapp/app/views/tasks/_form.html.erb
> +  <%end%>
最終行に改行を追加しました。
また、最終行に改行が入るようにVS Codeの設定を行いました。

2022-08-18 06:40 UTC, kazuma-gushiken commented on myapp/app/controllers/tasks_controller.rb
> +    end
内容について理解いたしました。
jsonの場合の処理を全体的に削除しました。

2022-08-18 06:41 UTC, kazuma-gushiken commented on myapp/app/views/tasks/_task.html.erb
> +<div id='<%= dom_id task %>'>
部分テンプレートを使用せず、show.html.erbに直接記載するよう修正いたしました。

2022-08-18 06:41 UTC, kazuma-gushiken commented on myapp/app/views/tasks/index.html.erb
> +    <%end%>
<% %>の内側前後に半角スペースを追加いたしました。

2022-08-18 06:42 UTC, kazuma-gushiken commented on myapp/config/application.rb
> +
承知しました。以後気をつけます。
application.rbの日本語設定の部分は削除しました。

2022-08-18 07:33 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-08-18 07:38 UTC, merged