ステップ7: タスクを登録・更新・削除できるようにしよう
Fablic/training pull request #1362
Opened 2022-08-10 09:14 UTC by kohei-matsubara

■要件
### ステップ7: タスクを登録・更新・削除できるようにしよう

- タスクの一覧画面、作成画面、詳細画面、編集画面を作成しましょう
  - `rails generate` コマンドでコントローラとビューを作成します
  - コントローラとビューに必要な実装を追加しましょう
  - 作成、更新、削除後はそれぞれflashメッセージを画面に表示させましょう
- `routes.rb` を編集して、 `http://localhost:3000/` でタスクの一覧画面が表示されるようにしましょう
- `Gemfile` で [RuboCop](https://github.com/rubocop/rubocop)（Rubyの静的コード解析ツール） か [fablicop](https://github.com/Fablic/fablicop)をインストールしましょう。設定やコマンド実行方法は各READMEから確認しましょう。
- GitHub上でPRを作成してレビューしてもらいましょう
  - 今後、PRが大きくなりそうだったらPRを2回以上に分けることを検討しましょう
  
■対応内容
- 一覧画面、作成画面、詳細画面、編集画面追加
- rubocop導入
  
■確認方法
1. docker立ち上げ
    1. 以下コマンド実行
    　``` cd myapp ```
　　``` docker-compose up --build ```
1. タスク一覧画面確認
    1. ブラウザで以下にアクセス
    　``` http://localhost:3001 ```
    　→タスク一覧画面が表示されること

    タスク一覧画面
<img width="1430" alt="スクリーンショット 2022-08-10 17 21 24" src="https://user-images.githubusercontent.com/110374166/183852468-ef765a63-da52-4200-ac4b-80454e08f188.png">

2. 新規登録画面確認
    1. タスク一覧画面の新規登録ボタンを押下
    2. 各項目を入力
<img width="1433" alt="スクリーンショット 2022-08-10 17 26 18" src="https://user-images.githubusercontent.com/110374166/183853306-9ba7fb72-50af-4b91-b15f-1bf930f745f1.png">

    3. 登録ボタンを押下
<img width="1434" alt="スクリーンショット 2022-08-10 17 28 21" src="https://user-images.githubusercontent.com/110374166/183853707-6359861d-6c26-41fb-bb64-5d28cb1e958c.png">

3. タスク詳細画面確認
    1. タスク一覧のタスクタイトルを押下
<img width="1432" alt="スクリーンショット 2022-08-10 17 30 33" src="https://user-images.githubusercontent.com/110374166/183854223-3674306a-a57c-462c-97d0-a3a8e6b8b2dc.png">

4. タスク編集画面確認
    1. タスク詳細画面または、タスク一覧画面の編集ボタンを押下
    2. 任意の項目を修正
<img width="1429" alt="スクリーンショット 2022-08-10 17 33 58" src="https://user-images.githubusercontent.com/110374166/183854967-b2db3d08-2a61-48d3-b5cd-26424c3fba26.png">

    3. 更新ボタンを押下
<img width="1429" alt="スクリーンショット 2022-08-10 17 35 04" src="https://user-images.githubusercontent.com/110374166/183855204-d0bb2606-dd30-4b36-9e62-704fdbc35526.png">

5. タスク削除画面確認
    1. タスク詳細画面または、タスク一覧画面の削除ボタンを押下
<img width="1426" alt="スクリーンショット 2022-08-10 17 38 30" src="https://user-images.githubusercontent.com/110374166/183855968-ae6f3078-ba46-4312-85a1-41294252d581.png">

    2. OKを押下
<img width="1429" alt="スクリーンショット 2022-08-10 17 39 47" src="https://user-images.githubusercontent.com/110374166/183856239-70aadd7a-57f5-4b28-b4bd-81515bbd7062.png">

2022-08-17 09:17 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/Gemfile
> +gem 'bootstrap'
bootstrapの導入はステップ15で用意されていますので、該当ステップになりましたら実装するようにお願いいたします。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/Gemfile
> +gem 'rubocop-rails', require: false
課題で提示されているgemと異なるものが記載されています。
また、`Gemfile.lock`に表示されていないため、記載後にbundle installしてないと思われますので、ご対応お願いします。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    end
おそらくgenerateコマンドで生成されたものだと思いますが、
```
format.json { render :show, status: :ok, location: @task }
```
こちらの記述は`jbuilder`というgemによって、`http://localhost:3001/tasks.json`等のURLにアクセスするとjsonを返すようにする処理となっています。
（現在はjbuilderファイルが生成されてないのでアクセスするとエラーが返ってきてしまう）

今回の研修では不要ですので、生成されないようにgemを消すか、処理を削除するようにお願いします。
他のアクションも対応お願いします。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +  <% end %>
formに関して、newとeditで同様となるはずです。（イメージと異なる可能性がありますが、ここでは合わせるようにお願いします）
ビューに同様の処理が出てくる場合、部分テンプレートを利用してください。
Railsでは`partial`といったものが用意されています。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/index.html.erb
> +  <a href="/tasks/new" class="btn btn-primary btn-block">新規登録</a>
リンクはaタグを利用するのではなく、link_toを用いてください。
また、パスはRails側が自動生成している`new_task_path`といったメソッドを利用してください。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +<%= link_to '一覧に戻る', tasks_path %>
ファイルの最後は改行をいれるようにしてください。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/config/ja.yml
> +title: タイトル
おそらく利用していないと思いますが、日本語化の対応は先のステップで行います。
該当ステップになりましたら実装していただけると幸いです。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220808071509_create_tasks.rb
> +      t.integer :user_id, limit: 8
DBを変更する場合、すでにmigrateを行ったファイルを編集せず、新しくDBを更新するmigrationを実装してください。
migrate済みのファイルを編集しても、このmigrationファイルをロールバックするまで反映されないといった不具合が起きます。

また、ユーザーに関しては先のステップで実装する予定となっております。
ここではフォームから入力を行わないためnilを回避するために変更したと思いますが、
今はコントローラ等で仮の値を入れるようにしておいてください。

2022-08-17 09:17 UTC, R-KazumaInazaki commented on myapp/db/schema.rb
> +# frozen_string_literal: true
`myapp/db`の配下はrubocopの対象外として問題ありません。
自動生成されるファイルなので、DBが更新されるたびに修正する必要が出てきます。
`myapp/app`配下など、手動で作成されたファイルのみ対象としてください。

2022-08-18 03:35 UTC, kohei-matsubara commented on myapp/Gemfile
> +gem 'bootstrap'
bootstrapの該当箇所を削除しました。

2022-08-18 05:19 UTC, kohei-matsubara commented on myapp/Gemfile
> +gem 'rubocop-rails', require: false
「gem 'rubocop-rails', require: false」を削除しました。
その後、rubocopがGemfile.lockに含まれていることを確認しました。

2022-08-18 05:29 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    end
gemfileのjbuilderを削除しました。
また、tasks_controller.rbのformat.json{}を削除しました。

2022-08-18 05:31 UTC, kohei-matsubara commented on myapp/app/views/tasks/edit.html.erb
> +  <% end %>
「ページタイトル」と、「登録ボタンまたは更新ボタン」以外は同じになるよう揃えました。

2022-08-18 05:32 UTC, kohei-matsubara commented on myapp/config/ja.yml
> +title: タイトル
現状使用していないため、ja.ymlを削除しました。

2022-08-18 05:45 UTC, kohei-matsubara commented on myapp/app/views/tasks/index.html.erb
> +  <a href="/tasks/new" class="btn btn-primary btn-block">新規登録</a>
link_toに修正しました。
また、パスはnew_task_pathに変更しました。

2022-08-18 07:22 UTC, kohei-matsubara commented on myapp/db/migrate/20220808071509_create_tasks.rb
> +      t.integer :user_id, limit: 8
直接、修正する前に戻しました。
また、user_idに仮の数値を入れる処理を追加しました。

2022-08-18 07:30 UTC, kohei-matsubara commented on myapp/app/views/tasks/show.html.erb
> +<%= link_to '一覧に戻る', tasks_path %>
最後の行に改行を入れました。

2022-08-18 07:38 UTC, kohei-matsubara commented on myapp/db/schema.rb
> +# frozen_string_literal: true
手動で生成されたファイルのみ対象にしました。

2022-08-18 09:57 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      if @task.save
1回目のレビューで見逃していましたが、updateとsaveは同じ役割となっており、これでは2回、DBに対して更新処理を流してしまいます。
`def create`も同様ですので確認お願いします。

2022-08-18 09:57 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +  <% end %>
こちら指摘の通りに修正がされていません。
フォーマットを揃えるだけでなく、部分テンプレートを利用してください。

2022-08-18 09:58 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    respond_to do |format|
`respond_to`メソッドですが、これはリクエストされるフォーマットによって処理を分けたい時に利用するメソッドです。
jsonの処理を削除し、htmlからのリクエストのみ受けるように修正したと思いますので、こちらも合わせて修正しましょう。

2022-08-18 10:00 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +      if @task.save
1回目のレビューで見逃していましたが、
21行目のcreateと25行目のsaveは同じ役割を持っており、どちらもDBへの更新処理を行います。
どちらか片方で行うようにしてください。
`def update`も同様です。

2022-08-18 10:04 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +      <div>
`<li>`の閉じタグがありません。
また`<li>`で囲まれているわけではないので、インデントが不自然です。

2022-08-18 10:07 UTC, R-KazumaInazaki commented on myapp/db/schema.rb
> +    t.bigint "user_id"
migrateにない変更があります。
指摘対応でmigrateを元に戻したと思うのでこちらも戻しましょう。

2022-08-19 00:28 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    respond_to do |format|
respond_toが不要だったため削除しました。

2022-08-19 02:40 UTC, kohei-matsubara commented on myapp/app/views/tasks/edit.html.erb
> +  <% end %>
部分テンプレートに修正しました

2022-08-19 03:19 UTC, kohei-matsubara commented on myapp/app/views/tasks/edit.html.erb
> +  <% end %>
部分テンプレートに修正しました。

2022-08-19 03:21 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +      if @task.save
片方で行うように修正しました。

2022-08-19 03:22 UTC, kohei-matsubara commented on myapp/app/views/tasks/show.html.erb
> +      <div>
閉じるタグを追加しました。

2022-08-19 03:22 UTC, kohei-matsubara commented on myapp/db/schema.rb
> +    t.bigint "user_id"
schema.rbを修正しました。

2022-08-19 03:32 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
新しくbefore_actionでインスタンス変数を定義するように実装されていますが、
こちらの行が同様の処理を行っており、重複しています。

2022-08-19 03:33 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
こちらもshow actionと同様です。

2022-08-19 03:33 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.new(task_params)
こちらもshow actionと同様の指摘です。

2022-08-19 03:33 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
こちらもshow actionと同様の指摘です。

2022-08-19 03:40 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
findが不要になったため削除しました

2022-08-19 03:40 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.new(task_params)
findが不要になったため削除しました

2022-08-19 03:40 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
findが不要になったため削除しました

2022-08-19 03:40 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
findが不要になったため削除しました

2022-08-19 04:35 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-08-19 04:41 UTC, merged