ステップ7: タスクを登録・更新・削除できるようにしよう
Fablic/training pull request #1363
Opened 2022-08-10 09:48 UTC by connect-yuma-nakamura

■要件
### ステップ7: タスクを登録・更新・削除できるようにしよう

- タスクの一覧画面、作成画面、詳細画面、編集画面を作成しましょう
  - `rails generate` コマンドでコントローラとビューを作成します
  - コントローラとビューに必要な実装を追加しましょう
  - 作成、更新、削除後はそれぞれflashメッセージを画面に表示させましょう
- `routes.rb` を編集して、 `http://localhost:3000/` でタスクの一覧画面が表示されるようにしましょう
- `Gemfile` で [RuboCop](https://github.com/rubocop/rubocop)（Rubyの静的コード解析ツール） か [fablicop](https://github.com/Fablic/fablicop)をインストールしましょう。設定やコマンド実行方法は各READMEから確認しましょう。
- GitHub上でPRを作成してレビューしてもらいましょう
  - 今後、PRが大きくなりそうだったらPRを2回以上に分けることを検討しましょう
  
■対応内容
- 一覧画面、作成画面、詳細画面、編集画面追加
  
■確認方法
1. docker立ち上げ
    1. 以下コマンド実行
    　``` cd myapp ```
　　``` docker-compose up --build ```
1. タスク一覧画面確認
    1. ブラウザで以下にアクセス
    　``` http://localhost:3001 ```
    　→タスク一覧画面が表示されること
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183869949-c71369aa-913a-4a1e-abb3-fe4ae93cc0fe.png">

2. タスク作成画面確認
    1. タスク一覧画面のCreate Taskボタンを押下
    2. 各項目を入力
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183870669-c5bece57-ba59-4ca9-9602-a199497e2174.png">

    3. Createボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183870453-c0c0e07d-69f9-44a2-a680-c96e0c0981c9.png">

3. タスク詳細画面確認
    1. タスク一覧画面のdetailsボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183870730-e24d69be-6cd9-4954-b1f8-f753cc4ed8db.png">

4. タスク編集画面確認
    1. タスク一覧画面のUpdateボタンを押下
    2. 任意の項目を修正
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183870974-676feb1a-e159-4739-b63a-4a87ccdf7eaa.png">

    3. Updateボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183871052-79d8bf28-bcab-4fbd-8cf9-ba814f4b4651.png">

5. タスク削除機能確認
    1. タスク一覧画面のDeleteボタンを押下
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183871182-c955453c-bad7-4469-8b21-e3919973a931.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/183871254-25959c3c-3cd4-48fb-b0c8-bae114976e1c.png">

2022-08-17 09:53 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/assets/stylesheets/scaffolds.scss
> +body {
デザインの適用について、先のステップで実装を予定しております。
該当のステップになりましたら実装していただくようお願いいたします。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +  def list
一覧画面のアクションはRailsのデフォルトである`index`にしてください。
Railsのデフォルトから逸れてしまうと、何をするアクションなのかぱっとみで分かりづらくなってしまい、
またRailsが用意しているメソッドも利用できなくなると言った、不便なこともあります。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @show_task =Task.joins(:user).select('tasks.title, tasks.description, tasks.label, users.name, tasks.status').where(id: params[:id]).first
ビューで表示するものだけをselectで指定する実装は基本的にはしません。
今後表示させたい項目が増えた場合に、コントローラを修正する必要が出てきてしまい、
この1箇所であればまだ小規模ですが、これがアプリケーション全体となると大きな問題となります。
selectでの指定はせず、全項目を取得しましょう。

また、`where(id: params[:id]).first`は使わずに、`find`か`find_by`を利用してください。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +  end
ユーザーに関する実装は先のステップで行いますので、該当ステップになりましたら実装するようにお願いします。
それまでは表示させないか、仮置でお願いします。

この箇所以外も対応お願いします。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +  end
ステータスについてもユーザーと同様です。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    end
おそらくgenerateコマンドで生成されたものだと思いますが、
```
format.json { render :show, status: :ok, location: @task }
```
こちらの記述は`jbuilder`というgemによって、`http://localhost:3001/tasks.json`等のURLにアクセスするとjsonを返すようにする処理となっています。
（現在はjbuilderファイルが生成されてないのでアクセスするとエラーが返ってきてしまう）

今回の研修では不要ですので、生成されないようにgemを消すか、処理を削除するようにお願いします。
他のアクションも対応お願いします。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +        format.html { redirect_to('/', notice: 'Create Task Success!!') }
redirect_toやlink_to等でパスを指定する時は、文字列ではなく
Rails側が自動生成している`new_task_path`といったメソッドを利用してください。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task.update_attributes(task_params[:task]) unless task_params[:task].blank?
この行はどのような想定の処理になりますでしょうか？
`update_attributes`メソッドはDBを更新するメソッドであり、26行目の`save`メソッドと細かい処理は異なりますが、役割はほとんど同じです。

また、unlessとblank?の掛け合わせは二重否定なので少々分かりづらいです。（空っぽでなければ、という意味）
判定用メソッド（blank?）に反対の意味のメソッド（present?）が用意されている場合、基本的にはifを利用しましょう。（存在していれば、という意味になり直感的にわかりやすい）
```suggestion
    @task.update_attributes(task_params[:task]) if task_params[:task].present?
```

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    puts @user_names
デバッグ用のコードでしょうか？

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +<%= form_with(model: @task, url: tasks_update_path()) do |f| %>
メソッドに引数がない場合の`()`は省略して問題ありません。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +<%= form_with(model: @task, url: tasks_update_path()) do |f| %>
formに関して、newとeditで同様となるはずです。（イメージと異なる可能性がありますが、ここでは合わせるようにお願いします）
ビューに同様の処理が出てくる場合、部分テンプレートを利用してください。
Railsでは`partial`といったものが用意されています。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +<%= link_to("Back", "/") %>
ファイルの最後は改行をいれるようにしてください。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/list.html.erb
> +    <thead>
ビューのインデントも半角スペース2つに統一してください。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/list.html.erb
> +                <td><%= link_to("Details", tasks_show_path(task), {class: "btn_a"}) %></td>
ここだけではありませんが、文字列の中に変数展開などが出てこない場合、`""`ではなく`''`を使ってください。
`''`を利用することで、この文字列の中に変数展開や`\n`などの特殊文字が出ないことを明確にできます。

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +<p><%= @show_task[:title] %></p>
titleなどのattributeにはハッシュの形式で取得するのではなく、メソッドを用いて取得してください。
```suggestion
<p><%= @show_task.title %></p>
```

2022-08-17 09:53 UTC, R-KazumaInazaki commented on myapp/config/routes.rb
> +  delete 'tasks/destroy/:id', to:'tasks#destroy', as:'tasks_destroy'
`resources :tasks`と記載することで、これらの設定がすべて可能です。
もしresourceの仕様から外れるものがある場合でも、カスタマイズや上書きができますので利用してみてください。

2022-08-19 01:41 UTC, miu-tsuzuki commented on myapp/app/assets/stylesheets/scaffolds.scss
> +body {
SCSSを削除しました。

2022-08-19 01:42 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +  def list
listをindexに修正しました。

2022-08-19 02:41 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +    @show_task =Task.joins(:user).select('tasks.title, tasks.description, tasks.label, users.name, tasks.status').where(id: params[:id]).first
Task.allに修正しました。

2022-08-19 02:42 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +  end
コメントアウトしました。

2022-08-19 02:42 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +  end
コメントアウトしました。

2022-08-19 02:42 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +    end
format.jsonは不要だったため削除しました。

2022-08-19 02:43 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +        format.html { redirect_to('/', notice: 'Create Task Success!!') }
自動生成のメソッドに修正しました。

2022-08-19 02:49 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +    @task.update_attributes(task_params[:task]) unless task_params[:task].blank?
不要だったため削除しました。

2022-08-19 02:49 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +    puts @user_names
不要だったため削除しました。

2022-08-19 02:49 UTC, miu-tsuzuki commented on myapp/app/views/tasks/edit.html.erb
> +<%= form_with(model: @task, url: tasks_update_path()) do |f| %>
不要だったため削除しました。

2022-08-19 02:50 UTC, miu-tsuzuki commented on myapp/app/views/tasks/edit.html.erb
> +<%= link_to("Back", "/") %>
改行を入れました。

2022-08-19 02:55 UTC, miu-tsuzuki commented on myapp/app/views/tasks/edit.html.erb
> +<%= form_with(model: @task, url: tasks_update_path()) do |f| %>
部分テンプレートを作成しました。

2022-08-19 02:56 UTC, miu-tsuzuki commented on myapp/app/views/tasks/list.html.erb
> +    <thead>
統一しました。

2022-08-19 02:56 UTC, miu-tsuzuki commented on myapp/app/views/tasks/list.html.erb
> +                <td><%= link_to("Details", tasks_show_path(task), {class: "btn_a"}) %></td>
修正しました。

2022-08-19 02:56 UTC, miu-tsuzuki commented on myapp/app/views/tasks/show.html.erb
> +<p><%= @show_task[:title] %></p>
メソッドを用いる方法に修正しました。

2022-08-19 02:57 UTC, miu-tsuzuki commented on myapp/config/routes.rb
> +  delete 'tasks/destroy/:id', to:'tasks#destroy', as:'tasks_destroy'
resources :tasksに修正しました。

2022-08-19 03:10 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @show_task =Task.joins(:user).select('tasks.title, tasks.description, tasks.label, users.name, tasks.status').where(id: params[:id]).first
実装内容とコメントに書かれた内容に乖離があります。実装された内容は正しいでしょうか？

2022-08-19 03:13 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    puts @user_names
実装内容とコメントに書かれた内容に乖離があります。実装された内容は正しいでしょうか？

2022-08-19 03:18 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/list.html.erb
> +    <thead>
インデントが統一されておりません。
すべてのファイルで統一するようお願いします。

2022-08-19 03:22 UTC, R-KazumaInazaki commented on myapp/app/helpers/task_helper.rb
> +  def status_view(code)
こちらのメソッドも一度コメントアウト等で消しておき、
後のステップで実装していただけるとレビューがしやすいです。

2022-08-19 04:53 UTC, miu-tsuzuki commented on myapp/app/helpers/task_helper.rb
> +  def status_view(code)
task_helperをコメントアウトしました。

2022-08-19 04:56 UTC, miu-tsuzuki commented on myapp/app/views/tasks/list.html.erb
> +    <thead>
list.html.erbは削除済みであるためインデント修正はしませんでした。
今回追加した_form.html.erbのインデントがずれていたため修正しました。

2022-08-19 04:58 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +    puts @user_names
コメントアウトになっていたので削除しました。

2022-08-19 05:07 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +    @show_task =Task.joins(:user).select('tasks.title, tasks.description, tasks.label, users.name, tasks.status').where(id: params[:id]).first
@task =Task.find(params[:id])の形に修正しました。コメントと乖離がありました。申し訳ありません。
    改めて、showに関わる部分を見直しました。

2022-08-19 05:15 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-08-19 05:55 UTC, merged