Nanae kusakari step8
Fablic/training pull request #1364
Opened 2022-08-17 01:35 UTC by nanae-kusakari

ドラフト版プルリク

2022-08-18 10:01 UTC, nanae-kusakari commented
下記を対応いたしましたので、お手数ですがご確認をお願いいたします。
■要件
ステップ8: テスト(system spec)を書こう
* First make sure that these gems are exist in Gemfile group :test do
*   gem 'capybara', '>= 2.15'
*   gem 'selenium-webdriver'
* end
*   Note: Remove the webdrivers gem from your Gemfile. If webdrivers is present, it will attempt to find Chrome in your application’s container. As Chrome isn’t installed in the Dockerfile, the spec will fail.
* Before start testing we need to register a new driver with Capybara that is configured to use the Selenium container, add the below codes to spec/rails_helper.rb Capybara.register_driver :remote_chrome do |app|
*   hub_url = 'https://chrome:4444/wd/hub'
*   chrome_capabilities = ::Selenium::WebDriver::Remote::Capabilities.chrome(
*     'goog:chromeOptions' => {
*       'args' => %w[no-sandbox headless disable-gpu window-size=1680,1050],
*     },
*   )
*   Capybara::Selenium::Driver.new(app, browser: :remote, url: hub_url, desired_capabilities: chrome_capabilities)
* end
* 
* config.before(:each, type: :system) do
*   driven_by :rack_test
* end
* 
* config.before(:each, type: :system, js: true) do
*   driven_by :remote_chrome
*   Capybara.server_host = IPSocket.getaddress(Socket.gethostname)
*   Capybara.server_port = 3000
*   Capybara.app_host = "https://#{Capybara.server_host}:#{Capybara.server_port}"
* end
*  
* specを書くための準備をしましょう
    * spec/spec_helper.rb 、 spec/rails_helper.rb を用意しましょう
* feature spec system specをタスク機能に対して書きましょう
    * Rails 5.1 以降、新たにsystem testの機能を追加しました
        * [日本語](https://qiita.com/jnchito/items/c7e6e7abf83598a6516d), [英語](https://rossta.net/blog/why-rails-system-tests-matter.html)
    * dockerを利用して研修を行う場合、以下の設定が必要です。
        * [Dockerfile](https://qiita.com/ngron/items/f61b8635b4d67f666d75#failed-to-read-the-sessionstorage-property-from-window-storage-is-disabled-inside-data-urls)
        * [spec/rails_helper.rb](https://commis.hatenablog.com/entry/2018/11/16/171608)
    * feature specですと database_cleaner という gemは必要でしたが、 system specに変更することで database_cleaner の導入が要らなくなった
* Circle CIなどのCIツールを導入して、Slackに通知するようにしましょう
    * Fablic/training内でPRのやり取りをする場合、CIツールの導入は任意(optional)です。CircleCIのAdmin権限が無いので、.circleci/config.ymlを設定しても実行できないです。
* 参考書籍：https://leanpub.com/everydayrailsrspec-jp

■対応内容
・設定
　- GemfileにFactoryBot, RSpec, ドライバの設定を追記
・SystemSpecの記載
・READMEの修正
　- ボタン名の表記揺れ解消
　- タスク一覧画面でボタンを重複して記載してしまっていたので、片方削除
・テストできるよう、HTMLでFlashメッセージのクラス名を指定
・ja.ymlの使用していない設定を削除

■確認方法
下記コマンドでテストを実行 docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb

■画面キャプチャ
＜タスク詳細画面＞ 
ボタンの表示を「一覧に戻る」→「一覧へ戻る」に変更しました。
![タスク詳細画面](https://user-images.githubusercontent.com/110373388/185368641-ed6e155a-c8f9-4e8c-af72-a522a437a0f4.png)

2022-08-21 23:47 UTC, R-KazumaInazaki requested changes
レビューしました。
コメントつけておりますが、指摘箇所だけでなく、指摘内容をもとに全体の見直しをお願いします。

2022-08-21 23:47 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +  end
これらは一覧画面用のものだと思いますが、
`describe 'タスク管理機能'`直下の階層に書いた場合、
その階層内にある全てのテスト（`describe '一覧表示機能'`,`describe '詳細表示機能'`など）で必要なように見えます。（実際、`describe '一覧表示機能'`以外でも呼び出すことができてしまいます。）

`describe '一覧表示機能'`でのみ利用するものであれば、その直下に記載しましょう。

2022-08-21 23:47 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      end
`before`は主に、テスト実施の事前準備をおこなうために利用します。（例えば画面にアクセスするためのログインをしておく、必要なデータを用意する等）
今回の場合`visit tasks_path`は事前準備ではなく、期待値を得るための直接的な手順だと思いますので、
`it`の中に記載するようにしてください。
すると`it`だけを見た時、
```
一覧画面を表示した⇒結果、一覧に期待したタスクが表示された
```
といったまとまりができ、読みやすいspecとなります。

2022-08-21 23:47 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +  let!(:task_b) { FactoryBot.create(:task, name: '２つ目のタスク', detail: '２つ目のタスクを実施する', status: 1, priority: 2) }
`let`と`let!`の使い分けはできておりますでしょうか？
例えば`describe '一覧表示機能'`で`task_a`を利用しますが、これはテスト実行直前から作っておく必要がなく、
遅延評価（初めて`task_a`という変数が呼ばれた時）で作成するでも問題なく動作するはずです。
テストに必要なデータだけを用意することで正確なテストができる、というのが主な観点です。
（規模が大きくなった際にRSpec全体のパフォーマンスにも影響してきます）

また、この位置でこれらのテストデータを定義すると、`describe 'タスク管理機能'`の配下のすべてのテストで利用されるデータのように見えます。
しかし、例えば27行目で`context 'タスクが1件存在する場合'`と書かれていますが、実際には２つデータが作成されており、条件と異なるテストとなってしまいます。
`context 'タスクが1件存在する場合'`の直下で5行目のデータ作成を、`context 'タスクが2件(複数)存在する場合'`の直下で5行目と6行目のデータ作成を行うことで、`context`とデータ作成がペアとなって正しいテストとなり、また可読性が上がります。
この時、5行目の内容が２つのcontextに書かれてしまい、DRYな実装ではなくなると思います。
ですが、RSpecではDRYな実装より読みやすいコードとなることを意識するようにしてください。

2022-08-21 23:47 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      select(value = priority, from: 'task[priority]')
こちらの内容も`let!`の指摘と同様で、`describe '新規登録機能'`の配下のすべてのテストで利用するように見えます。
入力値を`let`で持ってくることでDRYではあるのですが、仮に`特定の項目を入力しない場合`といった条件を作ることになった時、このbeforeが使えなくなる可能性もありますし、
フォームに入力項目が増えた時、`describe '新規登録機能'`の配下のすべてのテストに`let`を増やす必要が出てきて、保守性が低いです。

`context 'タスクの内容を入力した場合'`の直下に記載するようにしましょう。

2022-08-21 23:47 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        expect(task.priority).to eq(priority)
`have_attributes`というmatcherを使うことでこれらをまとめることが可能です。
が、`find_by`を`name`を用いて取得した時点で、81行目のテストをする必要がないように見えます。
この場合、全ての値で検索をかけ、レコードが取得できるか？というテストを書くと、キレイにまとめることができると思います。
`exist`というmatcherがあるので使ってみてください。

2022-08-21 23:47 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +    }
1つの`it`には1つの`expect`を書くようにしましょう。
まだ3つ程度であれば大きな問題にはなりませんが、このケースが失敗した時、どの`expect`で失敗したのか？がわかりづらくなるためです。
細分化することで、どのケースで失敗したのかが一目瞭然となります。

2022-08-21 23:47 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        expect(page).to have_selector '.alert-success', text: "タスク「#{task.name}」を登録しました。"
`task.name`を使うのではなく、入力時に入力した値、つまり`let`の`name`を利用するようにしましょう。
rails側が用意しているメソッドではありますが、このテストが失敗した時、`click_button '登録'`に問題があるのか？`find_by`メソッドに問題があるのか？`name`に問題があるのか？の特定が難しく、何をテストしたいのかがわかりづらいです。

2022-08-21 23:47 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      it '画面表示時に編集前のタスク内容が各項目に表示されている' do
`it '画面表示時`と、`it`に条件を記載してしまっています。
`describe`には概要を`context`には条件を`it`には期待値を、という使い分けをきっちりと行い、細分化しましょう。
また、98行目の`context`とも異なる条件であるため、階層が異なると思います。
`describe '編集機能'`の条件として、画面を表示した時と入力する時という２つの条件は並列になると思うので、
`context`を追加し、階層を変えてください。

2022-08-22 01:22 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +  describe 'ページ遷移' do
`describe 'ページ遷移'`を独立した機能としてテストしていますが、`一覧、登録、詳細、編集`画面に内包された機能であり、それらと横並びになる機能ではないと思います。
`describe`の分け方ですが、
まずは画面単位で`describe`を切り、そのネスト内で表示機能、画面遷移機能などの機能単位で`describe`を記載すると、見やすいテストになるかと思います。

2022-08-23 03:32 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +  end
一覧表示機能のみで使用する処理のため、一覧表示機能直下に移動しました。
また、全体的に使用する機能の配下に記載するよう修正しました。

2022-08-23 03:34 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +      end
beforeとitに記載する処理の線引きについて、理解しました。
「visit tasks_path」はit内に記載するよう修正しました。（全体的に修正しました）

2022-08-23 03:43 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +    }
1つのitに1つのexpectを記載するよう全体的に修正しました。

2022-08-23 04:59 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +  describe 'ページ遷移' do
ページ遷移については各画面に内包し、機能単位でdescribeを記載するよう修正しました。

2022-08-23 05:00 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +        expect(page).to have_selector '.alert-success', text: "タスク「#{task.name}」を登録しました。"
Flashメッセージに関して、入力時のnameを利用するよう全体的に修正しました。

2022-08-23 05:01 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +      select(value = priority, from: 'task[priority]')
「特定の項目を入力しない場合」が増えることを考慮できていなかったです。
タスク内容を入力した場合の直下に記載するよう修正しました。
タスクの入力についてはit内に記載しました。

2022-08-23 05:05 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +      it '画面表示時に編集前のタスク内容が各項目に表示されている' do
describe, context, itの記載内容を全体的に見直しました。
編集機能の階層も修正しました。

2022-08-23 05:40 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +  let!(:task_b) { FactoryBot.create(:task, name: '２つ目のタスク', detail: '２つ目のタスクを実施する', status: 1, priority: 2) }
letとlet!の使い分けについて再確認し、全体的に修正しました。

また、task_aをletで定義するよう変更し、一覧表示機能でタスクを作成できていなかった（task_aが呼ばれていなかった）ため、context直下で「let!(:task_1) { task_a }」を記載するよう変更したのですが、修正方針として正しいかご確認いただきたいです。

2022-08-23 05:51 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +        expect(task.priority).to eq(priority)
existがエラーで使用できなかったので、全ての値を条件として取得し、not_to be_nilで判定するよう修正しました。

2022-08-23 23:45 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_1) { task_a }
`let!`で事前に定義したものを呼び出すのではなく、この位置でbeforeを用いてcreateするようにしてください。
`task_1`という使われない変数を定義してしまっています。

テストデータの定義に関して、何度も記載するのは冗長のように見えますが、
例えば一覧画面のように「タスクが1件ある場合」「2件ある場合」のような条件であればそのcontextの直下で、
詳細画面や編集画面のようにテストデータがある前提のケースであれば、describeの直下で定義してあげると、読みやすいコードになると思います。

2022-08-23 23:45 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +  let!(:task_b) { FactoryBot.create(:task, name: '２つ目のタスク', detail: '２つ目のタスクを実施する', status: 1, priority: 2) }
こちらに記載しました。
https://github.com/Fablic/training/pull/1364/files#r953194146

2022-08-24 00:40 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        subject(:tds){ all('tbody tr')[0].all('td') }
このtdsはsubjectではなくletで定義してください。
subjectは１つのケースに１つだけ定義するようにしましょう。

また、詳細や登録機能のテストを見ると、それらのdescribeの直下でvisistのsubjectを定義しています。
一覧表示に関しても11行目と29行目で分けるのではなく、7行目の直下で定義すると見やすくなりそうです。

2022-08-24 00:51 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +          expect(Task.find_by(name: task_a.name)).to be_nil
ここだけexpectが2つ記載されています。
itに`正常に`という言葉がありますが、specにおいてあいまいな言葉を使ってしまうと、観点が分かりづらくなってしまいます。
１つのレコードだけ削除されること、対象のレコードがなくなっていること、と２つの観点にわけることができると思います。

2022-08-24 05:07 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +          expect(Task.find_by(name: task_a.name)).to be_nil
登録と削除のitにexpectを2つ記載していたので、分けるよう修正しました。
また、「正常に」という言葉を修正（削除）しました。

2022-08-24 05:14 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +        subject(:tds){ all('tbody tr')[0].all('td') }
1ケースに1subjectとなるよう修正しました。

一覧表示機能のsubject記載位置を一覧表示機能のdescribe直下に移動しました。

2022-08-24 05:33 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_1) { task_a }
ケースごとにデータを作成するよう修正しました。
ケースごとにデータを作成するメリット（読みやすさ）についても理解しました。

2022-08-24 05:34 UTC, nanae-kusakari commented on myapp/spec/system/tasks_spec.rb
> +  let!(:task_b) { FactoryBot.create(:task, name: '２つ目のタスク', detail: '２つ目のタスクを実施する', status: 1, priority: 2) }
ありがとうございます。確認いたしました。

2022-08-24 06:24 UTC, R-KazumaInazaki approved these changes
LGTM！

2022-08-24 07:24 UTC, merged