ステップ8: テスト(system spec)を書こう
Fablic/training pull request #1367
Opened 2022-08-19 06:38 UTC by connect-yuma-nakamura

■要件

### ステップ8: テスト(system spec)を書こう
- First make sure that these gems are exist in Gemfile
  ```
  group :test do
    gem 'capybara', '>= 2.15'
    gem 'selenium-webdriver'
  end
  ```
  **Note**: Remove the `webdrivers` gem from your Gemfile. If `webdrivers` is present, it will attempt to  find Chrome in your application’s container. 
  As Chrome isn’t installed  in the Dockerfile, the spec will fail.
  
- Before start testing we need to register a new driver with Capybara that is configured to use the Selenium container, add the below codes to 
  `spec/rails_helper.rb`
  ```
  Capybara.register_driver :remote_chrome do |app|
    hub_url = 'https://chrome:4444/wd/hub'
    chrome_capabilities = ::Selenium::WebDriver::Remote::Capabilities.chrome(
      'goog:chromeOptions' => {
        'args' => %w[no-sandbox headless disable-gpu window-size=1680,1050],
      },
    )
    Capybara::Selenium::Driver.new(app, browser: :remote, url: hub_url, desired_capabilities: chrome_capabilities)
  end

  config.before(:each, type: :system) do
    driven_by :rack_test
  end

  config.before(:each, type: :system, js: true) do
    driven_by :remote_chrome
    Capybara.server_host = IPSocket.getaddress(Socket.gethostname)
    Capybara.server_port = 3000
    Capybara.app_host = "https://#{Capybara.server_host}:#{Capybara.server_port}"
  end
  ```
- specを書くための準備をしましょう
  - `spec/spec_helper.rb` 、 `spec/rails_helper.rb` を用意しましょう
- ~~feature spec~~ system specをタスク機能に対して書きましょう
  - Rails 5.1 以降、新たにsystem testの機能を追加しました
    - [日本語](https://qiita.com/jnchito/items/c7e6e7abf83598a6516d), [英語](https://rossta.net/blog/why-rails-system-tests-matter.html)
  - dockerを利用して研修を行う場合、以下の設定が必要です。
    1. [Dockerfile](https://qiita.com/ngron/items/f61b8635b4d67f666d75#failed-to-read-the-sessionstorage-property-from-window-storage-is-disabled-inside-data-urls)
    2. [spec/rails_helper.rb](https://commis.hatenablog.com/entry/2018/11/16/171608)
  - feature specですと `database_cleaner` という gemは必要でしたが、 system specに変更することで `database_cleaner` の導入が要らなくなった
- Circle CIなどのCIツールを導入して、Slackに通知するようにしましょう
  - Fablic/training内でPRのやり取りをする場合、CIツールの導入は任意(optional)です。CircleCIのAdmin権限が無いので、`.circleci/config.yml`を設定しても実行できないです。
- 参考書籍：https://leanpub.com/everydayrailsrspec-jp

■確認方法
1. 下記コマンド実行
    ```shell docker-compose up --build```
    ```shell cd myapp ```
    ```shell docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb ```

2022-08-22 04:20 UTC, R-KazumaInazaki requested changes
レビューしました。

コメントにも記載しましたが、specはなるべくDRYに書かず、可読性を重視した実装になるようにしてください。
また、記載した指摘はその箇所だけでなく、他の箇所も横展開で確認してください。

system specはE2Eのテストなので、ユーザーの操作によって期待される「動作、表示」がされること、という観点がわかるような実装をしてみてください。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = Task.all.order('tasks.created_at desc')
もしステップに関係ない差分が出た場合、それが正しいのであればコメントで補足していただけると嬉しいです。
このステップではコントローラやモデルに差分は出ない想定でレビューしています。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/app/models/user.rb
> +  has_many :tasks, dependent: :destroy
こちらの差分も、今回のsystem spec対応では出ない差分だと思います。
コミット履歴からrubocopの対応だと思われますが、rubocop対応に関しては各ステップで実装した箇所のみでお願いいします。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +  describe '#index', type: :system do
`type: :system`は一番上の`describe 'Tasks'`に記載されているので不要となります。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +
現時点でuserとの紐付けは不要なはずです。
先のステップでユーザーに関する実装を行った時、追加してください。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        Task.create!(
テストデータを作成する時、`factory_bot_rails`というgemを使うとより効率的にテストができます。
現場でも利用していますので導入してみてください。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      let!(:tasks_number) { 0 }
`let`と`let!`の使い分けはできておりますでしょうか？
ここは`let`でも問題なく動作するはずです。
可能な限り`let`、遅延評価を利用してください。そうすることでテストに必要なデータのみを用意でき、問題があった時も気づきやすいです。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      let!(:tasks_number) { 0 }
beforeで`tasks_number`の数だけテストデータを作成するようにしていますが、specでは可能な限りDRYに書かないようにしてください。
例えばこのケースの場合、`tasks_number`がどこでどのように使われているのか頭に入れた上でコードを読むか、もしくは上にさかのぼる必要が出てきます。
しかし、`context`の直下で条件通りのテストデータ作成や動作を行っていれば、それをする必要がなく、読みやすいコードとなります。
specではあえて効率的に書かず、上から下に読んだ時の読みやすさを重視するようにしてください。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +          # expect(columns[4]).to(have_link('詳細', href: task_path(@db_items[i])))
DBから取得したデータと比較を行っていますが、DBから取得する処理をspec上に書いてしまっています。
主な問題点ですが、取得処理はコントローラが行っている役割であり、これではコントローラのテストができていません。
また、spec上に複雑な処理を書くことで、エラーが起きた時に本来テストすべきコントローラやビューに問題があるのか？それとも自身がspecに実装した内容に問題があるのか？わかりづらくなります。

spec上でどのような値を持つタスクをいくつ作成するか？を記載しているはずなので、そこで指定している値と比較するようにしてください。
そうすることで、ループ処理やDBからの取得処理も不要となるはずです。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      @view_items = all('div[name="list-task"] tbody tr')
spec内でインスタンス変数は使わずに、必ずletかlet!を利用しましょう。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      visit(root_path)
テストの期待値に関わる操作手順はbeforeではなくitの中に記載するようにしてください。
itだけを見た時に、何をしたことで期待値を得られたか？が明確になります。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        expect(@view_items.size).to(eq(@db_items.size))
1つのitには1つのexpectを記載するようにしましょう。
その上で、各itに何を期待しているのか記載してください。
エラーが起きた時、何が原因かがわかりやすくなります。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      # find("option[value='#{@user.id}']").select_option
一覧画面の指摘と同様で、テストの期待値に直接かかわる処理は、itの中に記載してください。
テストが明確になるだけでなく、仮に登録画面にフォーム入力以外の機能が増え、fill_inが不要なテストが出てきた時、この処理から修正する必要もありません。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      expect { click_button '作成' }.to change(Task, :count).by(1)
expectはbeforeに記載せず、itの中に記載してください。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        expect(@task.title).to eq(new_task[:title])
このテストだと、正しい値が入っていなかった場合、`title`メソッドに問題があるのか？`@task`に問題があるのか？`@task`をつくるための`find_by`に問題があるのか？といったように問題点がわかりづらいです。
ここでは登録ボタンを押した時、DB上にデータが作成されていることを確認できれば良いので、
入力した値すべてを利用して検索をかけ、データが存在するか？というテストをすると、これらの問題点が解決されると思います。
`exist`というmatcherがあるので使ってみてください。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +  describe '#new', type: :system do
テストの内容が、入力した値ごとに正しいレコードができているか？という観点しかありませんが、
入力したあとにどの画面に遷移するか？どのようなメッセージが表示されるか？もテストしてください。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        @task = Task.create!(
この実装の仕方だと、`@task`には最後に作成したレコードしか入っておらず、複数件を作っている意図が見えません。
また、詳細画面において複数件のタスクをつくることが、どのような観点を意図しているのか？がわからないです。

2022-08-22 04:20 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      if defined? update_task
他のコメントにも記載していることと同じ観点にはなるのですが、
1つのbeforeに処理をまとめて使いまわそうとしていることで、逆に分かりづらいコードとなっています。
この`defined?`を見て、update_taskを定義しないパターンのテストがあることを想像することはかなり難易度が高いです。
if分岐のような処理を必要としないよう、beforeを細分化してください。

2022-08-22 05:57 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = Task.all.order('tasks.created_at desc')
承知しました。
ReadMeに記載した設計を元にテストを実施し、テストにより修正したという内容です。
今後はコメントにて記載します。

2022-08-22 05:57 UTC, connect-yuma-nakamura commented on myapp/app/models/user.rb
> +  has_many :tasks, dependent: :destroy
承知しました。

2022-08-22 06:01 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +  describe '#index', type: :system do
不要の旨承知しました。
削除しました。

2022-08-22 06:13 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +
Modelへ紐付けの定義が残っていたため、Modelの紐づき定義とともにUser作成処理をコメントアウトしました。

2022-08-22 07:04 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        Task.create!(
FactoryBotを使用するよう修正しました。

2022-08-22 07:16 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      expect { click_button '作成' }.to change(Task, :count).by(1)
expectがbeforeに記載されている箇所をitに移しました。

2022-08-22 07:24 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      let!(:tasks_number) { 0 }
let!出ないとbefore前に定義されない、と勘違いしていました。
再度調べ直し、letの場合は呼び出し時に生成されるため問題ないことを理解しました。

2022-08-22 08:23 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      let!(:tasks_number) { 0 }
> specではあえて効率的に書かず、上から下に読んだ時の読みやすさを重視するようにしてください。

こちら承知しました。DRYではなく、各テスト毎に独立するよう修正しました。

2022-08-23 06:37 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        expect(@task.title).to eq(new_task[:title])
find_byの取得可否によって結果を評価するよう修正しました。
また、existではnilが判定できなかったため、not_to be_nil で評価するようにしました。

2022-08-23 07:36 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +  describe '#new', type: :system do
画面遷移、またメッセージについてもテスト追加しました。

2022-08-23 07:37 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        @task = Task.create!(
全体的なテスト見直しにより、複数件ケースは削除しました。

2022-08-23 07:38 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      if defined? update_task
DRYにならない作りに変更する際、共通処理、beforeを削除したためこちらも修正されました。

2022-08-23 07:39 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          # expect(columns[4]).to(have_link('詳細', href: task_path(@db_items[i])))
全体的に見直し、シンプルなソースへ修正しましたのでこちらも修正されました。

2022-08-23 07:39 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      @view_items = all('div[name="list-task"] tbody tr')
letに変更しました。

2022-08-23 07:40 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      visit(root_path)
DRYでないソースにしたため、こちらも修正されました。

2022-08-23 07:40 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        expect(@view_items.size).to(eq(@db_items.size))
1つのitに対し、1つのexpectにするよう修正しました。

2022-08-23 07:41 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      # find("option[value='#{@user.id}']").select_option
it同士が依存し合わないよう修正しました。

2022-08-24 02:28 UTC, R-KazumaInazaki requested changes
RSpecらしいコードになってきましたが、いくつか指摘をしています。
指摘箇所だけでなく、全体的に見直しをお願いします。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/factories/task.rb
> +  factory :task_not_started, class: Task do
ステータスの初期値は削除したと思うので、`_not_started`も削除しましょう。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +  describe '1 #index' do
ナンバリングは不要です。
specでは最後尾にテストを追加する以外に、途中に追加されることもありえますので、ナンバリングをしてしまうとテストと関係のないところの修正が増えてしまいます。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      let!(:task_index_1) { task_one }
`let!`で事前に定義したものを呼び出すのではなく、この位置でbeforeやlet!を用いてcreateするようにしてください。

テストデータの定義に関して、何度も記載するのは冗長だと思いますが、
例えば一覧画面のように「タスクが1件ある場合」「2件ある場合」のような条件であればそのcontextの直下で、
詳細画面や編集画面のようにテストデータがある前提のケースであれば、describeの直下で定義してあげると
「このテストではこのようなデータを用意している」というのが明確になり、読みやすいコードになると思います。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      end
これらのテスト、１つ目と２つ目のタスクで値が同じため、仮に２つ目のタスクが表示されていなかったとしてもテストが通ってしまいます。
テストデータを作成する時に、それぞれ異なる値となるように作成してください。

factoryを利用する場合のテストデータですが、あくまでfactory側に記載した値は初期値です。
「とりあえずtaskのテストデータがほしいけど値はなんでもいい」といった場合のみ、その初期値を利用するようにし、今回のように値が必要となるテストでは、それらのテストごとに値を指定しましょう、

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        expect(Task.find_by(title: new_task[:title], content: new_task[:content], label: new_task[:label])).not_to be_nil
せっかくnet_taskをハッシュで定義しているので、以下のように記載すると良いでしょう。
また、nilではないこと、だと二重否定なので、存在すること、とした方が直感的にわかりやすいです。
```suggestion
        expect(Task.find_by(new_task)).to be_present
```

あと編集してわかったのですが、この行の最後に半角スペースが残っています。
vscodeの設定で、保存時に行の最後にある無駄なスペースをトリムできるので、設定してみてください。
ただし、設定ファイルはpushしないようお願いします。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      let(:new_task) {
細かい話ですが、new_taskという変数名だと`Task.new`で作成したオブジェクトのように見えます。
フォームに入力する値だと思うので`input_values`ではどうでしょうか。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      it '2-1-1 登録内容が想定通りであること' do
itを記載するとき、想定どおり、正常、異常など曖昧な言葉を使うのではなく、観点をしっかりと記載してください。
例えばここであれば「入力した値でTaskが作成されていること」が111行目のexpectを言語化したようでわかりやすいでしょう。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +    context '2-5 画面遷移' do
contextは条件を書くためのものです。
`2-5 画面遷移`はテストの概要だと思うので、describeで記載してください。
また、これをこのままdescribeにしたとき、`context '2-4 ラベルのみ入力'`等と同じ階層にdescribeができてしまい、見づらいテストとなってしまいます。
フォーム入力や画面遷移など、画面内に存在する機能単位でdescribeをきりわけることで、見やすいテストになると思います。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +    context '3-1 タスク1件' do
タスク1件、という条件だと、複数のタスクが存在する場合もあるのか？となってしまい、詳細画面だと不要な条件です。
このcontext自体が不要に思えます。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +    end
このテストと266-282行目あたりのテストが重複しているように見えます。
describeを機能単位で分けるなどして見やすくしてください。

2022-08-24 02:28 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      let(:task_one) { FactoryBot.create(:task_not_started) }
`#show`では247行目にテストデータを定義することで、機能全体で利用するテストデータであることがわかりやすいです。
editではcontextごとに作っていますが、showと同じく`describe '4 #edit' do`の下で定義するでも良いと思います。

2022-08-24 06:33 UTC, connect-yuma-nakamura commented on myapp/spec/factories/task.rb
> +  factory :task_not_started, class: Task do
名称を「task_not_started」から「task」へ変更しました。

2022-08-24 06:34 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +  describe '1 #index' do
ナンバリングを削除しました。

2022-08-24 06:38 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      let!(:task_index_1) { task_one }
データ作成などはcontext内で実施するよう修正しました。

2022-08-24 06:48 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      end
createする際に2件目のデータに明示的に1件目と異なるデータを設定するよう修正しました。

2022-08-24 06:55 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        expect(Task.find_by(title: new_task[:title], content: new_task[:content], label: new_task[:label])).not_to be_nil
二重否定を修正しました。
> あと編集してわかったのですが、この行の最後に半角スペースが残っています。

こちら失礼しました。
設定したつもりができておらず、、。再度設定し、保存のタイミングで末尾の半角スペースがトリムされるよう修正しました。

2022-08-24 06:57 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      let(:new_task) {
おっしゃる通り、関連があるように見えます。
いただいた変数名をそのまま使わせていただきます。
input_valuesへ修正しました。

2022-08-24 07:00 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      it '2-1-1 登録内容が想定通りであること' do
曖昧なテスト項目の文言を修正しました。

2022-08-24 07:19 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +    context '2-5 画面遷移' do
違和感を持ちながら記載した箇所だったのでスッキリしました。ありがとうございます。
画面の機能単位（エリア単位）でdescribeをもう1階層作成しました。

2022-08-24 07:20 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +    context '3-1 タスク1件' do
強いていうならこれか？というところで書いていました。
おっしゃる通りconext（条件）自体不要だと思いましたので削除しました。

2022-08-24 07:23 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +    end
describeを全体的に見直しました。

2022-08-24 07:27 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      let(:task_one) { FactoryBot.create(:task_not_started) }
テストデータ定義場所を全体的に見直しました。

2022-08-24 07:37 UTC, R-KazumaInazaki approved these changes
LGTM！

2022-08-24 07:43 UTC, merged