step8 テスト(system spec)を書こう
Fablic/training pull request #1370
Opened 2022-08-23 05:29 UTC by miu-tsuzuki

■要件

### ステップ8: テスト(system spec)を書こう
- First make sure that these gems are exist in Gemfile
  ```
  group :test do
    gem 'capybara', '>= 2.15'
    gem 'selenium-webdriver'
  end
  ```
  **Note**: Remove the `webdrivers` gem from your Gemfile. If `webdrivers` is present, it will attempt to  find Chrome in your application’s container. 
  As Chrome isn’t installed  in the Dockerfile, the spec will fail.
  
- Before start testing we need to register a new driver with Capybara that is configured to use the Selenium container, add the below codes to 
  `spec/rails_helper.rb`
  ```
  Capybara.register_driver :remote_chrome do |app|
    hub_url = 'https://chrome:4444/wd/hub'
    chrome_capabilities = ::Selenium::WebDriver::Remote::Capabilities.chrome(
      'goog:chromeOptions' => {
        'args' => %w[no-sandbox headless disable-gpu window-size=1680,1050],
      },
    )
    Capybara::Selenium::Driver.new(app, browser: :remote, url: hub_url, desired_capabilities: chrome_capabilities)
  end

  config.before(:each, type: :system) do
    driven_by :rack_test
  end

  config.before(:each, type: :system, js: true) do
    driven_by :remote_chrome
    Capybara.server_host = IPSocket.getaddress(Socket.gethostname)
    Capybara.server_port = 3000
    Capybara.app_host = "https://#{Capybara.server_host}:#{Capybara.server_port}"
  end
  ```
- specを書くための準備をしましょう
  - `spec/spec_helper.rb` 、 `spec/rails_helper.rb` を用意しましょう
- ~~feature spec~~ system specをタスク機能に対して書きましょう
  - Rails 5.1 以降、新たにsystem testの機能を追加しました
    - [日本語](https://qiita.com/jnchito/items/c7e6e7abf83598a6516d), [英語](https://rossta.net/blog/why-rails-system-tests-matter.html)
  - dockerを利用して研修を行う場合、以下の設定が必要です。
    1. [Dockerfile](https://qiita.com/ngron/items/f61b8635b4d67f666d75#failed-to-read-the-sessionstorage-property-from-window-storage-is-disabled-inside-data-urls)
    2. [spec/rails_helper.rb](https://commis.hatenablog.com/entry/2018/11/16/171608)
  - feature specですと `database_cleaner` という gemは必要でしたが、 system specに変更することで `database_cleaner` の導入が要らなくなった
- Circle CIなどのCIツールを導入して、Slackに通知するようにしましょう
  - Fablic/training内でPRのやり取りをする場合、CIツールの導入は任意(optional)です。CircleCIのAdmin権限が無いので、`.circleci/config.yml`を設定しても実行できないです。
- 参考書籍：https://leanpub.com/everydayrailsrspec-jp

■確認方法
1. 下記コマンド実行

    ```shell docker-compose up --build```
    
1. 別ターミナルにて

    ```shell cd myapp ```
    ```shell docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb ```

2022-08-23 07:10 UTC, masayuki0001 reviewed
レビューしました！
基本的に草刈さんと同様の指摘をしておりますので、ご確認よろしくお願いします！（他に細かい指摘もプラスであります！）
指摘内容に関しては指摘箇所以外にも全体的に見て欲しい内容になっておりますのでその観点で修正していただけたらと思います！

2022-08-23 07:10 UTC, masayuki0001 commented on myapp/spec/system/tasks_spec.rb
> +  user = User.create!(name: 'name1')
Userに関しては「ステップ16: 複数人で利用できるようにしよう（ユーザの導入）」にて登場するため、現時点では導入されてない状態かとおもますのでこちらは適切なステップで導入をお願いします。
task_aとtask_bもuser_id指定しているのでこちらも適切なステップで導入でお願いします。

2022-08-23 07:10 UTC, masayuki0001 commented on myapp/spec/system/tasks_spec.rb
> +  let!(:task_b) { FactoryBot.create(:task, title: '２つ目のタスク', description: '２つ目のタスクを実施する', status: '1', label: '2', user_id: user[:id]) }
`let`と`let!`の使い分けはできておりますでしょうか？
例えば`describe '一覧表示機能'`で`task_a`を利用しますが、これはテスト実行直前から作っておく必要がなく、
遅延評価（初めて`task_a`という変数が呼ばれた時）で作成するでも問題なく動作するはずです。
テストに必要なデータだけを用意することで正確なテストができる、というのが主な観点です。
（規模が大きくなった際にRSpec全体のパフォーマンスにも影響してきます）

また、この位置でこれらのテストデータを定義すると、`describe 'タスク管理機能'`の配下のすべてのテストで利用されるデータのように見えます。
しかし、例えば15行目で`context 'タスクが1件存在する場合'`と書かれていますが、実際には２つデータが作成されており、条件と異なるテストとなってしまいます。
`context 'タスクが1件存在する場合'`の直下で5行目のデータ作成を、`context 'タスクが2件(複数)存在する場合'`の直下で5行目と6行目のデータ作成を行うことで、`context`とデータ作成がペアとなって正しいテストとなり、また可読性が上がります。
この時、5行目の内容が２つのcontextに書かれてしまい、DRYな実装ではなくなると思います。
ですが、RSpecではDRYな実装より読みやすいコードとなることを意識するようにしてください。

2022-08-23 07:10 UTC, masayuki0001 commented on myapp/spec/system/tasks_spec.rb
> +  end
ブロック区切りや処理のまとまりなど、適切に空行を挿入して区切りをわかりやすくましょう。
例としてここだけ抜粋しましたが、全体的に見直していただけたらと思います。
```suggestion
  shared_examples_for 'タスクが表示される' do
    it { expect(page).to have_content '最初のタスク' }
  end
  
  shared_examples_for '２つ目のタスクが表示される' do
    it { expect(page).to have_content '２つ目のタスク' }
  end
  
  describe '一覧表示機能' do
    context 'タスクが1件存在する場合' do
      before do
        # 確認するパス（URL）を設定
        visit tasks_path
      end
      
      it_behaves_like 'タスクが表示される'
    end
    
    context 'タスクが2件(複数)存在する場合' do
      before do
        visit tasks_path
      end
      
      it_behaves_like 'タスクが表示される'
      it_behaves_like '２つ目のタスクが表示される'
    end
  end
```

2022-08-23 07:10 UTC, masayuki0001 commented on myapp/spec/system/tasks_spec.rb
> +        expect(page).to have_content '1'
1つの`it`には1つの`expect`を書くようにしましょう。
まだ4つ程度であれば大きな問題にはなりませんが、このケースが失敗した時、どの`expect`で失敗したのか？がわかりづらくなるためです。
細分化することで、どのケースで失敗したのかが一目瞭然となります。

また、`expect(page).to have_content '1'`が二つ存在していますのでご確認お願いします。

2022-08-23 07:10 UTC, masayuki0001 commented on myapp/spec/system/tasks_spec.rb
> +  end
これらは一覧画面用のものだと思いますが、
`describe 'タスク管理機能'`直下の階層に書いた場合、
その階層内にある全てのテスト（`describe '一覧表示機能'`,`describe '詳細表示機能'`など）で必要なように見えます。（実際、`describe '一覧表示機能'`以外でも呼び出すことができてしまいます。）

`describe '一覧表示機能'`でのみ利用するものであれば、その直下に記載しましょう。

2022-08-23 07:10 UTC, masayuki0001 commented on myapp/spec/system/tasks_spec.rb
> +        visit tasks_path
`before`は主に、テスト実施の事前準備をおこなうために利用します。（例えば画面にアクセスするためのログインをしておく、必要なデータを用意する等）
今回の場合`visit tasks_path`は事前準備ではなく、期待値を得るための直接的な手順だと思いますので、
`it`の中に記載するようにしてください。
すると`it`だけを見た時、
```
一覧画面を表示した⇒結果、一覧に期待したタスクが表示された
```
といったまとまりができ、読みやすいspecとなります。

2022-08-23 07:10 UTC, masayuki0001 commented on myapp/spec/system/tasks_spec.rb
> +  describe 'ページ遷移' do
`describe 'ページ遷移'`を独立した機能としてテストしていますが、`一覧、登録、詳細、編集`画面に内包された機能であり、それらと横並びになる機能ではないと思います。
system specでは画面単位で`describe`を分けると、観点やコードが見やすくなると思います。
まずは画面単位で`describe`を切り、そのネスト内で表示機能、画面遷移機能などの機能単位で`describe`を記載すると、見やすいテストになるかと思います。

2022-08-26 05:26 UTC, connect-yuma-nakamura requested changes
全体的にきれいになりました。
いくつか指摘事項があるため確認をお願いします。

2022-08-26 05:26 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_1) { FactoryBot.create(:task, title: '最初のタスク', description: '最初のタスクを実施する', user_id: "1", status: "1", label: '1') }
``` ' ``` と ``` " ``` の使い分けができていません。
基本的に``` ' ``` を使用し、式展開する際に``` " ``` を使うようにしてください。
そうすることで他人にも使い分けの意図が伝わります。
→rubocopで怒られると思うので、一度rubocopを流してください。

2022-08-26 05:26 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      let(:description) { '新規作成のテストを書く２' }
titleとdescriptionは他contextと同様1つにまとめた方がわかりやすいです。

2022-08-26 05:26 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        expect(page).to have_selector '.alert-success', text: 'Update Task Success!!'
1つのitにつき1つのexpectにしてください。

2022-08-29 03:01 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +  user = User.create!(name: 'name1')
不要なUserを削除しました。

2022-08-29 03:01 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +  let!(:task_b) { FactoryBot.create(:task, title: '２つ目のタスク', description: '２つ目のタスクを実施する', status: '1', label: '2', user_id: user[:id]) }
letと let!の違いを理解し修正しました。

2022-08-29 03:02 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +  end
空行がなく、見づらいspecになっていたため、改行し、わかりやすくしました。

2022-08-29 03:03 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +        expect(page).to have_content '1'
複数のexpectがあったのでitに対しexpectが一つになるよう修正しました。

2022-08-29 03:04 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +  end
shared_examples_forを使用しないspecに修正しました。

2022-08-29 03:05 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +        visit tasks_path
beforeを使用しないよう修正しました。

2022-08-29 03:05 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +  describe 'ページ遷移' do
横並びになるものなので、それぞれのテスト項目に組み込みました。

2022-08-29 03:36 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +      let(:description) { '新規作成のテストを書く２' }
一つにまとめる修正をしました。

2022-08-29 05:07 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +        expect(page).to have_selector '.alert-success', text: 'Update Task Success!!'
1つのitにつき1つのexpectになるよう修正しました。

2022-08-29 05:09 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_1) { FactoryBot.create(:task, title: '最初のタスク', description: '最初のタスクを実施する', user_id: "1", status: "1", label: '1') }
'' と ""の違いを調査し、修正しました。

2022-08-29 05:45 UTC, connect-yuma-nakamura requested changes
何度もすみませんが、最後に追加で1点指摘しています。

2022-08-29 05:45 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          expect(tds[0]).to have_content task_1.title
すみません、早めに修正した方が良い内容を追加で1点。
テスト結果は動的なものとの比較をしないようにしてください。
ベタで文言を記述するよう全体的に修正してください。

2022-08-31 05:34 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +          expect(tds[0]).to have_content task_1.title
ベタで記載する修正を全体的に行いました。

2022-08-31 06:34 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-08-31 06:36 UTC, merged