ステップ11: バリデーションを設定してみよう
Fablic/training pull request #1372
Opened 2022-08-25 09:30 UTC by connect-yuma-nakamura

■要件
### ステップ11: バリデーションを設定してみよう

- バリデーションを設定しましょう
  - どのカラムにどのバリデーションを追加したらよいか考えてみましょう
  - 合わせてDBの制約も設定するマイグレーションを作成しましょう
  - マイグレーションファイルだけを作成するため、 `rails generate` コマンドで作成します
- 画面にバリデーションエラーのメッセージを表示するようにしましょう
- バリデーションに対してモデルのテストを書いてみましょう
- GitHub上でPRを作成してレビューしてもらいましょう

■確認手順
【バリデーションエラーメッセージ確認】

1. 以下ページへアクセスし、作成ボタンを押下

``` http://localhost:3001 ```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/186610993-c46e475d-1c13-42f2-b65b-fa0aab3bf43c.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/186611231-b8b53b49-cafc-4835-a748-04905436aecf.png">

2. 未入力の状態で作成ボタンを押下

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/186620381-190b0ddd-586b-4af7-86a9-91b8ba58b943.png">

エラーが表示されること

3. 入力した状態で作成ボタンを押下

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/186620751-97f95948-8bff-443c-99b2-eb8adafc8868.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/186620803-253fb3ac-5a21-4ee5-8fa7-9ed9615055aa.png">

タスクが作成されること

【RSpec実行】

1. dockerを立ち上げた状態で以下コマンド実行
``` docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb ```

2022-08-26 05:43 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。
指摘箇所以外に、全体的に見直しをお願いします。

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/models/tasks_spec.rb
> +    context 'title' do
'title'は条件ではなく「何をテストするのか」という説明にあたると思いますので、contextではなくdescribeで記載しましょう。

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/models/tasks_spec.rb
> +      end
itに条件を書いており、期待値が書かれていないため、全体的にわかりづらいです。
ここだと文字数が条件に当たり、validなのかinvalidなのかが期待値にあたると思いますので細分化しましょう。

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/models/tasks_spec.rb
> +      it '正常' do
「正常」という言葉が曖昧で、実装者以外が見たとき正常な値とは何か？がわかりません。
128文字のテストでも期待値は同じなので、バリデーションが通るという観点では重複しているように思えます。

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/models/tasks_spec.rb
> +      it '0文字' do
境界値のテストが最大値の時はできてますが、最小値の時ができていません。
1文字のパターンもあると良さそうです。

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/models/tasks_spec.rb
> +          '1234567890123456789012345678'
実際に128文字を並べるでも良いですが、もっと桁数が多くなった時に見づらくなりそうです。
`'1' * 128`といったように文字列を乗算することで、似たような値を作ることができます。

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +      context '正常' do
こちらもモデルのSpecと同様です。
バリデーションに成功する入力値の時、など、もう少し具体的な説明がほしいです。

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/models/tasks_spec.rb
> +        task.title = ''
一度paramsで代入した後に上書きするのは冗長だと思います。
別の指摘の対応でcontextができるはずなので、contextごとにparamsを作成しましょう。
また、`Task.new `としなくても、`FactoryBot.build(:task)`で同様の処理ができ、テストと関係ない項目はFactory側で定義した初期値を使えるので、書きやすくなると思います。

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_content("#{I18n.t('activerecord.attributes.task.title')}#{I18n.t('errors.messages.too_short', count: 1)}")
メソッドを利用して動的にすることで保守性は高くなりますが、ここでの期待値は文字列を記載しましょう。
どのような値を期待しているのか？がわかりやすくなる他、
期待値側が動的に変わると、想定外の値なのにテストが通ってしまう、といったことが起こり得ます。

（例えば現場作業だと、エラーメッセージは画面設計を元に実装しているはずですが、共通化された文言を利用しているので、他の誰かが修正してしまった時に設計と異なる値になってしまう等）

2022-08-26 05:43 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +          expect(Task.find_by(input_values)).to be_nil
このあたりに追加されているテスト、どれも入力値ごとの挙動をテストしており、これでも問題はないのですが、、、
上の階層で`describe '入力エリア'`と機能単位でテストを分けているはずなので、
エラー表示機能として切り出すことで、エラーメッセージ以外のテストをする必要がなくなりそうです。
修正はお任せします！

2022-08-26 07:00 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +    context 'title' do
contextとitの表記がちぐはぐでしたので全体的に見直しました。

2022-08-26 07:01 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +      end
contextとitの表記がちぐはぐでしたので全体的に見直しました。

2022-08-26 07:01 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +      it '正常' do
確かにおっしゃる通りです。削除しました。

2022-08-26 07:01 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +      it '0文字' do
1文字のパターンを追加しました。

2022-08-26 07:01 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +          '1234567890123456789012345678'
ありがとうございます。すっきり記述することが出来ました。

2022-08-26 07:02 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +      context '正常' do
条件を多少具体的になるよう修正しました。

2022-08-26 07:03 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +        task.title = ''
systemのようにletを使用し、すっきりした形で記述するよう修正しました。

2022-08-26 07:04 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_content("#{I18n.t('activerecord.attributes.task.title')}#{I18n.t('errors.messages.too_short', count: 1)}")
確かに意図せず通ってしまう可能性があるため、動的値をなくしました。

2022-08-26 07:04 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          expect(Task.find_by(input_values)).to be_nil
確かにエリア毎に分けているため、エラー表示エリアは分けるべきでした。
入力エリアが肥大化するのを防ぐ意図も込め、修正しました。

2022-08-26 09:39 UTC, R-KazumaInazaki commented on myapp/spec/models/tasks_spec.rb
> +        end
今回のようにletがそのままテスト対象となる場合、letではなくsubjectを使いましょう。
subjectはテストの対象であることを明確にするためのものです。
また、expectの中身がsubjectだけであった場合、以下のように書くことができます。
```suggestion
        subject(:task) { FactoryBot.build(:task, title: '') }

        it 'invalid' do
          is_expected.to be_invalid
        end
```
`is_expected`を用いることでそのまま英文のように書くことができるため、
itの説明も省略して大丈夫です。（itがsubjectに相当します。）

```suggestion
        subject(:task) { FactoryBot.build(:task, title: '') }

        it { is_expected.to be_invalid }
```

2022-08-29 02:14 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +        end
お教えいただいた通りに修正しました。
より見やすくなりました。ありがとうございます。
→評価対象の場合、letではなくsubjectにするとのこと理解しました。

2022-08-29 02:29 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-08-29 02:33 UTC, merged