STEP9: アプリの各種設定を行いましょう
Fablic/training pull request #1373
Opened 2022-08-26 03:27 UTC by kohei-matsubara

下記の対応が完了しましたので、レビューをお願いいたします。

■要件
### ステップ9: アプリの各種設定を行いましょう

- 日本語部分を共通化
  - Railsのi18nの仕組みを利用して、日本語リソースの共通化をしましょう
  - ※i18n化を行うと後のステップでメッセージを出したりするのが楽になるなどのメリットがあります
- タイムゾーンの設定
  - Railsのタイムゾーンを日本（東京）に設定しましょう
- エラーページの設定
  - Railsが用意しているデフォルトのエラーページを自分が作った画面にしてみましょう
  - 状況に応じて、適切にエラーページを設定しましょう
  - ステータスコードの404ページと500ページの2種類の設定は少なくとも必須とします

■対応内容 ＜Step9＞
・日本語化
　- application.rbに設定を追加
　- Gemfileに設定を追加
　- Viewで日本語表示になるよう修正
　- ja.ymlにenumを追加
・タイムゾーンの設定
　- application.rbに設定を追加
・エラーページ 　
　- エラー用メソッド（applicationコントローラ内）の作成
　- ルーティング設定
　- エラーページ作成

＜その他＞ 
・日本語化対応をしたことでsystem specでエラーが起きるようになってしまったため、日本語に対応できるようsystem specを修正

■確認方法
 ・事前準備
 　下記コマンドでDockerを起動 　
　docker-compose up --build
　下記コマンドでDBを作成 　
　docker-compose exec api rails db:create
　下記コマンドでテーブルを作成 　
　docker-compose exec api rails db:migrate
　下記コマンドでデータを作成 　
　docker-compose exec api rails c 　 　
　Task.create(title: '最初のタスク', description: '最初のタスクを実施する', user_id: "1", status: "1", label: 1);

・日本語化　
　下記URLで一覧画面に遷移し、ステータスと優先度を確認 　http://localhost:3001

・タイムゾーン設定
　下記コマンドを実行  （現在時刻が日本時間で表示される）
　docker-compose exec api rails c
　Time.current 　
　下記URLで一覧画面を開き、「詳細」を押下し、詳細画面に登録日時、更新日時が日本時間で表示されることを確認
　http://localhost:3001/ 

・エラーページ
　- 404
　　下記URLを開く（存在しないURLであればなんでも良い）
 　　http://localhost:3001/notexist

　-500
　　ソースの一部を下記のように変更（7行目をコメントアウト）
　　controllers/task_controller.rb
```
  def index
    # @tasks = Task.all
  end
``` 　

　　下記URLで一覧画面を開く 　
　　http://localhost:3001/ 

2022-08-26 05:35 UTC, connect-yuma-nakamura requested changes
指摘事項がいくつかありますので修正をお願いします。

2022-08-26 05:35 UTC, connect-yuma-nakamura commented on myapp/app/controllers/application_controller.rb
>  end
railsの機能として、500の時はpublic/500.html、404の時はpublic/404.htmlが呼ばれる仕組みがあります。
手でここに設定してレンダリングするといらぬ障害を埋め込む元になるので基本的には元々の仕組みを利用するようにしてください。

2022-08-26 05:35 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    # @tasks = Task.all
このコメントアウトは必要？

2022-08-26 05:35 UTC, connect-yuma-nakamura commented on myapp/config/routes.rb
> +  post '*not_found' => 'application#routing_error'
railsの機能として、500の時はpublic/500.html、404の時はpublic/404.htmlが呼ばれる仕組みがあります。
手でここに設定してレンダリングするといらぬ障害を埋め込む元になるので基本的には元々の仕組みを利用するようにしてください。

2022-08-26 05:35 UTC, connect-yuma-nakamura commented on myapp/db/schema.rb
> -ActiveRecord::Schema.define(version: 2022_08_08_080642) do
このファイルの修正は必要？
rubocopで自動的に修正されたのであれば、こちらのファイルは自動生成なのでrubocopの対象外にしてください。

2022-08-26 07:52 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    # @tasks = Task.all
コメントアウトは不要だったので削除しました。

2022-08-26 07:57 UTC, kohei-matsubara commented on myapp/db/schema.rb
> -ActiveRecord::Schema.define(version: 2022_08_08_080642) do
修正は不要だったため対象外にしました。

2022-08-26 09:04 UTC, kohei-matsubara commented on myapp/app/controllers/application_controller.rb
>  end
シンプルな作りに修正しました。

2022-08-26 09:04 UTC, kohei-matsubara commented on myapp/config/routes.rb
> +  post '*not_found' => 'application#routing_error'
シンプルな作りに修正しました。

2022-08-29 02:26 UTC, connect-yuma-nakamura requested changes
1点確認事項があるので確認をお願いします。

2022-08-29 02:26 UTC, connect-yuma-nakamura commented on myapp/db/schema.rb
> +    t.bigint "user_id"
この対応はなんでしょう？

2022-08-29 02:36 UTC, kohei-matsubara commented on myapp/db/schema.rb
> +    t.bigint "user_id"
動作確認時に一度消したまま、その後戻さずにそのままにしていました。
null falseを戻しました。

2022-08-29 02:49 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-08-30 02:44 UTC, merged