ステップ13: ステータスを追加して、検索できるようにしよう
Fablic/training pull request #1374
Opened 2022-08-29 04:56 UTC by connect-yuma-nakamura

■要件
### ステップ13: ステータスを追加して、検索できるようにしよう

- ステータス（未着手・着手中・完了）を追加してみよう
  - 【オプション要件】初学者ではない場合はstateを管理するGemを導入しても構いません
- 一覧画面でタイトルとステータスで検索ができるようにしよう
  - 【オプション要件】初学者ではない場合はransackなどの検索の実装を便利にするGemを導入しても構いません
- 絞り込んだ際、ログを見て発行されるSQLの変化を確認してみましょう
  - 以降のステップでも必要に応じて確認する癖をつけましょう
- 検索インデックスを貼りましょう
- 検索に対してmodel specを追加してみよう（system specも拡充しておきましょう）

■対応内容
- ステータス追加
- 検索機能追加
- tasksへインデックス追加
- specの追加
- specの既存バグ修正
- specのコメント整理

■確認手順
【検索機能確認】
1. 以下ページへアクセス

``` http://localhost:3001 ```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/187118389-d8babc5b-14c2-4dc0-a107-505578828ab7.png">

2. 既に存在するタスク名「タスク9」を入力し、タスク作成

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/187124761-15f31cf0-3da5-40f6-baa5-4c07c58ed01c.png">

4. 作成した「タスク9」のステータスを着手中へ変更

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/187124924-11ef78eb-059c-4feb-ace1-526c1bf142ae.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/187124949-917a7a9b-552c-4eb8-ab72-dcb847b3805d.png">

5. 「タスク9」、着手中 を指定し、検索

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/187125021-71f677e3-04ec-4743-9aa8-a264236cd2ef.png">

【検索機能テスト】

1. 以下コマンド実行

``` docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb ```
``` docker-compose exec api bundle exec rspec -f d spec/models/tasks_spec.rb ```

2022-08-31 05:44 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-08-31 05:44 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/edit.html.erb
> +  <%= render partial: 'form', locals: { url: task_path(@task), method: 'put', button_name: I18n.t('button.update'), is_status: true } %>
`is_status`はControllerから渡すようにしましょう。
Viewで切り替えることも出来るのですが、Taskデータの仕様（新規であればステータスはユーザーから登録させない）に関わる部分は、ControllerやModelに集約し、分散させない方がわかりやすいです。

2022-08-31 05:44 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/new.html.erb
> +  <%= render partial: 'form', locals: { url: tasks_path, method: 'post', button_name: I18n.t('button.create'), is_status: false } %>
こちらも合わせて修正お願いします。

2022-08-31 05:44 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +    sql += " status = '#{status}' " if status.present?
SQLにviewから渡されたパラメータを直接展開してしまうと、SQLインジェクションという攻撃に対して非常に弱くなります。
試しに検索フォームでTitleの入力欄に`'`を含む文字列を入力するとエラーになると思います。

ActiveRecordにはデフォルトでその対策が実装されていますので、可能な限りActiveRecordに準拠した書き方にしましょう。
例えばLIKE検索は以下のような書き方をします。
```
Task.where('title LIKE ?', "%{title}%")
```
`=`の検索も、以下のような書き方をします。
```
Task.where(status: status)
```

2022-08-31 05:44 UTC, R-KazumaInazaki commented on myapp/spec/models/tasks_spec.rb
> +      let(:title_list) { Task.search('', '').pluck(:title) }
1つ前のPRでも指摘しましたが、テスト対象はsubjectで記載しましょう。

2022-08-31 05:44 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        let(:conditions) { { word: '' } }
ステータスも空文字を入力していると思うので、conditionsから参照するようにしましょう。
指定しない時はitの中で直接指定する、といった書き方になっていますが、統一できていないのでわかりづらいです。

2022-08-31 05:44 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +          visit root_path
visitのあとに改行を入れている場合と入れていない場合があるので、統一しましょう。

2022-08-31 05:44 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        let(:tds_two){ all('tbody tr')[1].all('td') }
ここもSubjectを利用しましょう。

2022-09-01 03:20 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/edit.html.erb
> +  <%= render partial: 'form', locals: { url: task_path(@task), method: 'put', button_name: I18n.t('button.update'), is_status: true } %>
Controllerで設定した値を参照するように修正しました。

2022-09-01 03:20 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/new.html.erb
> +  <%= render partial: 'form', locals: { url: tasks_path, method: 'post', button_name: I18n.t('button.create'), is_status: false } %>
こちらも修正しました。

2022-09-01 03:32 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +      let(:title_list) { Task.search('', '').pluck(:title) }
失礼しました。
subjectを使用するよう修正しました。

2022-09-01 03:41 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        let(:conditions) { { word: '' } }
確かにテストデータが中途半端でした。
どちらもconditionsに定義し、参照するよう修正しました。

2022-09-01 04:56 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          visit root_path
spec内の改行位置が全体的に統一されていなかったため、見直しました

2022-09-01 05:30 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        let(:tds_two){ all('tbody tr')[1].all('td') }
こちらの指摘は間違えているので無視してください。

subjectはテスト対象を記載すると言いましたが、このテストの場合、
subjectに記載するべき処理は`visit root_path`になります。
`visit root_path`した時、画面にタスクが表示されることを確認したく、
`all('tbody tr')[0].all('td')`はあくまで「画面にタスクが表示されること」を確認するために必要な処理ですので、
subjectにするべきではない、といった考えになります。

> subjectに記載するべき処理は`visit root_path`

このように書きましたが、ここでは無理にsubjectを使う必要はありません。
subjectは`is_expected`が利用できるような、対象の返り値をテストしたい場合に有効ですが、
このテストでは`visit root_path`を行った時、副次的に生成されるpageやallなどをテストしたいので、
subjectを使うことで逆に分かりづらいテストになってしまいます。

2022-09-01 05:30 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +    sql += " status = '#{status}' " if status.present?
ActiveRecordのwhereに修正しました。

2022-09-01 05:36 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        let(:tds_two){ all('tbody tr')[1].all('td') }
細かく解説いただきありがとうございます！
内容理解しました。

2022-09-01 05:53 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +    return Task.where('title like ?', "%#{word}%").where(status: status).order(order) if !word.blank? && !status.blank?
複数回、同じ実装のwhereが出る時はscopeを使いましょう。
また、scopeにはparamsを引数として渡すことができるので、scope内でblank?チェックもするとわかりやすくなると思います。

2022-09-01 05:59 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +    sql += " status = '#{status}' " if status.present?
https://github.com/Fablic/training/pull/1374/files#r960243994
こちらにコメントしました。

2022-09-01 06:02 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).not_to have_content 'titleB1'
click_onとexpectの間の改行も統一してください。

2022-09-01 06:03 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +          visit root_path
追加でコメントしています。
https://github.com/Fablic/training/pull/1374/files#r960248777

2022-09-01 06:14 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +    return Task.where('title like ?', "%#{word}%").where(status: status).order(order) if !word.blank? && !status.blank?
ありがとうございます！
スコープを使用することでわかりやすく作成することができました。

2022-09-01 06:19 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).not_to have_content 'titleB1'
失礼しました。
一部不要な改行が残っていたため削除しました。

2022-09-01 08:27 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  scope :where_status, -> (status) { where(status: status) if !status.blank? }
`!word.blank?`は二重否定となっておりわかりづらいです。
また、`where_word`という名前ですが、実際に検索しているのは`title`ですのでそちらに合わせましょう。

2022-09-01 08:28 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +    return Task.where_word(word).where_status(status).order(order);
指摘漏れていましたが、`order`はもう少しシンプルに扱えます。
`order(created_at: :desc)`で動くと思うので試してみてください。

2022-09-01 08:31 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  def self.search(word, status)
おそらくここまで短縮できれば、メソッドにする必要もなく、Controllerから直接呼び出すでも良いと思います。

2022-09-01 09:09 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +  scope :where_status, -> (status) { where(status: status) if !status.blank? }
present?へ修正しました。
また、全体的に``` word ```を``` title ```へ変更しました。

2022-09-01 09:21 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +  def self.search(word, status)
承知しました。
直接呼び出しでも違和感なかったため、修正しました。

2022-09-01 23:46 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-09-01 23:49 UTC, merged