Kohei matsubara step11
Fablic/training pull request #1377
Opened 2022-08-30 04:43 UTC by kohei-matsubara

■要件
ステップ11: バリデーションを設定してみよう
バリデーションを設定しましょう
どのカラムにどのバリデーションを追加したらよいか考えてみましょう
合わせてDBの制約も設定するマイグレーションを作成しましょう
マイグレーションファイルだけを作成するため、 rails generate コマンドで作成します
画面にバリデーションエラーのメッセージを表示するようにしましょう
バリデーションに対してモデルのテストを書いてみましょう
GitHub上でPRを作成してレビューしてもらいましょう

■確認手順
【バリデーションエラーメッセージ確認】

以下ページへアクセスし、新規登録ボタンを押下
http://localhost:3001
<img width="1356" alt="スクリーンショット 2022-08-30 12 41 01" src="https://user-images.githubusercontent.com/110374166/187350856-d8ae2669-7ebe-4e22-8bcc-b883d2f20ed7.png">

タスクが作成されること

【RSpec実行】

dockerを立ち上げた状態で以下コマンド実行
docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb

2022-08-30 05:12 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> -        let!(:task_1) { FactoryBot.create(:task, title: '最初のタスク', description: '最初のタスクを実施する', user_id: "1", status: "1", label: 1) }
式を使っていないところで""を使っている箇所があったので全体的に見直し修正しました。

2022-08-31 00:19 UTC, connect-yuma-nakamura requested changes
レビューしました。
指摘項目について確認をお願いいたします。

2022-08-31 00:19 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +    validates :description, length: { maximum: 100 }
1つの属性に対して1行で複数条件を指定できるため、そのようにした方が見やすいです。
1行1カラムの方が他者が見た場合にいくつのカラムに対して条件を付与しているのかがぱっと見把握しやすいです。

``` ruby
    validates :title, presence: true, length: { maximum: 30 }
    validates :description, presence: true, length: { maximum: 100 }
```

2022-08-31 00:19 UTC, connect-yuma-nakamura commented on myapp/spec/models/tasks_spec.rb
> +    end
必須のバリデーションに対するテスト項目がないです。
→0文字はlengthで怒られます。
nilのテストケースが必要か？エラーメッセージを確認してみてください。
説明も同様。

2022-08-31 00:19 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +    describe '詳細カラム' do
詳細と説明でこのカラムを指す名称が統一されていないです。

2022-08-31 00:19 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +  describe 'バリデーション' do
valid or invalid のテストはmodelのspecの観点です。
systemのspecの観点としてはエラーの結果画面にどう動きがあるのが正しいかを確認するテストにしてください。
具体的には、エラーメッセージが表示される場合はエラーメッセージが表示されることの確認をしてください。

準備したメソッドのモジュール観点での確認　→　model spec
メソッドを呼び出した後の動作の確認　→　system spec

2022-09-01 00:02 UTC, kohei-matsubara commented on myapp/app/models/task.rb
> +    validates :description, length: { maximum: 100 }
まとめて記載する方法で記載し直しました。

2022-09-01 01:18 UTC, kohei-matsubara commented on myapp/spec/models/tasks_spec.rb
> +    end
modelsのテストとしてはnilのテストケースは必要だと判断しテストを追加しました。

2022-09-01 01:23 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +    describe '詳細カラム' do
SystemのSpecで名称が統一されていなかった箇所があったため、修正しました。

2022-09-01 02:08 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +  describe 'バリデーション' do
エラーメッセージが表示されるかどうかのテストに修正しました。

2022-09-05 00:08 UTC, connect-yuma-nakamura requested changes
指摘箇所の確認をお願いします。

2022-09-05 00:08 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/_form.html.erb
> +        <li class='error_list' ><%= msg %></li>
エラーメッセージの日本語化がされていないようなので日本語化をしましょう。

2022-09-05 00:08 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_selector '.error_list', text: "Title can't be blank"
シングルクォーテーションを使ってください。

2022-09-05 02:20 UTC, kohei-matsubara commented on myapp/app/views/tasks/_form.html.erb
> +        <li class='error_list' ><%= msg %></li>
エラーメッセージの日本語を追加しました。

2022-09-05 02:22 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_selector '.error_list', text: "Title can't be blank"
can'tの ' が含まれているため、シングルクォーテーションを使うとおかしくなってしまうのでダブルクォーテーションを使用しています。

2022-09-05 04:27 UTC, connect-yuma-nakamura requested changes
日本語化になっていない画像が説明欄に貼られているので、そこの差し替えをお願いします。

2022-09-06 02:50 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-09-06 05:10 UTC, merged