ステップ16: 複数人で利用できるようにしよう（ユーザの導入）
Fablic/training pull request #1384
Opened 2022-09-02 09:09 UTC by connect-yuma-nakamura

■要件

### ステップ16: 複数人で利用できるようにしよう（ユーザの導入）

- ユーザモデルを作成してみましょう
- 最初のユーザをseedで作成してみましょう
- ユーザとタスクが紐づくようにしましょう
  - 関連に対してインデックスを貼りましょう
  - N+1問題を回避するための仕組みを取り入れましょう
    - N+1クエリを自動検出するbulletを導入してみましょう（[参考記事](https://fablic.qiita.com/craftcat/items/b181b67ddae0c7d0702a)）

■対応内容
- Users追加
- 担当者選択項目追加
- bullet導入

■確認手順
1. 以下ページへアクセス

``` http://localhost:3001 ```

- 担当者が表示されていることを確認

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188104545-314ef582-8f26-47a3-9e0e-dba9ddcb734c.png">

2. タスク作成

- タスク作成画面にて担当者が選択できること
- 選択した担当者でタスクが作成されていること

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188104839-c7f65746-5c3b-438f-9ac2-2169202f8529.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188104886-ed81c898-be31-41bb-b13e-b6cad2cc9ef6.png">

3. タスク詳細画面へ遷移

- タスク詳細画面に担当者が表示されていること

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188105001-ccc65d4b-5c69-41be-8c25-e62e14f13ef1.png">

4. タスク編集

- タスク編集画面にて担当者の選択ができること
- 担当者の編集ができること

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188105184-16ab01ee-894d-4202-9db6-151125a009ca.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188105295-259e331a-7620-41dd-83af-50a0295cac90.png">

5. spec実行

``` docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb ```

2022-09-05 00:21 UTC, R-KazumaInazaki requested changes
レビューしました。
コメントご確認お願いいたします。

2022-09-05 00:21 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_form.html.erb
> +  <%= f.select(:user_id, @users_name) %>
モデル情報に紐づくselectは、`collection_select`を使いましょう。
おそらく、mapの処理が不要になると思います。

2022-09-05 00:21 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    task_params[:user_id] = task_params[:user_id]
この処理が何をしたいのかがわからないです。

2022-09-05 00:21 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @users_name = users_name
この処理`new, create, edit, update`で共通だと思うので、before_actionで呼ぶようにしましょう。

2022-09-05 00:21 UTC, R-KazumaInazaki commented on myapp/spec/factories/task.rb
> +    user_id  { FactoryBot.create(:user).id }
たしか、以下のように書くこともできたと思います。
```suggestion
    user
```
今の状態だとtaskを呼び出すたびにユーザーを作成してしまいますが、
上記のように記載することで、taskオブジェクト作成時の引数にuserを指定すればそのユーザーと紐付き、
引数で指定しなければ新しいユーザーが作成される、といった動きをさせることができたと思いますので、試してみてください。

2022-09-05 00:21 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +          select value = User.find(input_values[:user_id]).name, from: 'task[user_id]'
わざわざfindせずとも、user.nameで取れるのでは？

2022-09-06 02:31 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/_form.html.erb
> +  <%= f.select(:user_id, @users_name) %>
collection_selectを使用するよう修正しました。

2022-09-06 02:32 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    task_params[:user_id] = task_params[:user_id]
不要であったため削除しました。

2022-09-06 02:33 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @users_name = users_name
他指摘の修正に伴い、担当者名リストを削除しました。

2022-09-06 02:35 UTC, connect-yuma-nakamura commented on myapp/spec/factories/task.rb
> +    user_id  { FactoryBot.create(:user).id }
なるほど、ありがとうございます。
上記のように修正しました。

2022-09-06 02:39 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          select value = User.find(input_values[:user_id]).name, from: 'task[user_id]'
おっしゃる通り、user.nameで取得できるため全体的に修正しました。

2022-09-06 02:48 UTC, R-KazumaInazaki approved these changes
LGTM！

2022-09-06 02:49 UTC, merged