STEP9 アプリの各種設定を行いましょう
Fablic/training pull request #1388
Opened 2022-09-06 01:50 UTC by miu-tsuzuki

下記の対応が完了しましたので、レビューをお願いいたします。

■要件
### ステップ9: アプリの各種設定を行いましょう

- 日本語部分を共通化
  - Railsのi18nの仕組みを利用して、日本語リソースの共通化をしましょう
  - ※i18n化を行うと後のステップでメッセージを出したりするのが楽になるなどのメリットがあります
- タイムゾーンの設定
  - Railsのタイムゾーンを日本（東京）に設定しましょう
- エラーページの設定
  - Railsが用意しているデフォルトのエラーページを自分が作った画面にしてみましょう
  - 状況に応じて、適切にエラーページを設定しましょう
  - ステータスコードの404ページと500ページの2種類の設定は少なくとも必須とします

■対応内容 ＜Step9＞
・日本語化
　- application.rbに設定を追加
　- Gemfileに設定を追加
・タイムゾーンの設定
　- application.rbに設定を追加
・エラーページ 　
　- エラー用メソッド（applicationコントローラ内）の作成
　- ルーティング設定
　- エラーページ作成

＜その他＞ 
・日本語化対応をしたことでsystem specでエラーが起きるようになってしまったため、日本語に対応できるようsystem specを修正

■確認手順
 ・事前準備
 　下記コマンドでDockerを起動 　
　docker-compose up --build
　下記コマンドでDBを作成 　
　docker-compose exec api rails db:create
　下記コマンドでテーブルを作成 　
　docker-compose exec api rails db:migrate
　下記コマンドでデータを作成 　
　docker-compose exec api rails c 　 　
　Task.create(title: '最初のタスク', description: '最初のタスクを実施する', user_id: "1", status: "1", label: 1);

・日本語化　
　下記URLで一覧画面に遷移し、ステータスと優先度を確認 　http://localhost:3001

・タイムゾーン設定
　下記コマンドを実行  （現在時刻が日本時間で表示される）
　docker-compose exec api rails c
　Time.current 　
　下記URLで一覧画面を開き、「詳細」を押下し、詳細画面に登録日時、更新日時が日本時間で表示されることを確認
　http://localhost:3001/ 

・エラーページ
　- 404
　　下記URLを開く（存在しないURLであればなんでも良い）
 　　http://localhost:3001/notexist

　-500
　　ソースの一部を下記のように変更（7行目をコメントアウト）
　　controllers/task_controller.rb

```
  def index
    # @tasks = Task.all
  end
```

　　下記URLで一覧画面を開く 
　　http://localhost:3001/ 

2022-09-06 02:00 UTC, connect-yuma-nakamura requested changes
1点指摘しています。確認をお願いいたします。

2022-09-06 02:00 UTC, connect-yuma-nakamura commented on myapp/config/locales/ja.yml
> +    edit: 'タスク編集画面'
定義しているが、使用していないものがあります。
各画面で使用するか、もしくは未使用の定義を削除してください。

2022-09-06 07:36 UTC, connect-yuma-nakamura requested changes
前回の指摘にコメントがないのでコメントを記述してください。
また、修正してもらった後の状態で1点指摘箇所があるので修正をお願いします。

2022-09-06 07:36 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/index.html.erb
>            <td><%= link_to('Details', task_path(task), {id: "show#{task.id}" ,class: 'btn_a'}) %></td>
ここだけ辞書が使用されていないので使用するよう修正してください。

2022-09-07 02:34 UTC, miu-tsuzuki commented on myapp/app/views/tasks/index.html.erb
>            <td><%= link_to('Details', task_path(task), {id: "show#{task.id}" ,class: 'btn_a'}) %></td>
辞書を使用するように修正しました。

2022-09-07 02:35 UTC, miu-tsuzuki commented on myapp/config/locales/ja.yml
> +    edit: 'タスク編集画面'
未定義のものを削除し、必要なものを再度追加しました。

2022-09-07 05:24 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-09-07 05:39 UTC, merged