ステップ17: ログイン/ログアウト機能を実装しよう
Fablic/training pull request #1394
Opened 2022-09-06 07:02 UTC by connect-yuma-nakamura

■要件
### ステップ17: ログイン/ログアウト機能を実装しよう

- 追加のGemを使わず、自分で実装してみましょう
  - DeviseなどのGemを使わないことで、HTTPのCookieやRailsにおけるSessionなどの仕組みについて理解を深めることが目的です
  - また、一般的な認証についての理解を深めることも目的にしています（パスワードの取り扱いについてなど）
- ログイン画面を実装しましょう
- ログインしていない場合は、タスク管理のページに遷移できないようにしましょう
- 自分が作成したタスクだけを表示するようにしましょう
- ログアウト機能を実装しましょう

■対応内容
- ログイン/ログアウト機能追加
- 自分が作成したタスクのみ表示
- 上記対応に伴い、担当者設定項目削除

■確認手順
1. 以下ページへアクセス
``` http://localhost:3001 ```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188563974-16b0dea2-5196-479f-bccb-9b9cc0c409ec.png">

- ログイン画面が表示されること

2. 以下情報を入力してログインボタンを押下
メールアドレス：email1@example.com
パスワード：test1

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188564357-61ecbed4-33cd-4935-a588-149a424a21a1.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188564483-6dc75689-1edf-46b2-812d-ca15ffd1ad64.png">

- ログインできること

3. ログアウトボタンを押下

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/188564622-687815f0-03ab-4277-b2f0-7208291dbf5b.png">

- ログイン画面へ戻ること

4. 以下ページへアクセスできないこと
``` http://localhost:3001/tasks/new```
``` http://localhost:3001/tasks/1/edit```

2022-09-07 06:14 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220829071638_add_password_digest_to_users.rb
> +  end
migrationファイルの分け方ですが、
同じテーブルに対する操作は特別な理由がない限り、ひとつのmigrationにまとめるで問題ありません。
過去のmigrationを編集してしまうのには問題がありますが、例えば今回のように、
ログイン機能実装にあたってカラム追加する等、機能実装時にmigrationをまとめるのは、問題ないです。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220830033331_add_index_to_users_password_digest.rb
> +  end
中身がなにもないように見えます。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/app/helpers/sessions_helper.rb
> +  def login(user)
HelperはViewの中で利用するメソッドを用意する場所です。
このようなログイン関連のメソッドは、各Controllerで必ず必要となる処理だと思うので、ApplicationController側に直接実装しましょう。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/app/models/user.rb
> +  end
暗号化系の実装、参考にしたものがあれば教えていただけると嬉しいです！
Railsでは一般的に、bcryptというgemを利用して暗号化処理を実装します。
研修なのと、しっかりと実装されているのでこのままで問題ないとは思っていますが、
自分にあまり知見がないので、参考があると嬉しいです。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
この参照の仕方だと、URLに別のユーザーのIDを入力する開けてしまいます。
ユーザーの持つタスクのみ開けるようにしてください。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    task_params
メソッドを作る時、可能な限りメソッドの役割を少なくするようにしましょう。
例えばこの場合、以下の役割があります
* 送信されたparamsの中身をrequireとpermitで検証する
* login_userとタスクを紐づける

このうち、login_userとの紐付けは過剰な役割です。
メソッドの呼び出し元で処理しましょう。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/app/helpers/sessions_helper.rb
> +  end
login周りのフローがかなり複雑なので、フロー図などを用いて見直してください。
おそらく無駄なチェックがあるはずです。
（login_userを返すときにインスタンス変数の存在チェックしていますが、本来チェックすべきはcookiesのlogin_tokenでは？）
もし時間がかかりそうであれば、bcryptのgemを使用することも検討してみてください。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/app/helpers/sessions_helper.rb
> +    cookies[:login_token] = token
cookiesはブラウザ側から簡単に値をみられてしまいますが、sessionとcookiesのどちらを使うか？などの検討はされましたでしょうか。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/app/helpers/sessions_helper.rb
> +    redirect_to(login_path) if !login?
`if + !`で否定をするならunlessで良いと思います。
unlessとの使い分けとして、二重否定になるパターンは避けてほしいですが、
今回のように否定が一度なら使ったほうがわかりやすいです。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = Task.where_user_id(login_user.id).where_title(params[:title]).where_status(params[:status]).order('tasks.created_at desc').page(params[:page])
Model側でユーザーとタスクの関連付けをしていますので、それを利用した書き方にしましょう。
この時点でuserのオブジェクトはlogin_userに格納されていると思うので、
`login_user.task`でユーザー紐づくタスクは取得できるはずです。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/db/seeds.rb
> +  user = User.create!(name: "ユーザ#{i + 1}", password_digest: password_digest, salt: salt, email: "email#{i + 1}@example.com")
これはseedの作り方の指摘ではなくuser作成に関する指摘なのですが、事前に実施する処理が多すぎます。
毎回ユーザーを作成する前に、saltを用意してpasswordをhash化して、と実施していますが、
これらの処理はcallbackを利用しましょう。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/spec/models/users_spec.rb
> +        it { expect { FactoryBot.create(:user, email: 'test@example.com') }.to raise_error(ActiveRecord::RecordInvalid) }
これでもいいですが、他と同じようにcreateではなくbuildしたオブジェクトにバリデーションを実行するで良いでのは？

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/spec/models/users_spec.rb
> +      subject(:hash) { user.authenticate('password') }
このテストだと元のパスワードがわからないため、passwordという文字列が一致しているのかどうかがわかりません。
コードを読むことで、factory側で初期値として書いているpasswordと一致していることがわかりますが、
factory側の初期値を検証するようなテストは見通しが悪いので書かないようにしましょう。
テスト用データを作成する際、明示的に値を書くことで解消されるはずです。

2022-09-07 06:14 UTC, R-KazumaInazaki commented on myapp/spec/models/users_spec.rb
> +    subject(:salt_length) { User.create_salt.length }
やりたいことは理解できるのですが、これではlengthをテストしているように見えます。
subjectにlengthは含めないようにしてください。

2022-09-07 06:58 UTC, connect-yuma-nakamura commented on myapp/app/models/user.rb
> +  end
gemを使わないことが本ステップの条件であったため、bcryptの中でやっているであろうことを自作しました。
→ストレッチングもしようと思ったのですが割愛しました。
参考リンクは下記あたりです。
https://qiita.com/kenjiszk/items/d38e398bc120cf4bbd1c

2022-09-07 07:06 UTC, connect-yuma-nakamura commented on myapp/db/migrate/20220829071638_add_password_digest_to_users.rb
> +  end
1つのmigrationファイルにまとめました。

2022-09-07 07:07 UTC, connect-yuma-nakamura commented on myapp/db/migrate/20220830033331_add_index_to_users_password_digest.rb
> +  end
失礼しました。
上記対応とともに修正しました。

2022-09-07 07:11 UTC, connect-yuma-nakamura commented on myapp/app/helpers/sessions_helper.rb
> +  def login(user)
> HelperはViewの中で利用するメソッドを用意する場所です。

承知しました。
ApplicationControllerへ移動しました。

2022-09-07 07:18 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
条件にuser_idも含めるよう修正しました。

2022-09-07 07:25 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    task_params
おっしゃる通り、メソッドの役割がぶれていたのでシンプルにしました。
→paramsのpermitのみ

2022-09-07 07:39 UTC, connect-yuma-nakamura commented on myapp/app/helpers/sessions_helper.rb
> +  end
ログイン周りの処理を整理しました。
bcryptは本ステップで導入してはいけないと勘違いしていました。
一旦、使用しない方向で修正しています。

2022-09-07 07:44 UTC, connect-yuma-nakamura commented on myapp/app/helpers/sessions_helper.rb
> +    cookies[:login_token] = token
いえ、特に検討はしていないです。
→強いていうなら研修なのでデータを見ながらやりたいな程度です。
実際このようなデータは確かにsessionの方に詰めるものだと思いますので修正しました。

2022-09-07 07:45 UTC, connect-yuma-nakamura commented on myapp/app/helpers/sessions_helper.rb
> +    redirect_to(login_path) if !login?
ログイン周りの処理を整理する中でこちらの処理変更となりました。
今後はunlessを使用します。

2022-09-07 07:51 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = Task.where_user_id(login_user.id).where_title(params[:title]).where_status(params[:status]).order('tasks.created_at desc').page(params[:page])
where_user_idを削除し、login_user.tasksを利用するよう修正しました。

2022-09-07 08:54 UTC, connect-yuma-nakamura commented on myapp/db/seeds.rb
> +  user = User.create!(name: "ユーザ#{i + 1}", password_digest: password_digest, salt: salt, email: "email#{i + 1}@example.com")
Userのパスワード関連処理をcallbackへ移動させました。
ちょっと気持ち悪さが残っている（saltをcallback内で設定しているが、事前に設定されても意味がなくなる、など）のでよりよい書き方があれば教えていただけると助かります。

2022-09-07 08:58 UTC, connect-yuma-nakamura commented on myapp/spec/models/users_spec.rb
> +        it { expect { FactoryBot.create(:user, email: 'test@example.com') }.to raise_error(ActiveRecord::RecordInvalid) }
私の認識ですが、buildはオブジェクトを作成し、DBに登録する前の状態だと思っています。
User1をDBに登録→User2をDBに登録→emailが重複し、エラーが発生
の流れでないとテストできないかなと思いcreateにしました。
→実際最初buildにしていたのですが、エラーが発生せず正常にDBに登録されていました。

こちらを回避するよい法法がありましたらお教えいただきたいです。

2022-09-07 09:01 UTC, connect-yuma-nakamura commented on myapp/spec/models/users_spec.rb
> +      subject(:hash) { user.authenticate('password') }
User のmodel spec、またTask のsystem spec で登録しているUserのパスワードを明示的に設定するよう修正しました。

2022-09-07 09:12 UTC, connect-yuma-nakamura commented on myapp/spec/models/users_spec.rb
> +    subject(:salt_length) { User.create_salt.length }
lengthを含めないよう修正しました。

2022-09-08 06:49 UTC, R-KazumaInazaki commented on myapp/db/seeds.rb
> +  user = User.create!(name: "ユーザ#{i + 1}", password_digest: password_digest, salt: salt, email: "email#{i + 1}@example.com")
中村さんの実装では`password + salt`をHash化し、DBに`Hash化したpassword`と`salt`を個別に保存しますが、
bcryptの場合、`password`をHash化し、DBには`salt + Hash化したpassword`を1項目のみ保存します。
bcryptでは常にsaltの文字数が一定となる（configから変更可能）ため、認証時はpassword_digestを分割するだけ、という割とシンプルな実装になっていますね。

とはいえ今回はこのままで問題ないと思います！

2022-09-08 06:50 UTC, R-KazumaInazaki commented on myapp/db/seeds.rb
> +  user = User.create!(name: "ユーザ#{i + 1}", password_digest: password_digest, salt: salt, email: "email#{i + 1}@example.com")
中村さんの実装では`password + salt`をHash化し、DBに`Hash化したpassword`と`salt`を個別に保存しますが、
bcryptの場合、`password`をHash化し、DBには`salt + Hash化したpassword`を1項目のみ保存します。
bcryptでは常にsaltの文字数が一定となる（configから変更可能）ため、認証時はpassword_digestを分割するだけ、という割とシンプルな実装になっていますね。

とはいえ今回はこのままで問題ないと思います！

2022-09-08 07:07 UTC, R-KazumaInazaki commented on myapp/spec/models/users_spec.rb
> +        it { expect { FactoryBot.create(:user, email: 'test@example.com') }.to raise_error(ActiveRecord::RecordInvalid) }
もしかしたら、subjectとlet!でuserという変数名が被っているのが原因かもしれません。
このテストではUser1をlet!で作成していますが、beforeでも問題なく動くはずです。
その上で、itは他のテストと同様の書き方ができると思います。
```suggestion
        it { is_expected.to be_invalid }
```

2022-09-08 07:12 UTC, R-KazumaInazaki commented on myapp/app/controllers/application_controller.rb
> +    user.update(login_token: User.encrypt_login_token(token))
sessionであればユーザーから中身が見えないと思いますので、
わざわざtokenを生成して保存せずとも、user_idなどで代用できそうな気がします。（世の中的にもそういった実装が多いので、特に問題ないはず・・・？）

2022-09-08 07:19 UTC, R-KazumaInazaki commented on myapp/app/controllers/application_controller.rb
> +    User.find_by(login_token: User.encrypt_login_token(session[:login_token]))
修正前の`@login_user ||=`の形で良いと思います。
```suggestion
    @login_user ||= User.find_by(login_token: User.encrypt_login_token(session[:login_token]))
```
`||=`は、左辺がnilであれば右辺を実行し、返り値を左辺に代入する処理を行います。
この形のメソッドは比較的よく利用します。
login_userのようにDBへのアクセスが必要だが何度も呼び出す必要のあるメソッドは、
`インスタンス変数 ||=`をキャッシュに見立てることで、アクセス回数を減らすことができるからです。

2022-09-08 07:25 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.new(create_params)
login_userに紐づくtaskを作成するとき、`login_user.tasks.new`を実行することで、
user_idにlogin_userのidが入った状態のオブジェクトが生成されると思うので、使ってみてください。

2022-09-08 07:28 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find_by(id: params[:id], user_id: login_user.id)
ここも関連付けを利用すると良いと思います。
```suggestion
    @task = login_user.tasks.find(params[:id])
```

2022-09-08 07:32 UTC, R-KazumaInazaki commented on myapp/db/seeds.rb
> +  user = User.create!(name: "ユーザ#{i + 1}", password_digest: "test#{i + 1}", email: "email#{i + 1}@example.com")
password_digest、という項目に生のパスワードを入力しているのは見栄えがあまりよくないですね・・・
このようなとき、仮想のattributeをモデルに定義すると良いと思います。
attr_accessorで調べると出てくるはずですので使ってみてください。

2022-09-08 07:33 UTC, R-KazumaInazaki requested changes
コメントに返信と、新しく指摘をしておりますのでご確認ください。

2022-09-09 00:11 UTC, connect-yuma-nakamura commented on myapp/db/seeds.rb
> +  user = User.create!(name: "ユーザ#{i + 1}", password_digest: password_digest, salt: salt, email: "email#{i + 1}@example.com")
saltは各データ毎に異なる仕様のようなので、本来自作するのであればsaltを管理するテーブルを別で作成して管理するように思いました。
一旦自作で作成してしまったため、このままとさせていただきます。

2022-09-09 00:34 UTC, connect-yuma-nakamura commented on myapp/app/controllers/application_controller.rb
> +    user.update(login_token: User.encrypt_login_token(token))
指摘内容について把握いたしました。
その上で、カラムからの修正になるのでこのままでいかせてもらえると助かります。
今後他メンバーに対してレクチャーする際はtokenまでは不要というところでレクチャーします。

2022-09-09 01:28 UTC, connect-yuma-nakamura commented on myapp/app/controllers/application_controller.rb
> +    User.find_by(login_token: User.encrypt_login_token(session[:login_token]))
DBへのアクセス数が減るよう修正しました。

2022-09-09 01:29 UTC, connect-yuma-nakamura commented on myapp/spec/models/users_spec.rb
> +        it { expect { FactoryBot.create(:user, email: 'test@example.com') }.to raise_error(ActiveRecord::RecordInvalid) }
buildへ修正しました。
ただ、before内で事前にデータを登録するところはcreateで実際にDBに保存する必要があったためそちらはcreateにしています。

2022-09-09 01:32 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.new(create_params)
ありがとうございます！
スッキリとした実装にすることができました。

2022-09-09 01:39 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find_by(id: params[:id], user_id: login_user.id)
ありがとうございます！
それを使う頭がまだ定着していないので、レビューをする中で落とし込んでいきます。

2022-09-09 01:49 UTC, connect-yuma-nakamura commented on myapp/db/seeds.rb
> +  user = User.create!(name: "ユーザ#{i + 1}", password_digest: "test#{i + 1}", email: "email#{i + 1}@example.com")
attr_accessorでpasswordを定義し、そちらを元に作成するよう修正しました。

2022-09-09 02:21 UTC, R-KazumaInazaki commented on myapp/db/seeds.rb
> +User.destroy_all
研修なので修正しなくて良いですが、知識として。
根本的に変更する必要ありそうですが、これだとDocker起動するたびに全てのデータが消えてしまいます。

railsがdefaultで用意しているseedの欠点が、seedを実行するたびに毎回データを作成してしまうことです。
現場ではseed-fuというgemを利用していまして、すでにデータがあれば作成しない、といったことが実現できます。

2022-09-09 02:22 UTC, R-KazumaInazaki approved these changes
LGTM！
補足で１点だけコメントしていますが、読むだけでOKです！

2022-09-09 02:36 UTC, merged