STEP13: ステータスを追加して、検索できるようにしよう
Fablic/training pull request #1397
Opened 2022-09-07 02:26 UTC by kohei-matsubara

■要件
### ステップ13: ステータスを追加して、検索できるようにしよう

- ステータス（未着手・着手中・完了）を追加してみよう
  - 【オプション要件】初学者ではない場合はstateを管理するGemを導入しても構いません
- 一覧画面でタイトルとステータスで検索ができるようにしよう
  - 【オプション要件】初学者ではない場合はransackなどの検索の実装を便利にするGemを導入しても構いません
- 絞り込んだ際、ログを見て発行されるSQLの変化を確認してみましょう
  - 以降のステップでも必要に応じて確認する癖をつけましょう
- 検索インデックスを貼りましょう
- 検索に対してmodel specを追加してみよう（system specも拡充しておきましょう）

■対応内容
- ステータス追加
- 検索機能追加
- tasksへインデックス追加
- specの追加

■確認手順
【検索機能確認】
1. 以下ページへアクセス

``` http://localhost:3001 ```

2. 既に存在するタスク名を押下し、詳細ページを開く
<img width="1424" alt="スクリーンショット 2022-09-06 15 04 24" src="https://user-images.githubusercontent.com/110374166/188773257-161e56c2-8f19-40a7-a32c-84150a62ebc7.png">

3. 選択したタスクのステータスを確認し、編集ボタンを押下
<img width="1419" alt="スクリーンショット 2022-09-06 15 08 58" src="https://user-images.githubusercontent.com/110374166/188773400-f5766a3f-58fc-401d-9610-aa6627b5acaa.png">

4. ステータスを別のステータスに変更する
<img width="1422" alt="スクリーンショット 2022-09-06 15 09 21" src="https://user-images.githubusercontent.com/110374166/188773431-fae87cd0-9fde-495c-9e8a-d6316c6beb62.png">

5. 再度、同じタスクを開くと選択したステータスに変化していることを確認
<img width="1424" alt="スクリーンショット 2022-09-06 15 09 35" src="https://user-images.githubusercontent.com/110374166/188773604-fb2ef5ad-29a6-4d05-b265-ffec03eedcc5.png">

6. 一覧画面の検索バーで変更後のステータスを指定し、検索すると一致するタスクのみ表示されることを確認
<img width="1291" alt="スクリーンショット 2022-09-07 11 15 56" src="https://user-images.githubusercontent.com/110374166/188773856-974444bc-a39f-4f3c-bff9-e925b1eed0f9.png">

【検索機能テスト】

1. 以下コマンド実行

``` docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb ```
``` docker-compose exec api bundle exec rspec -f d spec/models/tasks_spec.rb ```

2022-09-07 05:33 UTC, connect-yuma-nakamura requested changes
中村が指摘された内容と同様のものが散見されるため、全体的に確認、修正してから再度レビュー依頼を出してください。

2022-09-07 05:33 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +      sql += " status = '#{status}' " if status.present?
SQLインジェクションに弱いソースとなっています。
ActiveRecordのwhereを使用するようにしてください。

2022-09-07 06:36 UTC, kohei-matsubara commented on myapp/config/locales/ja.yml
>        task: タスク
日本語対応する辞書を増やしました。

2022-09-07 06:36 UTC, kohei-matsubara commented on myapp/app/models/task.rb
> +      sql += " status = '#{status}' " if status.present?
whereで実装するように修正しました。

2022-09-07 09:33 UTC, connect-yuma-nakamura requested changes
レビューしました。
指摘項目の確認をお願いします。

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    end
where_titleなどの処理上、ここのif文は不要です。
```@tasks = Task.where_title(params[:title]).where_status(params[:status]).order('tasks.created_at desc')```のみで正常に動くかと思います。

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +  end
htmlのformを変更しなければ、元のソースでも動きそうな気がします。
試してみてください。

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
showと同様。

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/_form.html.erb
> +  <div style="color: red" class='error_list'>
このクラスは何のためでしょう？

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/edit.html.erb
> +<div name='header'>
headerは元々なかったので追加する必要なないのでは？
他画面も同様。

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/edit.html.erb
> +<div name='content'>
contentは元々なかったので追加しなくてもいいのでは？
他画面も同様。

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/edit.html.erb
> +<div name='footer'>
footerは元々なかったので追加しなくてもいいのでは？
他画面も同様。

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/index.html.erb
> -<h1>タスク一覧</h1>
修正量が多すぎる気がします。
元の処理の原型がないように見えます。

2022-09-07 09:33 UTC, connect-yuma-nakamura commented on myapp/db/migrate/20220830014947_add_index_to_tasks_status.rb
> +    add_index :tasks, :status
これくらいの内容であれば、1つのmigrationファイルにまとめてください。

2022-09-08 00:43 UTC, kohei-matsubara commented on myapp/app/views/tasks/index.html.erb
> -<h1>タスク一覧</h1>
修正箇所を再度見直し、必要最低限に変更しました

2022-09-08 00:43 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    end
正常に動くことが確認できたので、if文を削除しました。

2022-09-08 00:44 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +  end
元のソースで問題ないことが確認できたので修正しました。

2022-09-08 00:44 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
show同様動作確認できたので修正しました

2022-09-08 01:22 UTC, kohei-matsubara commented on myapp/db/migrate/20220830014947_add_index_to_tasks_status.rb
> +    add_index :tasks, :status
一つのmigrationFileにまとめました。

2022-09-08 01:22 UTC, kohei-matsubara commented on myapp/app/views/tasks/edit.html.erb
> +<div name='header'>
作法として必要なのかと思い、追加していました。
削除しました。

2022-09-08 01:23 UTC, kohei-matsubara commented on myapp/app/views/tasks/edit.html.erb
> +<div name='content'>
作法として必要なのかと思い、追加していました。
削除しました。

2022-09-08 01:23 UTC, kohei-matsubara commented on myapp/app/views/tasks/edit.html.erb
> +<div name='footer'>
作法として必要なのかと思い、追加していました。
削除しました。

2022-09-08 01:27 UTC, kohei-matsubara commented on myapp/app/views/tasks/_form.html.erb
> +  <div style="color: red" class='error_list'>
不要なclass属性であったため削除しました。

2022-09-08 01:37 UTC, connect-yuma-nakamura approved these changes
修正内容がスッキリしました。
LGTM！

2022-09-08 01:44 UTC, merged