ステップ13: ステータスを追加して、検索できるようにしよう
Fablic/training pull request #1401
Opened 2022-09-07 06:33 UTC by miu-tsuzuki

■要件
### ステップ13: ステータスを追加して、検索できるようにしよう

- ステータス（未着手・着手中・完了）を追加してみよう
  - 【オプション要件】初学者ではない場合はstateを管理するGemを導入しても構いません
- 一覧画面でタイトルとステータスで検索ができるようにしよう
  - 【オプション要件】初学者ではない場合はransackなどの検索の実装を便利にするGemを導入しても構いません
- 絞り込んだ際、ログを見て発行されるSQLの変化を確認してみましょう
  - 以降のステップでも必要に応じて確認する癖をつけましょう
- 検索インデックスを貼りましょう
- 検索に対してmodel specを追加してみよう（system specも拡充しておきましょう）

■対応内容
- Taskにステータス追加
- 検索機能追加
- Modelのspec追加

■確認手順
・事前準備
 　下記コマンドでDockerを起動 
　docker-compose up --build 
・検索機能
　 下記URLでタスク一覧画面を開く
 　[http://localhost:3001/ ](http://localhost:3001/%E2%80%A8)
　検索エリアのタスク名に入力し、ステータスを選択して検索ボタンを押下する
　
・モデルテスト
 　下記コマンドを実行
 　docker-compose exec api bundle exec rspec -f d spec/models/task_spec.rb 
・システムテスト
　下記コマンドを実行
　docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb

2022-09-07 06:40 UTC, connect-yuma-nakamura requested changes
指摘しましたので確認をお願いします。

2022-09-07 06:40 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/show.html.erb
> +<p>Status</p>
他項目と同様辞書から取得するようにしてください

2022-09-07 06:40 UTC, connect-yuma-nakamura commented on myapp/config/locales/ja.yml
> +    created_at: '作成日'
``` created_at ```未使用？

2022-09-08 05:38 UTC, connect-yuma-nakamura requested changes
指摘していますので確認をお願いします、

2022-09-08 05:41 UTC, miu-tsuzuki commented on myapp/app/views/tasks/show.html.erb
> +<p>Status</p>
辞書から取得するよう修正しました。

2022-09-08 05:49 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-09-08 05:54 UTC, merged