STEP16: 複数人で利用できるようにしよう
Fablic/training pull request #1409
Opened 2022-09-08 08:52 UTC by kohei-matsubara

■要件

### ステップ16: 複数人で利用できるようにしよう（ユーザの導入）

- ユーザモデルを作成してみましょう
- 最初のユーザをseedで作成してみましょう
- ユーザとタスクが紐づくようにしましょう
  - 関連に対してインデックスを貼りましょう
  - N+1問題を回避するための仕組みを取り入れましょう
    - N+1クエリを自動検出するbulletを導入してみましょう（[参考記事](https://fablic.qiita.com/craftcat/items/b181b67ddae0c7d0702a)）

■対応内容
- Users追加
- Task登録時に担当者選択項目追加
- bullet導入

■確認手順
1. 以下ページへアクセス

``` http://localhost:3001 ```

2. タスク作成

- タスク作成画面にて担当者が選択できること

<img width="382" alt="スクリーンショット 2022-09-08 16 50 11" src="https://user-images.githubusercontent.com/110374166/189066391-b5e12399-307e-4031-ba0b-0c8928f41756.png">

<img width="426" alt="スクリーンショット 2022-09-08 16 50 26" src="https://user-images.githubusercontent.com/110374166/189066510-0e52b9af-155f-43ed-b5fe-45e15544e8e5.png">

3. タスク名を押下し、タスク詳細画面へ遷移

- タスク詳細画面に担当者が表示されていること

<img width="360" alt="スクリーンショット 2022-09-08 16 50 38" src="https://user-images.githubusercontent.com/110374166/189066539-2d52413e-193c-4d51-acd4-22724f3c1eba.png">

4. 詳細画面の編集ボタンを押下し、編集画面を表示

- タスク編集画面にて担当者の選択ができること
- 担当者の編集ができること

別ユーザを選択
<img width="394" alt="スクリーンショット 2022-09-08 16 50 56" src="https://user-images.githubusercontent.com/110374166/189066788-1b1cc0bd-f620-45c3-8ed5-e21405023e83.png">

担当者が変わったことを確認
<img width="356" alt="スクリーンショット 2022-09-08 16 51 07" src="https://user-images.githubusercontent.com/110374166/189066861-9179dfd5-6d45-4428-baf9-81682f25d019.png">

5. spec実行

``` docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb ```

2022-09-08 08:58 UTC, kohei-matsubara commented on myapp/config/application.rb
> +    config.i18n.default_locale = :ja
日本語辞書を参照するための行が消えていたので戻しました。

2022-09-08 09:24 UTC, connect-yuma-nakamura requested changes
指摘項目がありますので確認をお願いします！

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/_form.html.erb
> +    <%= f.label :ユーザ %>
私の知識不足なのですが、:{カタカナ}でいくのは標準的なやり方なのでしょうか？
→rubyは変数名などに日本語使えるのですが、使うべきではないかと。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/config/application.rb
> +    config.i18n.default_locale = :ja
日本語化は前のステップでやっているのですが、こちら今定義したのでしょうか？

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/config/environments/development.rb
> +  end
恐らく中村のソースを参考にしたのだと思うのですが、それぞれの設定については理解をお願いします。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/db/seeds.rb
> +  end
```end```のインデントがおかしいです。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/spec/factories/user.rb
> +  end
インデントがおかしいです。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_1) { FactoryBot.create(:task, title: '最初のタスク', description: '最初のタスクを実施する', status: '1', label: 1) }
statusがテストによってコード値だったり```not_started```だったり違うのが気になります。
Task.statuses[:not_started]などに統一できないでしょうか？

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_content '0'
```0```との一致は表示されていることの確認ではないです。
→内部の値が```0```になっていて、そちらに紐づいてOKになっているのだと思われます。
全体的に見直しお願いします。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_five) { FactoryBot.create(:task) }
どこからも参照していない系のデータ（準備だけをしたいデータ）はletではなくbeforeでcreateだけやりましょう。
全体的に修正をお願いします。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
>            expect { click_button 'submit' }.to change(Task, :count).by(1)
件数だけでなく、登録されたデータが想定通りかのテストも書きましょう。
→find_byでinput_valuesの値を条件とし、取得できればOKという内容でよいです。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
>    describe '編集機能' do
ユーザーを選択する機能を追加していると思うので、ユーザー項目が更新されているテストを追加しましょう。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_content "タイトルを入力してください"
ここら辺の修正は前ステップの修正漏れだと思うので対応内容に記載しましょう。

2022-09-08 09:24 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +            description: '新規作成のテストを書く2'
登録機能にもユーザーの選択項目を追加していると思うので、明確に何を選択するかを設定しましょう。

2022-09-08 09:27 UTC, kohei-matsubara commented on myapp/config/application.rb
> +    config.i18n.default_locale = :ja
上記に記載したとおり、どこかのタイミングで消えてしまっていたので、追加し直しました。

2022-09-08 09:28 UTC, kohei-matsubara commented on myapp/db/seeds.rb
> +  end
インデントのずれを修正しました。

2022-09-08 09:29 UTC, kohei-matsubara commented on myapp/spec/factories/user.rb
> +  end
インデントを修正しました。

2022-09-08 09:35 UTC, kohei-matsubara commented on myapp/app/views/tasks/_form.html.erb
> +    <%= f.label :ユーザ %>
全て英語で対応するよう修正しました。

2022-09-08 09:47 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_five) { FactoryBot.create(:task) }
beforeでcreateだけするよう修正しました。

2022-09-08 09:51 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> -          expect(page).to have_content "Title is too long (maximum is 30 characters)"
前回の修正漏れがあったので、STEP16で合わせて修正しました。

2022-09-08 09:51 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> -          expect(page).to have_content "Description can't be blank"
前回の修正漏れがあったので、STEP16で合わせて修正しました。

2022-09-08 09:51 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> -          expect(page).to have_content "Description is too long (maximum is 100 characters)"
前回の修正漏れがあったので、STEP16で合わせて修正しました。

2022-09-08 09:52 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_content "タイトルを入力してください"
対応内容に記載しました。

2022-09-08 09:55 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_1) { FactoryBot.create(:task, title: '最初のタスク', description: '最初のタスクを実施する', status: '1', label: 1) }
0やnot_startedが存在していたため、全てnot_startedに統一しました。

2022-09-08 09:56 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_content '0'
実際に表示されているのは'未着手'だったので修正しました。

2022-09-09 00:05 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
>            expect { click_button 'submit' }.to change(Task, :count).by(1)
一つ下のテストで入力した値と一致するものが存在するかのテストを行っていました。

2022-09-09 00:41 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +            description: '新規作成のテストを書く2'
何を選択するかは、input_valuesの上のユーザを指定するように指定していました。

2022-09-09 02:00 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
>    describe '編集機能' do
ユーザ項目を更新するテストを追加しました。

2022-09-09 02:32 UTC, kohei-matsubara commented on myapp/config/environments/development.rb
> +  end
Bulletを調査し、それぞれが何を意味しているのか理解しました。
また、実際にJavaScriptでアラートが表示されることも確認しました。

2022-09-09 06:09 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-09-09 08:00 UTC, merged