ステップ20: タスクにラベルをつけられるようにしよう
Fablic/training pull request #1410
Opened 2022-09-09 05:25 UTC by connect-yuma-nakamura

■要件
### ステップ20: タスクにラベルをつけられるようにしよう

- タスクに複数のラベルをつけられるようにしてみましょう
- つけたラベルで検索できるようにしてみましょう

■対応内容
- 複数ラベルをつけられるよう修正
- いづれかのラベルで検索されるよう修正

■確認手順
【画面】
1. 以下ページへアクセス
```http://localhost:3001```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/189276317-51d4ed79-84b8-45e4-9103-dd23abd92980.png">

2. ```2```を入力して検索ボタン押下

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/189276382-1cc432a8-d383-4141-bd46-b2da1902eb1c.png">

- ラベル名に2がついたタスクのみ検索されること

3. タスク作成画面にて複数のラベル名設定し、作成

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/189276658-2e812390-89d1-4573-9043-40dd6d12f875.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/189276685-52595554-a321-4d35-bead-9a08af624d9a.png">

4. タスク編集画面にてラベル名を編集

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/189276772-921f083a-785e-41e5-9418-58a1ebc77a55.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/189276794-4e53f222-40b9-45f2-b7a0-fdd6088a80ae.png">

【spec】
```docker-compose exec api bundle exec rspec -f d spec/models/labels_spec.rb```
```docker-compose exec api bundle exec rspec -f d spec/models/tasks_spec.rb```
```docker-compose exec api bundle exec rspec -f d spec/models/users_spec.rb```
```docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb```

2022-09-09 08:05 UTC, R-KazumaInazaki requested changes
レビューしましたのでコメント確認お願いします。

また、ラベルの設計について見直して欲しいです。
現状、タスクにラベルが紐づく形となっていますが、
例えばタスクAでつけたラベルをタスクBでも使いたい時、
表面上は同じ名前ですが、データとしては複数作られてしまいます。
仕様とするにしても、どこかで不整合が出そうなので見直したほうが良さそうです。

また、タスク作成時にも別のフォームに同じ名前のラベルを入力すると、別のレコードとして作られてしまいます。同じ名前のラベルがつくのも不自然な気がしますので、バリデーションなどで対応してください。

2022-09-09 08:05 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = Task.where(id: @tasks.map { |t| t.id }).order('tasks.created_at desc').page(params[:page])
whereやorderなどのSQLに関するメソッドは、チェインすることで自動的にSQLを生成します。
このようにオブジェクトを切ってしまうと、クエリも分かれるのでその利点がなくなってしまいます。
また、`@tasks`を上書きしているので、eager_loadした意味がなくなっています。

2022-09-09 08:05 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_form.html.erb
> +<% if @task_form.error_messages.present? && @task_form.error_messages.size > 0 %>
any?から変更した理由が知りたいです。
present?がtrueを返す時点で、sizeは0より大きくなるのでは？

2022-09-09 08:05 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/show.html.erb
> +  <% if @label5.present? %><p><%= @label5 %></p><% end %>
一覧画面ではループで表示していますが、処理の仕方を変えた理由はありますでしょうか？

2022-09-09 08:05 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220831024133_create_labels.rb
> +      t.integer :task_id, null: false
関連付けに使うカラムには`t.reference`を利用しましょう。

2022-09-09 08:05 UTC, R-KazumaInazaki commented on myapp/app/forms/task_form.rb
> +class TaskForm
このクラスを作るに至った経緯や意図を教えていただけるとレビューがしやすいです。

2022-09-09 08:05 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220831024133_create_labels.rb
> +      t.string :name, limit: 64, null: false, default: 'not setting'
defaultの値が使われることはありますか？

2022-09-09 08:05 UTC, R-KazumaInazaki commented on myapp/db/seeds.rb
> +5.times do |i|
seedではアプリケーションを動かすのに必要な、最低限のデータだけを作るようにしてください。
例えばタスクやラベルは後から作成すれば良いので、ここで作成するのは不適切です。

2022-09-13 02:31 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = Task.where(id: @tasks.map { |t| t.id }).order('tasks.created_at desc').page(params[:page])
１つの処理にまとめました。

2022-09-13 02:34 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/_form.html.erb
> +<% if @task_form.error_messages.present? && @task_form.error_messages.size > 0 %>
anyで問題なく動作したため修正しました。
→formを実装する中でanyでうまく動作しないタイミングがあり、その修正がそのままとなっていました。

2022-09-13 02:34 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/show.html.erb
> +  <% if @label5.present? %><p><%= @label5 %></p><% end %>
特に意図はないため、ループで表示するよう修正しました。

2022-09-13 02:42 UTC, connect-yuma-nakamura commented on myapp/app/forms/task_form.rb
> +class TaskForm
Task作成時にLabelを5つまで付与できる仕様としました。
そうなると、画面とModelが不一致となるためその不一致をカバーするためにFormObjectを用意しました。

2022-09-13 02:42 UTC, connect-yuma-nakamura commented on myapp/db/migrate/20220831024133_create_labels.rb
> +      t.string :name, limit: 64, null: false, default: 'not setting'
ないため、削除しました。

2022-09-13 02:43 UTC, connect-yuma-nakamura commented on myapp/db/seeds.rb
> +5.times do |i|
ユーザーのみ作成するよう修正しました。

2022-09-13 02:46 UTC, connect-yuma-nakamura commented on myapp/db/migrate/20220831024133_create_labels.rb
> +      t.integer :task_id, null: false
承知しました。修正しました！

2022-09-13 12:04 UTC, R-KazumaInazaki requested changes
TaskFormクラスを中心に再度レビューしました。
ご確認お願いいたします。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/forms/task_form.rb
> +class TaskForm
Railsとしては、このような仮想モデルを作成する時もありますが、
中間テーブルがひとつあるくらいのボリュームであれば、ControllerとModelに処理を記載することが大半です。
また、このような仮想モデルは拡張性が低く、例えばタスクに紐づくラベルを５つに増やした時、修正する量がとても多いため、頻繁に改修される画面周りではあまり使用されません。
なので、仮想モデルを作るのではなく、ControllerやModel側に実装するようにお願いいたします。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/forms/task_form.rb
> +    self.label5 = task.labels[4].id if task.labels.present? && task.labels.size > 4
ラベルの存在チェックを行なってからセットする処理が頻繁に出てきますが、ループ処理では実装できないでしょうか？
ラベルが５個まで設定できる、という仕様が変わった場合、現状だと改修箇所が多すぎます。
この箇所でいえば`task.labels`をループで処理することで、if文なしでも実現できそうです。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = login_user.tasks.eager_load(:labels).eager_load(:task_labels).where(id: login_user.tasks.get_ids_by_user(params[:title], params[:label], params[:status])).order('tasks.created_at desc').
おそらく中間テーブルのtask_labelsは、labelsをeager_loadすればキャッシュされるので、呼び出さなくても良いはずです。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/forms/task_form.rb
> +  def save
メソッド名のsaveやupdateですが、ActiveRecordのメソッドをオーバーライドするでもなくただ寄せるだけにしてしまうと、思わぬ不具合やミスリーディングにつながります。
例えばsaveですが、受け取ったオブジェクトによって内部でcreateかupdateを実行するので、メソッドだけを見た時にupdateと役割同じでは？となってしまいます。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/forms/task_form.rb
> +        @task.update!(title: self.title, content: self.content, status: self.status, user_id: self.user_id)
saveメソッドの差異として、新規オブジェクトを生成するか、既存オブジェクトを取得するかの違いがあると思います。
この時、`find_or_initialize_by`というメソッドを利用すると、ひとつにまとめることが可能です。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/forms/task_form.rb
> +        TaskLabel.all.where(task_id: @task.id).destroy_all
編集画面で何も値を変えなかった場合でも、中間テーブルの削除と作成が必ず行われてしまいます。
すでにある場合はそのレコードを利用するようにして、DBの更新頻度を下げるようにしてください。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/forms/task_form.rb
> +        @task_labels.push(TaskLabel.new(task_id: @task.id, label_id: self.label1)) if self.label1.present?
一度newで作成した後、後からループで作成するのは少し冗長に見えます。初めからループで作成することは可能でしょうか。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  scope :get_ids_by_user, -> (title, label, status) { eager_load(:labels).where_title(title).where_status(status).where_label(label).select('tasks.id') }
`get_ids_by_user`スコープ名と実施内容に差異があります。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/views/tasks/_form.html.erb
> +  <%= f.collection_select(:label1,  Label.all, :id, :name, { include_blank: '未設定' }) %>
この処理も、フォームの数（今回であれば5）を定数としてモデルなどに定義し、その定数を用いてループ処理をすれば、改修コストが減ると思います。

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/spec/system/labels_spec.rb
> +          expect(Label.find_by(name: input_values[:name])).to be_nil
全体的に、expectの中でfindしている処理が目立ちします。
letで事前に定義しているはずなので、そのオブジェクトを使うようにしてください。

また、例えばこのテストの場合、画面側では違うオブジェクトを取得し更新しているので、一度letで定義したオブジェクトは最新の情報にする必要があります。
そのときはreloadメソッドが便利です。
```suggestion
          expect(label.reload.name).not_to eq input_values[:name]
```

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        end
タスクに紐づくラベルを作るとき、必ずこの２行を記載する必要があります。
この時、FactoryBotでtraitを利用すると便利です。
以下の記事のtrait部分が参考になると思います。
https://t1gerk1ngd0m.hatenablog.com/entry/2019/08/24/233047

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/models/task.rb
> +  scope :where_label, -> (label) { where('labels.id = ?', "#{label}") if label.present? }
引数はidのはずですが、これではオブジェクトを受け取るように見えます。
また、異なるモデルの検索をするときは以下のように書くと良いです。
```suggestion
  scope :where_label, -> (label_id) { where(labels: { id: label_id }) if label_id.present? }
```

2022-09-13 12:04 UTC, R-KazumaInazaki commented on myapp/app/forms/task_form.rb
> +        @task_labels.each { |task_label| !task_label.save! }
中間テーブルは、意図的に保存せずともRails側に任せることが可能です。
以下の記事を参考にしてください。
https://qiita.com/harukioo/items/7976775c15280d259d38

2022-09-16 08:23 UTC, connect-yuma-nakamura commented on myapp/app/forms/task_form.rb
> +class TaskForm
TaskFormを削除しました。

2022-09-16 08:24 UTC, connect-yuma-nakamura commented on myapp/app/forms/task_form.rb
> +    self.label5 = task.labels[4].id if task.labels.present? && task.labels.size > 4
仮装モデルは作成しない方が良いとのこと把握しました。
TaskFormを削除しました。

2022-09-16 08:26 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = login_user.tasks.eager_load(:labels).eager_load(:task_labels).where(id: login_user.tasks.get_ids_by_user(params[:title], params[:label], params[:status])).order('tasks.created_at desc').
bulletに怒られてしまうため、こちら記載しています。
記載なしでbulletにも怒られない方法ありましたらお教えいただけると助かります、、。

2022-09-16 08:27 UTC, connect-yuma-nakamura commented on myapp/app/forms/task_form.rb
> +  def save
指摘内容把握しました。
修正内容としては、task_form自体を削除しています。

2022-09-16 08:27 UTC, connect-yuma-nakamura commented on myapp/app/forms/task_form.rb
> +        @task.update!(title: self.title, content: self.content, status: self.status, user_id: self.user_id)
ありがとうございます。内容把握しました。
修正としてはtask_formを削除しました。

2022-09-16 08:28 UTC, connect-yuma-nakamura commented on myapp/app/forms/task_form.rb
> +        TaskLabel.all.where(task_id: @task.id).destroy_all
指摘内容把握しました。
他同様、task_form削除しました。

2022-09-16 08:28 UTC, connect-yuma-nakamura commented on myapp/app/forms/task_form.rb
> +        @task_labels.push(TaskLabel.new(task_id: @task.id, label_id: self.label1)) if self.label1.present?
指摘内容把握しました。
他同様、task_form削除しました。

2022-09-16 08:30 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +  scope :get_ids_by_user, -> (title, label, status) { eager_load(:labels).where_title(title).where_status(status).where_label(label).select('tasks.id') }
```get_ids```へ変更しました。

2022-09-16 08:30 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/_form.html.erb
> +  <%= f.collection_select(:label1,  Label.all, :id, :name, { include_blank: '未設定' }) %>
1つのプルダウンで複数選択する方法へ修正しました。

2022-09-16 08:42 UTC, connect-yuma-nakamura commented on myapp/spec/system/labels_spec.rb
> +          expect(Label.find_by(name: input_values[:name])).to be_nil
findでなく、reloadを使用するよう全体的に修正しました

2022-09-16 08:47 UTC, connect-yuma-nakamura commented on myapp/app/forms/task_form.rb
> +        @task_labels.each { |task_label| !task_label.save! }
ありがとうございます！そのように修正しました。

2022-09-16 09:07 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +  scope :where_label, -> (label) { where('labels.id = ?', "#{label}") if label.present? }
ありがとうございます！修正しました。

2022-09-16 09:28 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        end
ありがとうございます！
ですがすみません、私がtraitを使用して綺麗になるのがイメージできておらず、、。
結局意図して用意しているTaskとUserを紐付けるためには個別で作成する必要があるのではというところで思考が止まりました。
→適当な紐づきでいいのであればtraitを使用できるかと思います。
→もしくは、traitを使用しながらもtask_id、label_idは引数で渡して意図したものを設定可能であれば使用できるかと思ったのですが、探しきれずでした。

2022-09-20 03:06 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = login_user.tasks.eager_load(:labels).eager_load(:task_labels).where(id: login_user.tasks.get_ids_by_user(params[:title], params[:label], params[:status])).order('tasks.created_at desc').
eager_loadでもN+1のクエリは発行されてないように見えるのですが、Bulletには怒られてしまいますね。
どうやらeager_loadではなく、`preload(:labels)`だとtask_labels側の記載が不要になるようです。
使い方としても、この箇所のjoinはViewで表示するためなので、preloadの方が適切かもしれません。

Bulletからはincludesを使えと言われますが、違いについては以下の記事を参考にしてみてください。
https://qiita.com/iLLviA/items/a52bdec96c25ebdc8e4e#eager_load

2022-09-20 05:26 UTC, R-KazumaInazaki requested changes
再レビューしましたのでご確認お願いいたします。

2022-09-20 05:26 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220912014806_create_task_labels.rb
> +      t.references :label, index: true
`references`はindexを自動で貼るはずなので、オプションには不要ですね。
オプションで必要になるパターンとしては、ユニークなインデックスを貼りたい時などになると思います。
あと、現状だとnullが許可されているので、許可しない方が良さそうです。

2022-09-20 05:26 UTC, R-KazumaInazaki commented on myapp/spec/system/tasks_spec.rb
> +        end
参考が少々悪かったですね、、シンプルな場合は記事のような実装で良いのですが、
labelの名前を変えたいなど、traitに引数を渡したい場合はtransientを利用します。
```Ruby
FactoryBot.define do
  factory :task do
  # 途中省略

    trait :with_labels do
      transient do
        label_name { 'label' } # label_nameという引数とそのデフォルトの定義
      end

      after(:build) do | task, evaluator | 
        task.labels << build(:label, name: evaluator.label_name) # block引数のevaluatorからlabel_nameを取得可能
      end
    end
  end
end

# 補足
# << はtaskとlabelを紐づけると同時に、task_labelまで作成します。
# もしlabelがnewやbuildで生成したオブジェクトであれば、labelのcreateも行います。
```

そして、以下のように呼び出します。
```Ruby
FactoryBot.create(:task, :with_labels, label_name: 'label test')
```

もし複数のラベルを紐付けたい場合は、同じように引数を持たせることで実現できると思いますが、
一つのtraitにたくさんの機能をつけるより、
シンプルにラベルを作るtraitと、複数のラベルを作るtraitで分けた方がよさそうです。

こちらが参考です。
https://github.com/thoughtbot/factory_bot/issues/527

2022-09-20 06:17 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = login_user.tasks.eager_load(:labels).eager_load(:task_labels).where(id: login_user.tasks.get_ids_by_user(params[:title], params[:label], params[:status])).order('tasks.created_at desc').
ありがとうございます！
URL先も読ませていただきました。
eager_loadからpreloadへ変更しました。

2022-09-20 08:40 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        end
ありがとうございます！
transientを使用し、中間テーブルを自動的に作成するよう修正しました。

2022-09-20 08:52 UTC, connect-yuma-nakamura commented on myapp/db/migrate/20220912014806_create_task_labels.rb
> +      t.references :label, index: true
index貼られるの確認しました。
```index: true```は削除しました。

2022-09-21 00:14 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-09-26 05:22 UTC, merged