STEP17 ログイン/ログアウト機能を実装しよう
Fablic/training pull request #1425
Opened 2022-09-15 06:10 UTC by kohei-matsubara

■要件
### ステップ17: ログイン/ログアウト機能を実装しよう

- 追加のGemを使わず、自分で実装してみましょう
  - DeviseなどのGemを使わないことで、HTTPのCookieやRailsにおけるSessionなどの仕組みについて理解を深めることが目的です
  - また、一般的な認証についての理解を深めることも目的にしています（パスワードの取り扱いについてなど）
- ログイン画面を実装しましょう
- ログインしていない場合は、タスク管理のページに遷移できないようにしましょう
- 自分が作成したタスクだけを表示するようにしましょう
- ログアウト機能を実装しましょう

■対応内容
- ログイン/ログアウト機能追加
- 自分が作成したタスクのみ表示
- 上記対応に伴い、担当者設定項目削除

■確認手順
1. 以下ページへアクセス
``` http://localhost:3001 ```

- ログイン画面が表示されること

2. 以下情報を入力してログインボタンを押下
メールアドレス：sample12345@example.com
パスワード：password

<img width="418" alt="スクリーンショット 2022-09-15 9 27 24" src="https://user-images.githubusercontent.com/110374166/190285821-4de248a2-bb3d-4124-b69c-00bcf0a65743.png">

<img width="432" alt="スクリーンショット 2022-09-15 9 42 34" src="https://user-images.githubusercontent.com/110374166/190287186-6ce19fce-6bd6-41c4-9cde-dd91408d2e51.png">

- ログインできること

3. ログアウトボタンを押下

<img width="428" alt="スクリーンショット 2022-09-15 9 43 07" src="https://user-images.githubusercontent.com/110374166/190287238-3180cf48-a97b-49b2-89a1-8c54ee393e49.png">

- ログイン画面へ戻ること

4. 以下ページへアクセスできないこと
``` http://localhost:3001/tasks/new```
``` http://localhost:3001/tasks/1/edit```

2022-09-26 04:54 UTC, connect-yuma-nakamura requested changes
まだレビュー途中ですが、一部指摘したので確認をお願いします。

2022-09-26 04:54 UTC, connect-yuma-nakamura commented on myapp/Gemfile
> +gem 'bcrypt', '~> 3.1.7'
bcryptをコメントアウトしていますが、使用していないように見えます。

2022-09-26 04:54 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +  def show; end
以下確認してみてください！
自分のユーザー以外が作成したタスクのIDをURLへ直接打ち込んでも表示されず、エラーが発生するか。

2022-09-26 04:54 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @task = login_user.tasks.new(task_params)
ここは新規タスクなので他タスクを元にnewすると余計な情報がつきそう。
そのままでよいかと思います。

2022-09-26 05:04 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    @task = login_user.tasks.new(task_params)
元の状態に戻しました。

2022-09-26 05:14 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +  def show; end
表示されてしまうことが確認できたので、表示されないように修正しました。

2022-09-26 05:20 UTC, connect-yuma-nakamura requested changes
追加レビュー分です。
指摘しているので確認をお願いします。

2022-09-26 05:20 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    task_params = params.require(:task).permit(:title, :description, :label, :status)
labelが追加になっているのは今回の対応？

2022-09-26 05:20 UTC, connect-yuma-nakamura commented on myapp/app/helpers/application_helper.rb
> +    include SessionsHelper
SessionHelperには何も定義されていないが、未使用の場合この定義は不要

2022-09-26 05:20 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +  scope :where_user_id, -> (user_id) { where(user_id: user_id) if user_id.present? }
このscopeは未使用？

2022-09-26 05:20 UTC, connect-yuma-nakamura commented on myapp/spec/system/sessions_spec.rb
> +       let(:user) { FactoryBot.create(:user) }
インデントが異なる
また、ユーザー作成時はpasswordの設定が必要

2022-09-26 05:25 UTC, kohei-matsubara commented on myapp/app/models/task.rb
> +  scope :where_user_id, -> (user_id) { where(user_id: user_id) if user_id.present? }
scope :where_user_id, -> (user_id) { where(user_id: user_id) if user_id.present? }
どこでも使っていなかったため削除しました。

2022-09-26 05:25 UTC, kohei-matsubara commented on myapp/app/helpers/application_helper.rb
> +    include SessionsHelper
何も定義していないhelperを呼び出していたので削除しました、

2022-09-26 05:26 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    task_params = params.require(:task).permit(:title, :description, :label, :status)
今回の対応ではlabelは不要のため削除しました。

2022-09-26 10:00 UTC, kohei-matsubara commented on myapp/Gemfile
> +gem 'bcrypt', '~> 3.1.7'
使用していないためコメントアウトしました

2022-09-26 10:10 UTC, kohei-matsubara commented on myapp/spec/system/sessions_spec.rb
> +       let(:user) { FactoryBot.create(:user) }
インデント修正しました。
mた、passwordを設定する仕様に修正しました。

2022-09-27 01:07 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-09-27 01:30 UTC, merged