ステップ21: メンテナンス機能を作ろう
Fablic/training pull request #1430
Opened 2022-09-26 05:53 UTC by connect-yuma-nakamura

■要件
### ステップ21: メンテナンス機能を作ろう

- メンテナンスを開始／終了するバッチを作ってみましょう
- メンテナンス中にアクセスしたユーザはメンテナンスページにリダイレクトさせましょう
- 追加のGemを使わず、自分で実装してみましょう

■対応内容
- メンテナンス開始/終了バッチ作成
- メンテナンス中の場合に503エラーになるよう修正

■確認手順
1. タスク一覧画面表示

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/192201348-02b17837-fb2b-4766-9834-e8fed96f4c3f.png">

2. システム停止バッチ実行
``` docker-compose exec api rails runner Maintenance::Functions::StopSystem.execute ```

- タスク一覧画面を表示すると、503エラーとなること

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/192201628-c643b278-df29-42c4-b569-01dabb06c6bb.png">

以下コマンドで再度システム開始
``` docker-compose exec api rails runner Maintenance::Functions::StartSystem.execute ```

3. タスク作成機能停止バッチ実行
``` docker-compose exec api rails runner Maintenance::Functions::StopCreate.execute ```

- タスク作成画面を表示すると、503エラーとなること

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110370186/192202503-d184d133-5609-46bb-95d4-b1f72f9c8273.png">

2022-09-27 02:22 UTC, R-KazumaInazaki requested changes
レビューしましたのでご確認お願いいたします。

2022-09-27 02:22 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +  end
render処理は共通だと思うので、private methodなどに切り分けると良さそうです。

2022-09-27 02:22 UTC, R-KazumaInazaki commented on myapp/app/models/function.rb
> +  def self.is_started(id)
メソッド名の最後に`?`をつけてあげると、true or falseを返すということがわかりやすくなります。

2022-09-27 02:22 UTC, R-KazumaInazaki commented on myapp/db/migrate/20220906235803_create_functions.rb
> +      t.string :status, limit: 1, null: false, default: '1'
varchar型なのが気になります。
ステータスがON/OFFのみであれば、booleanで定義すると、enumなども不要になると思うので使ってみてください。

2022-09-27 02:22 UTC, R-KazumaInazaki commented on myapp/app/models/function.rb
> +    Function.statuses[Function.find(id).status] == Function.statuses[:started] ? true : false
`==`もbooleanを返すので、三項演算子の形にする意味がほぼないです。
statusカラムをbooleanにすることで、この判定処理も改善されると思います。

2022-09-27 02:22 UTC, R-KazumaInazaki commented on myapp/app/models/function.rb
> +  def self.is_started(id)
そもそもstartedは使ってない？もしステータスがON/OFFの2種類であれば、メソッドも１つでよさそうですね

2022-09-27 02:22 UTC, R-KazumaInazaki commented on myapp/README.md
> +docker-compose exec api rails runner Maintenance::Functions::StartSystem.execute
バッチはrails runnerではなくrake taskで実装お願いします。
rails runnerだとrubyのコード実行になるので、引数が扱いづらいなど不便なことが多いです。
また、今回のバッチであれば引数でどの機能をON/OFFすればいいか？ということができればいいので、
機能は引数で渡すとして、バッチは２種類でよさそうです。

2022-09-27 03:33 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +  end
render処理を共通化しました。

2022-09-27 03:37 UTC, connect-yuma-nakamura commented on myapp/app/models/function.rb
> +  def self.is_started(id)
メソッド名の最後に？をつけました。

2022-09-27 06:00 UTC, connect-yuma-nakamura commented on myapp/db/migrate/20220906235803_create_functions.rb
> +      t.string :status, limit: 1, null: false, default: '1'
停止中、開始中以外にもステータスはあるかなと思いコードにしていました。
今回の仕様に関してはbooleanで事足りるのでbooleanへ修正しました。

2022-09-27 06:03 UTC, connect-yuma-nakamura commented on myapp/app/models/function.rb
> +    Function.statuses[Function.find(id).status] == Function.statuses[:started] ? true : false
booleanにすることで```Function.find(id).status```、```!Function.find(id).status```を返却するよう修正しました。

2022-09-27 06:07 UTC, connect-yuma-nakamura commented on myapp/app/models/function.rb
> +  def self.is_started(id)
startedは一旦お作法として用意していただけなので削除しました。

2022-09-27 07:17 UTC, connect-yuma-nakamura commented on myapp/README.md
> +docker-compose exec api rails runner Maintenance::Functions::StartSystem.execute
runnerからrake taskへ修正しました。

2022-09-28 01:00 UTC, R-KazumaInazaki requested changes
再度レビューしました。ご確認お願いいたします。

2022-09-28 01:00 UTC, R-KazumaInazaki commented on myapp/README.md
> +docker-compose exec api rails runner Maintenance::Functions::StopDelete.execute
前の仕様が残ってしまってますね

2022-09-28 01:00 UTC, R-KazumaInazaki commented on myapp/app/controllers/tasks_controller.rb
> +  end
ApplicationControllerに`transition_503`を置くことで`check_system_started`の処理も共通化できそう、と思ったのですが、
TaskControllerから見た時に、どこのメソッドを呼び出しているのか分かりづらくなってしまいますね。。。

おそらく`check_create_service`や`check_update_service`など機能単位にメソッドを分けるのではなく、
引数で受け取った機能IDに対して、今その機能がメンテナンス中かどうか？と判断する単一のメソッドにすれば解決できそうです。
before_actionでも引数は受け取れたと思うので試してみてください。

2022-09-28 01:00 UTC, R-KazumaInazaki commented on myapp/lib/tasks/function.rake
> +    function = Function.find(args.id.to_i)
引数が正しい数字かどうかをチェックしましょう。

仮に引数が渡されなかった場合、`args.id`はおそらく空文字かnilになります。
空文字やnilに対して`.to_i`メソッドを利用すると0に変換され、id=0のレコードは無いとfindメソッドは例外を出します。

バッチは人が手で動かすものでもあるので、期待していない引数を渡してしまった時に、正しい引数を案内してあげるとよさそうです。

2022-09-28 01:00 UTC, R-KazumaInazaki commented on myapp/lib/tasks/function.rake
> +    puts function.inspect
このinspectは意図的に書いたものでしょうか？
これだと不要な情報が多く、更新されたことの確認だけであれば機能名とステータスだけで足りるのではと思います

2022-09-28 03:03 UTC, connect-yuma-nakamura commented on myapp/README.md
> +docker-compose exec api rails runner Maintenance::Functions::StopDelete.execute
失礼しました。削除しました。

2022-09-28 03:22 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +  end
1つのメソッドにし、引数でfunction_idを取得するよう修正しました。

2022-09-28 03:45 UTC, connect-yuma-nakamura commented on myapp/lib/tasks/function.rake
> +    function = Function.find(args.id.to_i)
引数チェック処理を追加しました。

2022-09-28 03:49 UTC, connect-yuma-nakamura commented on myapp/lib/tasks/function.rake
> +    puts function.inspect
inspectにした意図はないです。
→デバッグ時に記載していたので、特に何も考えずそれをそのまま適用させていました。
おっしゃる通りのため修正しました。

2022-09-28 05:37 UTC, R-KazumaInazaki approved these changes
LGTM!

2022-09-28 05:40 UTC, merged