ステップ20: タスクにラベルをつけられるようにしよう
Fablic/training pull request #1431
Opened 2022-09-26 08:00 UTC by miu-tsuzuki

■要件
### ステップ20: タスクにラベルをつけられるようにしよう

- タスクに複数のラベルをつけられるようにしてみましょう
- つけたラベルで検索できるようにしてみましょう

■対応内容
- 複数ラベル設定可能
- 複数ラベルで検索可能

■確認手順
・事前準備
　下記コマンドでDockerを起動
　docker-compose up --build
　
　下記URLにアクセス
 　 http://localhost:3001/
 　下記入力
　メールアドレス：[email1@example.com](mailto:email1@example.com)
　パスワード：test1

・タスク作成画面にて複数ラベルを設定し、タスク作成
　タスク一覧画面にて設定したラベルを指定し、検索した結果、作成したタスクが表示されることを確認
　タスク一覧画面にて設定していないラベルを指定し、検索した結果、作成したタスクが表示されないことを確認

2022-09-26 08:32 UTC, connect-yuma-nakamura requested changes
今回の対応分以外で気になるソースが多くあったため、以下に記載します。
- ReadMeが最新と異なる
- tasks_specのstatus は1とかじゃなくて:not_startedとかにできないか
- let名が統一されていない
- label編集機能のテストがない
- 全体的にtask[:]で参照している箇所はtask.で参照してほしい
- Step9のエラーページ作成がない？

2022-09-26 08:32 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = current_user.tasks.includes([:labels]).includes([:tasks_labels]).all.page(params[:page])
```includes([:tasks_labels])```は省いてjoinできます。
→中村も同様の指摘されているのでそこを参照ください。

2022-09-27 02:50 UTC, connect-yuma-nakamura requested changes
指摘しました。確認をお願いします。

2022-09-27 02:50 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_label_a) { FactoryBot.create(:tasks_label, task_id: task_a.id, label_id: label_a.id) }
task_labelはtransientを使用することでtaskのfactory作成時に自動的に作成されるようになります。
中村への指摘を参考に修正してみてください。

2022-09-27 03:11 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = current_user.tasks.includes([:labels]).includes([:tasks_labels]).all.page(params[:page])
labelsをpreloadするように修正しました。

2022-09-27 03:12 UTC, miu-tsuzuki commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = current_user.tasks.includes([:labels]).includes([:tasks_labels]).all.page(params[:page])
その他指摘事項についても全て修正しました。

2022-09-27 03:13 UTC, miu-tsuzuki commented on myapp/spec/system/tasks_spec.rb
> +        let!(:task_label_a) { FactoryBot.create(:tasks_label, task_id: task_a.id, label_id: label_a.id) }
taskのfactoryにlabelを作成するwith_labelを作成しました。

2022-09-27 03:17 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-09-27 03:19 UTC, merged