STEP20 タスクにラベルをつけられるようにしよう
Fablic/training pull request #1433
Opened 2022-09-27 07:04 UTC by kohei-matsubara

■要件
### ステップ20: タスクにラベルをつけられるようにしよう

- タスクに複数のラベルをつけられるようにしてみましょう
- つけたラベルで検索できるようにしてみましょう

■対応内容
- 複数ラベルをつけられるよう修正
- いづれかのラベルで検索されるよう修正

■確認手順
【画面】
1. 以下ページへアクセスし、ラベル一覧を押下
```http://localhost:3001```
<img width="363" alt="スクリーンショット 2022-09-27 15 45 08" src="https://user-images.githubusercontent.com/110374166/192452833-fa519944-ab9b-494e-a1cf-aef8ea32cdb8.png">

2. ラベル作成
作成を押下する
<img width="259" alt="スクリーンショット 2022-09-27 15 46 25" src="https://user-images.githubusercontent.com/110374166/192453104-505bc603-0c71-4200-9c32-17a1d644138d.png">

ラベルが作成されることを確認
<img width="278" alt="スクリーンショット 2022-09-27 15 46 45" src="https://user-images.githubusercontent.com/110374166/192453137-41db6785-5574-449a-95e8-905a312e3278.png">

3. タスク作成
ラベルを複数選択してタスクを作成
<img width="251" alt="スクリーンショット 2022-09-27 15 48 21" src="https://user-images.githubusercontent.com/110374166/192453438-4df83c37-8094-4856-aa47-20ce904ea837.png">

ラベルが複数登録されたことを確認
<img width="381" alt="スクリーンショット 2022-09-27 15 48 53" src="https://user-images.githubusercontent.com/110374166/192453538-697d8b92-2b34-4908-b9db-79ccaa84519b.png">

4. ラベルで検索
タスクを複数作成し、ラベル検索する。 今回はラベル2を選択
<img width="381" alt="スクリーンショット 2022-09-27 15 48 53" src="https://user-images.githubusercontent.com/110374166/192453694-d745ffbe-c1a9-4da2-b8ad-7890676ff1c8.png">

ラベル2のタスクのみ出力されることを確認
<img width="418" alt="スクリーンショット 2022-09-27 15 50 31" src="https://user-images.githubusercontent.com/110374166/192453852-6daba471-726e-4897-baa6-a9363685688a.png">

【spec】
```docker-compose exec api bundle exec rspec -f d spec/models/labels_spec.rb```
```docker-compose exec api bundle exec rspec -f d spec/models/tasks_spec.rb```
```docker-compose exec api bundle exec rspec -f d spec/models/users_spec.rb```
```docker-compose exec api bundle exec rspec -f d spec/system/tasks_spec.rb```
```docker-compose exec api bundle exec rspec -f d spec/system/labels_spec.rb```

2022-09-27 08:03 UTC, connect-yuma-nakamura requested changes
一部レビューしました。指摘項目を確認お願いします。

2022-09-27 08:03 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> -  before_action :set_task, only: %i[show edit update destroy]
set_taskは削除しなくてもよいのでは？

2022-09-27 08:03 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      redirect_to(root_path, notice: 'タスクを登録しました')
ここは変更する必要ないのでは？

2022-09-27 08:03 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      render(:new, status: :unprocessable_entity)
ここは変更する必要ないのでは？

2022-09-27 08:03 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +      redirect_to(root_path, notice: 'タスク更新成功')
ここは変更する必要ないのでは？

2022-09-27 08:03 UTC, connect-yuma-nakamura commented on myapp/app/controllers/tasks_controller.rb
> +    redirect_to(root_path, notice: 'タスク削除成功') if @task.destroy
メッセージなど修正する必要あるか？

2022-09-27 08:03 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +    # scope :where_label, -> (label) { where('tasks.id IN( SELECT task_id FROM labels WHERE labels.name like ? )', "%#{label}%") if label.present? }
このコメントアウトは削除してよい？

2022-09-27 08:49 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> -  before_action :set_task, only: %i[show edit update destroy]
削除不要であるため、元の状態に戻しました。

2022-09-27 08:50 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +      redirect_to(root_path, notice: 'タスクを登録しました')
変更の必要がないので元に戻しました。

2022-09-27 08:50 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +      render(:new, status: :unprocessable_entity)
変更の必要がないため元に戻しました。

2022-09-27 08:50 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +      redirect_to(root_path, notice: 'タスク更新成功')
変更の必要がないため元に戻しました。

2022-09-27 08:50 UTC, kohei-matsubara commented on myapp/app/controllers/tasks_controller.rb
> +    redirect_to(root_path, notice: 'タスク削除成功') if @task.destroy
変更の必要がないためメッセージを元に戻しました。

2022-09-27 08:51 UTC, kohei-matsubara commented on myapp/app/models/task.rb
> +    # scope :where_label, -> (label) { where('tasks.id IN( SELECT task_id FROM labels WHERE labels.name like ? )', "%#{label}%") if label.present? }
不要なコメントアウトだったので削除しました。

2022-09-27 09:37 UTC, connect-yuma-nakamura requested changes

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/index.html.erb
> +    <p><%= f.submit('検索') %></p>
labelを追加するだけでよいです。

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/index.html.erb
> +    <div name='create-task'>
このnameは使用しているか？

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/app/views/tasks/index.html.erb
> +    <div name='create-label'>
このnameは使用しているか？

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('path/to', '**').to_s]
これは日本語化対応、、？

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/spec/factories/tasks.rb
> +    trait :with_labels do
with_labelsは未使用？

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/spec/factories/tasks.rb
> +    trait :with_label do
with_labelは未使用？

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
>        end
ラベルの表示テストは不要？

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
>          it 'タスク名が表示される' do
ラベルの表示テストは不要？

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_current_path  root_path
空白スペースが多い

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
>            visit_task_a
ラベルの表示テストがない

2022-09-27 09:37 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> -          select value = user_1.name
user_1のletも不要？user_2も？
全体的に不要なletが残っていないか見直しをお願いします。

2022-09-28 00:07 UTC, kohei-matsubara commented on myapp/app/views/tasks/index.html.erb
> +    <p><%= f.submit('検索') %></p>
テキストフィールド名も一緒に追加していたので、ラベルの追加のみに修正しました。

2022-09-28 00:08 UTC, kohei-matsubara commented on myapp/app/views/tasks/index.html.erb
> +    <div name='create-task'>
未使用のため削除しました。

2022-09-28 00:08 UTC, kohei-matsubara commented on myapp/app/views/tasks/index.html.erb
> +    <div name='create-label'>
未使用のため削除しました。

2022-09-28 00:11 UTC, kohei-matsubara commented on myapp/spec/factories/tasks.rb
> +    trait :with_labels do
未使用のため削除しました。

2022-09-28 00:11 UTC, kohei-matsubara commented on myapp/spec/factories/tasks.rb
> +    trait :with_label do
未使用のため削除しました。

2022-09-28 00:12 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +          expect(page).to have_current_path  root_path
have_current_path  root_pathの間の空白を削除しました。

2022-09-28 00:15 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> -          select value = user_1.name
仕様変更したため、user_1, user_2が不要になっていたので削除しました。

2022-09-28 00:21 UTC, kohei-matsubara commented on myapp/config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('path/to', '**').to_s]
不要であるため削除しました。

2022-09-28 00:21 UTC, kohei-matsubara commented on myapp/config/application.rb
> +    config.i18n.load_path += Dir[Rails.root.join('path/to', '**').to_s]
不要だったので削除しました。

2022-09-28 02:23 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
>            visit_task_a
ラベル表示テストを追加しました。

2022-09-28 02:23 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
>          it 'タスク名が表示される' do
ラベル表示テストを追加しました。

2022-09-28 02:23 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
>        end
ラベル表示テストを追加しました。

2022-09-28 02:40 UTC, connect-yuma-nakamura requested changes
一旦spec以外レビュー完了

2022-09-28 02:40 UTC, connect-yuma-nakamura commented on myapp/app/models/task.rb
> +    scope :get_ids, -> (title, label, status) { eager_load(:labels).where_title(title).where_status(status).where_label(label).select('tasks.id') }
インデントがずれている
where_user_idは不使用？

2022-09-28 02:46 UTC, kohei-matsubara commented on myapp/app/models/task.rb
> +    scope :get_ids, -> (title, label, status) { eager_load(:labels).where_title(title).where_status(status).where_label(label).select('tasks.id') }
申し訳ありません。同じミスを繰り返していました。
where_user_idは不要であるため削除しました。

2022-09-28 03:01 UTC, connect-yuma-nakamura requested changes
specに関してもレビューしました。確認をお願いします。

2022-09-28 03:01 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
>    describe '新規登録機能' do
ラベルを設定して登録できるかの確認はできているか？

2022-09-28 03:01 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
>            # ユーザ2に変更する
ラベルの更新がない？

2022-09-28 03:01 UTC, connect-yuma-nakamura commented on myapp/spec/factories/tasks.rb
> +    trait :with_label do
これはtaskのsystem spec で使用しなければならなかったのでは？

2022-09-28 06:16 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
>    describe '新規登録機能' do
ラベルを設定して登録確認するテストを追加しました

2022-09-28 06:16 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
>            # ユーザ2に変更する
ラベルの更新に対するテストを追加しました。

2022-09-28 06:20 UTC, kohei-matsubara commented on myapp/spec/factories/tasks.rb
> +    trait :with_label do
task_spec上でlabelの登録更新ができているか確認する必要があったので、改めて追加しました。

2022-09-28 06:26 UTC, connect-yuma-nakamura requested changes
レビューしました。

2022-09-28 06:26 UTC, connect-yuma-nakamura commented on myapp/spec/system/tasks_spec.rb
> +    let!(:task_a) { FactoryBot.create(:task, :with_labels, title: '最初のタスク', description: '最初のタスクを実施する', status: 'not_started', user_id: user.id, label_name: 'label1') }
with_labelではなくwith_labelsにしている意図は何か

2022-09-28 06:32 UTC, kohei-matsubara commented on myapp/spec/system/tasks_spec.rb
> +    let!(:task_a) { FactoryBot.create(:task, :with_labels, title: '最初のタスク', description: '最初のタスクを実施する', status: 'not_started', user_id: user.id, label_name: 'label1') }
一覧表示機能のletをコピーして作成していたため、しっかり確認せずspecも通ったのでそのまま気づかずにレビューに出していました。１つしかラベルがないのでwith_labelで問題ないです。修正しました。

2022-09-28 06:35 UTC, connect-yuma-nakamura approved these changes
LGTM！

2022-09-28 06:37 UTC, merged