[Koyama STEP13] ステータスを追加して、検索できるようにしよう
Fablic/training pull request #1549
Opened 2023-05-11 01:52 UTC by coffee-stain-neko

## Jiraチケット
https://jira.rakuten-it.com/jira/browse/RAKUTRA-5180
## 行うこと
- ステータス（未着手・着手中・完了）を追加してみよう
- 一覧画面でタイトルとステータスで検索ができるようにしよう
- 絞り込んだ際、ログを見て発行されるSQLの変化を確認してみましょう
- 検索インデックスを貼りましょう
- 検索に対してmodel specを追加してみよう（system specも拡充しておきましょう）
## URL
[Rails 研修](https://github.com/Fablic/training/blob/develop/steps_jp.md)「ステップ13: ステータスを追加して、検索できるようにしよう」を実施しました
## 行ったこと
- ステータスの追加
- 一覧画面に検索機能を実装
- マイグレーションでインデックスを追加
- テストを実施した
### テスト結果
#### Modelテスト
<img width="583" alt="スクリーンショット 2023-05-11 10 46 35" src="https://github.com/Fablic/training/assets/129723112/5e6dcd61-cbaa-4b30-9ada-ea673c84626e">

#### SystemSpec
<img width="750" alt="スクリーンショット 2023-05-11 10 50 36" src="https://github.com/Fablic/training/assets/129723112/25f75ede-b48e-4642-972e-e5255e9fccf0">

```
Finished in 1.68 seconds (files took 1.51 seconds to load)
27 examples, 0 failures
```

2023-05-11 02:49 UTC, sourcewc reviewed
@coffee-stain-neko 
すみませんまだコード確認中ですが、
念の為画面の表示と検索結果もスクショをとってdescriptionに追加お願いできますか？

2023-05-11 04:50 UTC, sourcewc reviewed
step 13ではインデックス追加の項目があったと思うのでそちらも対応お願いします。

色々確認事項が多いと思います。
お手数ですがよろしくお願いします

2023-05-11 04:50 UTC, sourcewc commented on myapp/app/models/task.rb
> +  validates :status, inclusion: { in: ['未着手', '着手中', '完了済'] }
statusをinclusionで入力の制限するのはいいと思います。
ただ設計の話になりますが、statusをstringにした理由がありますか？
現在存在するステータス３パータン
`'未着手', '着手中', '完了済'`の場合、

個人的には指定されたステータスを表すためのInteger形式で良いと思いました。

2023-05-11 04:50 UTC, sourcewc commented on myapp/app/models/task.rb
> +  end
検索機能をタスクタイトルとsearch?(ステータスかな)とくっつけてメソッドを作成した理由がありますか？

今後メンテパターンをいくつか想定した時、以下のような懸念があります。

- あえて極端なケースを想定すると例えばsearch(ステータス)が100個あるとするとif elseが100個増えると思います
- seachとwordの引数命名が実際示しているデータと違い理解しにくいです
- titleとstatusの片方を修正したくても両方影響されて確認が大変
- `@tasks`でインスタンス変数を渡しているので他のエンドポイントから呼ばれると意図せず`@tasks`の結果が書き変わる可能性がある

ここからは提案です。
何か他の良さそうな進め方があれば変えても大丈夫です

- メソッド単位をstatusとtitle検索で両方分離する
- if elseのネストをやめてstatusはinclusionで制限しているので `=`で比較
- return値の見直し
- scope単位に分離して検索条件を追加が簡単にできるようにする

2023-05-11 04:50 UTC, sourcewc commented on myapp/app/views/tasks/_search.html.erb
> +    <%= form.select :search, options_for_select([['未着手', 'not_started_task'], ['着手中', 'started_task'],  ['完了済', 'completed_task']]), { include_blank: '------'}, id: 'search_status' %>
optionをハードコーディングしていますが、
こちら別にステータスを管理するテーブルだったりenumに変えてもらいたいです。。

こちらも上記のコメントのようにステータスが無数に増えるとメンテできなくなります。

2023-05-11 04:50 UTC, sourcewc commented on myapp/app/views/tasks/index.html.erb
> +  <% if  @tasks.present? %>
細かいですがスペースが２つ入っているようです。

2023-05-11 04:50 UTC, sourcewc commented on myapp/db/migrate/20230509042420_add_task_status_to_tasks.rb
> +  end
可能ならstring形式でステータスを管理するのは避けたいですね。
実装の目的を聞いてもいいでしょうか？

2023-05-11 04:50 UTC, sourcewc commented on myapp/spec/models/task_spec.rb
> +    end
モデルのrspecの場合
モデルのメソッドをテストするために書く物です。
http://www.code-magagine.com/?p=8913

検索のメソッドテストがないので追記お願いします。
あとついでですが、並び順のテストもないみたいですので追記お願いします。

2023-05-11 04:50 UTC, sourcewc commented on myapp/app/views/tasks/search.html.erb
> +<h2>Results index</h2>
searchのためのページを作っていますが、
中身はほぼほぼindexとそこまで変わらない気がします。
共通化した方がシンプルな気がします。

2023-05-12 05:37 UTC, coffee-stain-neko commented on myapp/app/models/task.rb
> +  end
scope単位に分離して検索条件を追加が簡単にできるように変更しました

2023-05-12 05:38 UTC, coffee-stain-neko commented on myapp/app/models/task.rb
> +  validates :status, inclusion: { in: ['未着手', '着手中', '完了済'] }
> 個人的には指定されたステータスを表すためのInteger形式で良いと思いました。

statusカラムをinteger形式に変更しました

2023-05-12 05:38 UTC, coffee-stain-neko commented on myapp/app/views/tasks/_search.html.erb
> +    <%= form.select :search, options_for_select([['未着手', 'not_started_task'], ['着手中', 'started_task'],  ['完了済', 'completed_task']]), { include_blank: '------'}, id: 'search_status' %>
enumに変更しました

2023-05-12 05:39 UTC, coffee-stain-neko commented on myapp/app/views/tasks/index.html.erb
> +  <% if  @tasks.present? %>
検索の処理上で不要になったため、削除しました

2023-05-12 05:41 UTC, coffee-stain-neko commented on myapp/db/migrate/20230509042420_add_task_status_to_tasks.rb
> +  end
enumを配列のinteger形式で管理するようになったため、integer形式に変更しました

2023-05-12 05:42 UTC, coffee-stain-neko commented on myapp/spec/models/task_spec.rb
> +    end
> 検索のメソッドテストがないので追記お願いします。
あとついでですが、並び順のテストもないみたいですので追記お願いします。

検索のメソッドテストと並び替えテストを追加しました

2023-05-12 05:43 UTC, coffee-stain-neko commented on myapp/app/views/tasks/search.html.erb
> +<h2>Results index</h2>
> searchのためのページを作っていますが、
中身はほぼほぼindexとそこまで変わらない気がします。

viewをindexと共通にしました

2023-05-12 06:19 UTC, coffee-stain-neko commented
@sourcewc 
一通りの修正と確認試験が完了しました。
よろしくお願いいします。

#### index
<img width="1396" alt="スクリーンショット 2023-05-12 14 47 46" src="https://github.com/Fablic/training/assets/129723112/b5fdaab3-3dc8-4995-ba49-431e2752eca4">

#### モデルテスト
<img width="786" alt="スクリーンショット 2023-05-12 14 48 51" src="https://github.com/Fablic/training/assets/129723112/ebf3a032-a8fa-4a92-a77f-784c2516cbd7">

#### SystemSpec
<img width="689" alt="スクリーンショット 2023-05-12 14 53 46" src="https://github.com/Fablic/training/assets/129723112/ab9dbccb-7ff6-435c-b1df-ea030fc64aa8">

2023-05-12 08:15 UTC, sourcewc reviewed
@coffee-stain-neko 
ご対応ありがとうございます。
ただ前回のコメントで色々実装の理由を聞きたかったことと、
レビュアーがわかりやすいように画面のキャップチャーをお願いしましたけれど、
それについては次のステップから気をつけていただきたいです。。

研修ではとりあえず動くものを作ることが大事だと思いますが、
今後プロダクトコードを触る際は１行を書く時も実装の理由が説明できるコードを書くことを心かけるといいと思います。

いくつか修正になると思いますので
対応のほうよろしくお願いします。

2023-05-12 08:15 UTC, rr-woochul-shin commented on myapp/app/controllers/tasks_controller.rb
> +  end
パラメータでdeadlineのorderを考慮してない実装になっています。

検索した状態で並び順を変えると検索条件がなくなると思うので
order関連のパラメータをコントローラーに追加して対応しましょう

2023-05-12 08:15 UTC, rr-woochul-shin commented on myapp/app/models/task.rb
> +  scope :where_status, -> (status) { where(status: status) if status.present? }
良さそうですね、scopeで書くことで１行でまとめられたし、
今後他のロジックにもこちらの検索機能を追加、削除しやすい状態だと思います。

2023-05-12 08:15 UTC, rr-woochul-shin commented on myapp/app/views/tasks/_search.html.erb
> +    <%= form.select :status, Task.statuses.keys.map { |k| [t("enums.task.status.#{k}"), k] }, { selected: 1 } %>
修正任意ですが
検索を外すためのも項目を用意すると親切だと思います
現在はurlを直接直してないとおそらく検索を外れない状態に見えます。

2023-05-12 08:15 UTC, rr-woochul-shin commented on myapp/app/views/tasks/index.html.erb
> +  <p><%= render partial: 'search' %></p>
pタグで囲む必要はなさそうです。

2023-05-12 08:15 UTC, rr-woochul-shin commented on myapp/config/routes.rb
> +  get 'search' => 'tasks#search'
今更気づいてすみませんが、こちらsearchがtasksのurlの配下になっていませんでした。

今確認したところsearchだけのurlになっていてREST APIのurl構造になっていません。
`http://0.0.0.0:3000/search`

こういう感じで修正しましょう
``` ruby
resources :tasks do
    get :search, on: :collection
  end
```

2023-05-12 08:15 UTC, rr-woochul-shin commented on myapp/db/migrate/20230511010502_add_index_task.rb
> +  end
複合インデックスになっていますが、こちらは片方だけで条件かけても問題ないでしょうか？

2023-05-12 08:15 UTC, sourcewc commented on myapp/spec/models/task_spec.rb
> +          expect(Task.where_title('あいうえお').where_status(1).count).to eq 1
task名検索なので`where_status`は不要です

2023-05-12 08:15 UTC, sourcewc commented on myapp/spec/models/task_spec.rb
> +          expect(Task.where_title('あいうえお').where_status(1).count).to eq 1
こちらもステータステストなので`where_title`は不要です。

2023-05-12 08:15 UTC, sourcewc commented on myapp/spec/system/task_spec.rb
> +                      status: 0, created_at: '2023/04/27 09:00')
ステータスのハードコーディングですが、
railsではこういう書き方もできます。

``` ruby
create(:task, id: '1', title: 'task1', content: 'task_contetnt1', deadline: '2023/04/27',
                      status: ：not_started, created_at: '2023/04/27 09:00')
```

2023-05-12 08:16 UTC, rr-woochul-shin commented on myapp/app/views/tasks/search.html.erb
> +<h2>Results index</h2>
確認しました！
こちらのコメントでやり取りお願いします
https://github.com/Fablic/training/pull/1549#discussion_r1192039225

2023-05-12 08:33 UTC, rr-woochul-shin requested changes
変更待ち

2023-05-14 22:22 UTC, coffee-stain-neko commented on myapp/db/migrate/20230511010502_add_index_task.rb
> +  end
@sourcewc 
必ず検索条件にステータスを含んで検索することになるため、複合インデックスにしている状態になります

2023-05-14 22:27 UTC, coffee-stain-neko commented
@sourcewc 
> 念の為画面の表示と検索結果もスクショをとってdescriptionに追加お願いできますか？

大変申し訳ありません。検索結果のスクショの提示を失念しておりました。

> ただ前回のコメントで色々実装の理由を聞きたかったことと、
> レビュアーがわかりやすいように画面のキャップチャーをお願いしましたけれど、
> 回答もらえず、、
> それについては次のステップから気をつけていただきたいです。。

ステータスカラムの型について質問が来ておりましたが、内容の修正したものの、質問に
回答しておりませんでした。申し訳ありません。

2023-05-14 22:36 UTC, coffee-stain-neko commented on myapp/app/views/tasks/_search.html.erb
> +    <%= form.select :status, Task.statuses.keys.map { |k| [t("enums.task.status.#{k}"), k] }, { selected: 1 } %>
@sourcewc 

> 検索を外すためのも項目を用意すると親切だと思います

検索後、条件をリセットして一覧画面に戻る方法がないため
機能として追加する方が親切です、意味でよかったでしょうか？

2023-05-14 23:53 UTC, sourcewc commented on myapp/app/views/tasks/_search.html.erb
> +    <%= form.select :status, Task.statuses.keys.map { |k| [t("enums.task.status.#{k}"), k] }, { selected: 1 } %>
ですです、
最初の実装には`-----`みたいな機能がありました。
現在のコードでは検索条件リセットがないのでURLから一覧画面に戻るか条件を外さないと
リセットできない状態になったと思います。

2023-05-14 23:57 UTC, sourcewc commented on myapp/db/migrate/20230511010502_add_index_task.rb
> +  end
こちらのコードでは片方だけの検索が想定されているように実装されてます。
むしろ現在必ずtitleとsatusの両方検索のSQLが発行されるならコントローラーの修正するべきですね
https://github.com/Fablic/training/blob/c0b0136be17c280a56b46ec0e1fee2b57f0e1573/myapp/app/models/task.rb#L7-L8

単純に片方のlike SQLでindexが使用されているかだけ確認したかったです。
問題なかったらこのままでも大丈夫です。

2023-05-16 05:46 UTC, coffee-stain-neko commented on myapp/spec/system/task_spec.rb
> +                      status: 0, created_at: '2023/04/27 09:00')
`status: 0 => status: ：not_started`の記載方法に変更しました

2023-05-16 05:47 UTC, coffee-stain-neko commented on myapp/spec/models/task_spec.rb
> +          expect(Task.where_title('あいうえお').where_status(1).count).to eq 1
ステータステストの`where_title`は削除しました

2023-05-16 05:47 UTC, coffee-stain-neko commented on myapp/spec/models/task_spec.rb
> +          expect(Task.where_title('あいうえお').where_status(1).count).to eq 1
タスク名テストの`where_status`は削除しました

2023-05-16 05:49 UTC, coffee-stain-neko commented on myapp/config/routes.rb
> +  get 'search' => 'tasks#search'
ルーティングをネストするように修正しました
[e05eff8](https://github.com/Fablic/training/pull/1549/commits/e05eff846add75a7d9e187c26149ac6f58113138)

2023-05-16 05:50 UTC, coffee-stain-neko commented on myapp/app/views/tasks/index.html.erb
> +  <p><%= render partial: 'search' %></p>
修正しました
[7b51d09](https://github.com/Fablic/training/pull/1549/commits/7b51d091311a56ddccb8a63462df8e88a6ab5936)

2023-05-16 05:51 UTC, coffee-stain-neko commented on myapp/app/views/tasks/_search.html.erb
> +    <%= form.select :status, Task.statuses.keys.map { |k| [t("enums.task.status.#{k}"), k] }, { selected: 1 } %>
リセットボタンを追加しました
[a96c707](https://github.com/Fablic/training/pull/1549/commits/a96c7072ab69696ebb0f03b98c329c887094ce45)

2023-05-16 05:52 UTC, coffee-stain-neko commented on myapp/app/controllers/tasks_controller.rb
> +  end
検索の際にソート条件を含めるように修正しました
[5b14dde](https://github.com/Fablic/training/pull/1549/commits/5b14ddef6ec131a3c65099696de7dfdfb728ddf1)
[946e88d](https://github.com/Fablic/training/pull/1549/commits/946e88d0bfe194a773950332bb1d73c34250baf0)

2023-05-16 05:56 UTC, coffee-stain-neko commented
![20230516142944](https://github.com/Fablic/training/assets/129723112/3a1fa765-696e-4076-be7e-52c9c158be1a)
#### Model
<img width="613" alt="スクリーンショット 2023-05-16 14 26 59" src="https://github.com/Fablic/training/assets/129723112/e87966a5-3208-497c-b990-72d3f91333e9">

#### SystemSpec
<img width="731" alt="スクリーンショット 2023-05-16 14 26 12" src="https://github.com/Fablic/training/assets/129723112/34e61939-d765-44bc-a788-6c9a1a508efa">

@sourcewc 
一通りの修正、確認試験が完了しました。
足りない資料等ありましたら教えてください。
よろしくお願いいたします。

2023-05-16 08:43 UTC, sourcewc commented on myapp/app/views/tasks/index.html.erb
> +          <%= link_to t('sort.work.desc'), search_tasks_path(deadline_order: 'desc') %>
以下みたいな変なパラメータを渡すとエラーになると思います
`http://0.0.0.0:3000/tasks/search?deadline_order=tst`

2023-05-16 08:43 UTC, sourcewc commented on myapp/app/views/tasks/_search.html.erb
> +    <%= form.hidden_field :deadline_order, :value => @deadline_order  %>
`:selected => @status`のような書き方は過去のRailsバージョンで使用した書き方らしいです。
ラクマでは主に
`selected: @status`で書くことが多いので修正しましょう
他の =>の箇所も同じです

2023-05-16 08:44 UTC, sourcewc commented
@coffee-stain-neko 
お疲れ様です。
細かいところにコメントを残しました！
明日対応お願いします。

2023-05-16 23:58 UTC, coffee-stain-neko commented on myapp/app/views/tasks/index.html.erb
> +          <%= link_to t('sort.work.desc'), search_tasks_path(deadline_order: 'desc') %>
`asc`もしくは`desc`が含んでいた際に処理するように変更しました
[d0d1acc](https://github.com/Fablic/training/pull/1549/commits/d0d1acce54ea20237b1d99eff819efa142a9c24a)

2023-05-17 00:02 UTC, coffee-stain-neko commented on myapp/app/views/tasks/_search.html.erb
> +    <%= form.hidden_field :deadline_order, :value => @deadline_order  %>
該当する記述を全て変更しました
[020b3ae](https://github.com/Fablic/training/pull/1549/commits/020b3ae57350b34c38296b5cff50fe43663f2316)

2023-05-17 00:07 UTC, coffee-stain-neko commented
@sourcewc
修正が終わりました！
よろしくお願いします。

2023-05-17 04:05 UTC, coffee-stain-neko commented
@sourcewc 
すみません。
searchメソッドの条件式が長くなってしまっていたので、リファクタリングしました。
[8326e25](https://github.com/Fablic/training/pull/1549/commits/8326e256e3d8176e36922463f6b96b89ff27ac6c)

2023-05-17 05:03 UTC, sourcewc commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if params.key?(:deadline_order) && !params[:deadline_order].nil? && %w[asc desc].include?(params[:deadline_order])
いい改善ですね！ w[].include?を使って対応して読みやすいコードになったと思います。
もっとシンプルに書くとこういう書き方になると思います。

``` ruby
def search
    @tasks = Task.where_title(params[:title]).where_status(params[:status]).deadline_order(params[:deadline_order])
    @tasks.order(created_at: :DESC) if params.key?(:deadline_order) && !params[:deadline_order].nil?
    @title = params[:title]
    @status = params[:status]
    @deadline_order = params[:deadline_order]
    render :index
  end
```

あとデータベース問い合わせ関連のコードはModelに寄せるのがMVC的に良いです。

task.rb
``` ruby
scope :deadline_order, -> (v) { order(deadline: v) if %w[asc desc].include?(v) }
```

2023-05-17 06:27 UTC, coffee-stain-neko commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if params.key?(:deadline_order) && !params[:deadline_order].nil? && %w[asc desc].include?(params[:deadline_order])
@sourcewc 
``` ruby
@tasks.order(created_at: :DESC) if params.key?(:deadline_order) && !params[:deadline_order].nil?
```
ありがとうございます！
すみません。１点教えてください。
`asc,desc`以外の文字列が`params[:deadline_order]`に入っていた場合は、並び順は上記の処理が実行されると思っています。しかし、表示はidのasc順になってしていました。どこか他に処理を追加するとこがあったのでしょうか。見落としや、認識の違いがあれば教えてください。

2023-05-17 06:55 UTC, sourcewc commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if params.key?(:deadline_order) && !params[:deadline_order].nil? && %w[asc desc].include?(params[:deadline_order])
動作確認深くせずコードをみて置き換えたですが、
そういう問題があったんですね。

ifの条件をなくして後ろに`.order(created_at: :DESC)`をつける方法もありえますし、
片方だけやりたいなら`deadline_order`に寄せれば良さそうですね
``` ruby
def search
    @tasks = Task.where_title(params[:title]).where_status(params[:status]).deadline_order(params[:deadline_order])
    @title = params[:title]
    @status = params[:status]
    @deadline_order = params[:deadline_order]
    render :index
  end
```

``` ruby
scope :deadline_order, -> (v) { %w[asc desc].include?(v) ? order(deadline: v) : order(created_at: :DESC) }
```

2023-05-17 07:05 UTC, coffee-stain-neko commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if params.key?(:deadline_order) && !params[:deadline_order].nil? && %w[asc desc].include?(params[:deadline_order])
@sourcewc 
三項演算子で判別する方法は考えておりませんでした。
ありがとうございます！

2023-05-17 07:13 UTC, coffee-stain-neko commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if params.key?(:deadline_order) && !params[:deadline_order].nil? && %w[asc desc].include?(params[:deadline_order])
修正しました！
[83e5927](https://github.com/Fablic/training/pull/1549/commits/83e5927deaea14452fbbfa6d993b5f38a590c0af)
[9bf0a84](https://github.com/Fablic/training/pull/1549/commits/9bf0a84790ced77f18f0c7875a72cc74f1dd3892)

2023-05-17 07:18 UTC, sourcewc commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if params.key?(:deadline_order) && !params[:deadline_order].nil? && %w[asc desc].include?(params[:deadline_order])
お疲れ様でした！実装はこれで良さそうです。

ただ`deadline_order`の動作が少し変わったのでmodelのspecを変更お願いします
これが最後です！

2023-05-17 07:30 UTC, coffee-stain-neko commented on myapp/app/controllers/tasks_controller.rb
> +    @tasks = if params.key?(:deadline_order) && !params[:deadline_order].nil? && %w[asc desc].include?(params[:deadline_order])
終了期限ソートの値が不正値だった場合のテストを追加しました
[646177c](https://github.com/Fablic/training/pull/1549/commits/646177c4ce290df3d31438244f77365bbdd330b4)
<img width="444" alt="スクリーンショット 2023-05-17 16 26 41" src="https://github.com/Fablic/training/assets/129723112/3261c351-a935-4569-8a92-cafd345cc8e8">

2023-05-17 07:34 UTC, sourcewc approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/10580)

2023-05-17 23:28 UTC, merged