[Koyama STEP19]ユーザにロールを追加しよう
Fablic/training pull request #1555
Opened 2023-05-31 06:03 UTC by coffee-stain-neko

## Jiraチケット
https://jira.rakuten-it.com/jira/browse/RAKUTRA-5187
## 行うこと
- ユーザに管理ユーザと一般ユーザを区別するようにしてみましょう
- 管理ユーザだけがユーザ管理画面にアクセスできるようにしてみましょう
- ユーザ管理画面でロールを選択できるようにしましょう
- 管理ユーザが1人もいなくならないように削除の制御をしましょう
   ※ Gemの使用・不使用は自由です

## URL
[Rails 研修](https://github.com/Fablic/training/blob/develop/steps_jp.md)「ステップ19: ユーザにロールを追加しよう」を実施しました
## 行ったこと
- ユーザー機能の権限を管理者権限を持ったユーザーのみに制限
- 管理者は自分のユーザー情報を削除できないように制限
- 管理者は自分のユーザー編集画面では役割変更できないように制限
- User ModelSpec の実施
- User SystemSpec の実施

## 動作確認
### 管理ユーザーのみできること
![管理ユーザー](https://github.com/Fablic/training/assets/129723112/291f3b77-6468-423b-a3ed-a9ffb68754a0)

### 一般ユーザーのアクセス制限
![一般ユーザー](https://github.com/Fablic/training/assets/129723112/a0011cc2-a859-4c85-b14a-044f843e6803)

2023-06-01 09:14 UTC, KumoRaku requested changes
コメントしました
ご確認お願いいたします。

2023-06-01 09:14 UTC, KumoRaku commented on myapp/app/models/user.rb
> +  enum role: { general: false, admin: true }
拡張性視点から考えると、
roleはbooleanよりintにした方が良さそうです。
（本番だと今後新しいロールが追加する可能性を考えた方がいいと思います。）
（今回Rails研修ではrole追加するとかのStepがないだけど）

2023-06-01 09:14 UTC, KumoRaku commented on myapp/db/schema.rb
> +    t.boolean "role", default: false, null: false
こちらもbooleanよりintにした方が拡張性が良いと思います。

2023-06-02 04:33 UTC, coffee-stain-neko commented on myapp/app/models/user.rb
> +  enum role: { general: false, admin: true }
intへの変更に加えて、enumの中身も一部変更しました
[b99ae60](https://github.com/Fablic/training/pull/1555/commits/b99ae6012e08f4b131b7a2f7a77d3c339b398554)

2023-06-02 04:34 UTC, coffee-stain-neko commented on myapp/db/schema.rb
> +    t.boolean "role", default: false, null: false
@KumoRaku 
roleの型をboolean→intに変更しました
[b41ddbb](https://github.com/Fablic/training/pull/1555/commits/b41ddbb01bd5b52159452abbd22b1bda60fe6418)

2023-06-05 01:47 UTC, KumoRaku approved these changes
LGTM!

2023-06-05 02:17 UTC, merged