Environment build
Fablic/training pull request #1636
Opened 2024-05-21 06:17 UTC by fanfannb

perpose：
Environment build

related tasks：
ステップ1: 開発環境を構築しよう
ステップ2: リポジトリの初期設定をしよう
ステップ3: Railsプロジェクトを作成しよう
ステップ4: Dockerに慣れましょう

<img width="1373" alt="截屏2024-05-21 15 16 47" src="https://github.com/Fablic/training/assets/102937509/27b97d57-47e2-4c9c-b896-cb6eddf11322">

2024-05-22 00:22 UTC, higuching reviewed
Please provide appropriate information in the PR Description and README! 
In that case, please consider the structure and use markdown notation to make the document easy for the reader to read.
Since PR is seen by many people when developing with Rakuma, I hope you can think of it as training now.

PRのDescriptionとREADMEに適切な情報を記載お願いします！
その際、読み手にとって読みやすいドキュメントとなるように構成を考えてみたりマークダウン記法を駆使してみてください。
ラクマで開発する際のPRは多くの人から見られるため、今はそのトレーニングだと思っていただければと思いますmm

2024-05-22 00:22 UTC, higuching commented on myapp/Dockerfile
> +ENV NODE_VERSION 18
version 18を指定した理由を記載いただけますか？（なぜ最新でないかも含めて）

2024-05-22 00:22 UTC, higuching commented on myapp/.ruby-version
> +ruby-2.6.10
Rubyは現在ラクマで使っているバージョンか、最新版を指定お願いします！

2024-05-22 00:22 UTC, higuching commented on myapp/Gemfile
> +gem 'rails', '~> 6.0.6', '>= 6.0.6.1'
Railsも現在ラクマで使っているバージョンか、最新版を指定お願いします！

2024-05-22 00:22 UTC, higuching commented on myapp/Gemfile.lock
> +   1.17.2
こちらもだいぶ古いので新しいバージョンを使用するようにしてみてください

2024-05-22 02:19 UTC, mvincent-yap commented
delete cache folder and add into gitignore

2024-05-22 02:22 UTC, mvincent-yap requested changes
delete tmp/cache folder and add into gitignore

2024-05-22 02:38 UTC, kanipan commented
- file changes が多すぎると reviewer が見るのが大変なので不要なファイルは .gitignore に含める
- api を参考に .gitignore を編集する
- (optional) rails.new したものをすべて push してもいいが不要なものは消しておくとベスト
  - application cable (web socket 用モジュール) とか
  - 一旦全部コミットしてから不要なものを消すコミットを作っていく方法でも良い
- コミットメッセージは why を書く

2024-05-23 01:22 UTC, fanfannb commented on myapp/.ruby-version
> +ruby-2.6.10
バージョンについては、rubyとrailsとNODEを最新版を指定したときに、エラーが出て失敗したので、M san said it’s better to focus on working version now

2024-05-23 01:51 UTC, higuching commented on myapp/.ruby-version
> +ruby-2.6.10
OK, I understand.
Please make a ticket for upgrade ruby/rails version as optional tasks.

2024-05-23 03:00 UTC, higuching commented
@fanfannb Please update the following

> Please provide appropriate information in the PR Description and README!
In that case, please consider the structure and use markdown notation to make the document easy for the reader to read.
Since PR is seen by many people when developing with Rakuma, I hope you can think of it as training now.
PRのDescriptionとREADMEに適切な情報を記載お願いします！
その際、読み手にとって読みやすいドキュメントとなるように構成を考えてみたりマークダウン記法を駆使してみてください。
ラクマで開発する際のPRは多くの人から見られるため、今はそのトレーニングだと思っていただければと思いますmm

2024-05-23 07:27 UTC, higuching approved these changes
LGTM!

2024-05-24 01:24 UTC, kanipan approved these changes

2024-05-24 01:24 UTC, kanipan commented
LGTM

![寿司ゆき:ok](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/03.png)

2024-05-24 02:17 UTC, mvincent-yap approved these changes
LGTM

2024-05-24 06:15 UTC, merged