ステップ9: アプリの各種設定を行いましょう
Fablic/training pull request #748
Opened 2020-08-20 01:58 UTC by monakam01

## 課題
-  [ステップ9: アプリの各種設定を行いましょう](https://github.com/Fablic/training/tree/m-nakamura/eumetopias_2/docs#ステップ9-アプリの各種設定を行いましょう)

## 変更内容
- i18nを追加（デフォルト言語を日本語に設定）
- タイムゾーンを東京に設定
- エラーページ（404, 500）を追加
- 開発環境のエラー画面を自作ページに変更

## コメント
### 当PRの差分ファイル
- 前ステップのPRがマージがされていない場合、関係無い差分が出ます。下記の差分のみ確認ください。
```
 eumetopias_2/Gemfile
 eumetopias_2/Gemfile.lock
 eumetopias_2/app/controllers/application_controller.rb
 eumetopias_2/app/views/errors/error_404.html.erb
 eumetopias_2/app/views/errors/error_500.html.erb
 eumetopias_2/config/application.rb
 eumetopias_2/config/environments/development.rb
 eumetopias_2/config/routes.rb
```

### エラー画面の確認をした手順
#### 500の確認
- task#indexに例外コードを仕込み、 ブラウザで http://localhost:3000 にアクセスし500のページが表示されることを確認
`app/controllers/task_controller.rb`
```ruby
class TaskController < ApplicationController
   def index
    raise Exception # 追加
    @task = Task.all
  end
       ・
       ・
```

#### 404の確認
- routes.rbに定義されていない http://localhost:3000/dummy にアクセスし404のページが表示されることを確認

# スクリーンショット 
<img width="651" alt="スクリーンショット 2020-08-20 9 22 53" src="https://user-images.githubusercontent.com/69135260/90706781-f3d32f00-e2d0-11ea-8439-1720af838054.png">

<img width="674" alt="スクリーンショット 2020-08-20 9 26 07" src="https://user-images.githubusercontent.com/69135260/90706802-ffbef100-e2d0-11ea-847c-64e353f168bf.png">

2020-08-23 23:46 UTC, fmot commented on eumetopias_2/app/controllers/application_controller.rb
> +    logger.debug('404')
ログが出力させるようになっているのいいですね👍

2020-08-23 23:46 UTC, fmot commented on eumetopias_2/app/controllers/application_controller.rb
> +    logger.debug('500')
👍

2020-08-24 00:02 UTC, fmot requested changes

2020-08-24 00:02 UTC, fmot commented on eumetopias_2/app/controllers/application_controller.rb
> +  rescue_from Exception, with: :render_500
こちらですがExceptionのrescueは避けた方が良さそうです！
https://qiita.com/snaka/items/40c9fd3cc16c2ccc195d

2020-08-24 02:04 UTC, monakam01 commented on eumetopias_2/app/controllers/application_controller.rb
> +  rescue_from Exception, with: :render_500
ありがとうございます！
interruptまでrescueされるのは勉強になりました。
プログラムのエラーに限定する形で `StandardError` に変更しました。

2020-08-24 04:26 UTC, fmot commented
LGTMです！

2020-08-24 04:30 UTC, fmot approved these changes

2020-08-24 04:31 UTC, merged