ステップ16: 複数人で利用できるようにしよう（ユーザの導入
Fablic/training pull request #775
Opened 2020-09-03 08:47 UTC by monakam01

## 課題
- [ステップ16: 複数人で利用できるようにしよう（ユーザの導入](https://github.com/Fablic/training/tree/m-nakamura#ステップ15-デザインを当てよう--スキップ可能)

## 変更内容
- Userモデル追加
  - Userモデルテストを追加
- 初期ユーザー投入用seed作成
- Taskモデル、Userモデルの関連を追加
- N+1問題対策
  - `Gem 'bullet'` を追加
  - TaskコントローラーのN+1発生箇所を修正
- docs/ERD.png を更新（Userテーブルにemailを追加）

## コメント
- レビュー用にベースブランチを `m-nakamura_15_add_design_2` に設定しています
　（Merge時は m-nakamura に戻して実行予定）

## 動作確認について
- DB設定
  - `dotenv-rails`でDBの設定情報を隠蔽しているため、`$ mv .env.template .env`して、[ユーザー名]、[パスワード] をご自身の環境のものに書き換えてください。
- その他の環境再現メモ
  - [2020-09-02 Rails研修 環境構築メモ](https://rak.box.com/s/wgohbyls1jmiuajxkpupzs9atrwh2tsw)
  - [Vagrantfile](https://rak.box.com/s/fluhlwqhkoszfpmpytppnyeb7uzitio0)（研修者(中村)の実行環境はVagrant, AWS Linux）
  
## 実行結果コード／SS
### Userモデルテスト　結果
```
$ bundle exec rspec spec/models/user_spec.rb 
.
Finished in 0.04782 seconds (files took 0.7958 seconds to load)
1 example, 0 failures
```

---

### N+1 検出時のブラウザ上のメッセージ
<img width="505" alt="スクリーンショット 2020-09-03 16 08 58" src="https://user-images.githubusercontent.com/69135260/92092434-0c813000-ee0d-11ea-91ce-9b2e61789db0.png">

2020-09-04 08:53 UTC, satoshi-kwn requested changes
コメントしました！

2020-09-04 08:53 UTC, satoshi-kwn commented on eumetopias_2/app/models/user.rb
> +    validates :email, presence: true
バリデーションに関して、検証項目を増やした方が良いと思います！
既存の検証項目のみだと想定外のデータがDBに登録されかねないように感じる為です。
以下、参考例なので、どこまで実装するかはお任せします！
名前→文字数の検証
メールアドレス→文字数やフォーマット、一意性の検証（[参考サイト](https://qiita.com/aiorange19/items/6f7d1d0f7582b5159b65)）
パスワード→文字数や複雑性の検証([参考サイト](https://qiita.com/E6YOteYPzmFGfOD/items/807d63cfb7f5f34d4314))
※内容を詳細に確認できてはいないですが、参考になりそうなサイトがあったので連携しときます。

2020-09-04 08:53 UTC, satoshi-kwn commented on eumetopias_2/app/models/user.rb
> +    validates :password, presence: true
念の為の確認ですが、パスワードはハッシュ化してデータベースに登録する想定ですか？
上記の想定がなければ、セキュリティの観点からパスワードはハッシュ化するようお願いします！([参考サイト](https://qiita.com/shumpeism/items/4d8946ade2dbdccab31c))

2020-09-04 08:53 UTC, satoshi-kwn commented on eumetopias_2/Gemfile
> +  gem 'bullet'
N+1問題を検出を検出してくれるライブラリなんてあるんですね！勉強になります！

2020-09-07 08:48 UTC, monakam01 commented on eumetopias_2/app/models/user.rb
> +    validates :email, presence: true
- バリデーション項目、モデルテストも合わせて追加しました。
  - 指示書の品質要求について失念しており実装漏れていました。m(_ _)m
  >一般的な品質で作ってください。
 [アプリケーション（サーバ）の構成について](https://github.com/Fablic/training/tree/m-nakamura#アプリケーションサーバの構成について)

2020-09-07 08:49 UTC, monakam01 commented on eumetopias_2/app/models/user.rb
> +    validates :password, presence: true
- 同上に追加いたしました。

2020-09-09 00:13 UTC, satoshi-kwn approved these changes
LGTMです！

2020-09-09 00:39 UTC, merged