Uyo123 step16&step17
Fablic/training pull request #933
Opened 2021-03-22 01:43 UTC by UYO123

## 参考
[step16](https://github.com/Fablic/training#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9716-%E8%A4%87%E6%95%B0%E4%BA%BA%E3%81%A7%E5%88%A9%E7%94%A8%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%82%88%E3%81%86%E3%83%A6%E3%83%BC%E3%82%B6%E3%81%AE%E5%B0%8E%E5%85%A5)
[step17](https://github.com/Fablic/training#%E3%82%B9%E3%83%86%E3%83%83%E3%83%9717-%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%83%AD%E3%82%B0%E3%82%A2%E3%82%A6%E3%83%88%E6%A9%9F%E8%83%BD%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%97%E3%82%88%E3%81%86)

## [環境構築方法](https://github.com/Fablic/training/tree/UYO123/yaraneba#%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89)
環境構築でエラーが発生した際もお申し付けください。

## 実施内容

## 確認事項

## rubocop & spec 実施内容
![スクリーンショット 2021-03-22 10 23 44](https://user-images.githubusercontent.com/78333980/111929960-278e6580-8afb-11eb-8ef6-2f41783cb286.png)

## 画面(ヘッダーのタイトル位置は気にしなくて良いです。)
### main
ログイン前 
![スクリーンショット 2021-03-22 10 42 11](https://user-images.githubusercontent.com/78333980/111930002-43920700-8afb-11eb-8203-cb8132bf060d.png)

ログイン後
<img src="https://user-images.githubusercontent.com/78333980/110740307-301eaa80-8276-11eb-8989-7d7b269a02ab.png" width="300">

### 作成＆編集
<img src="https://user-images.githubusercontent.com/78333980/110740473-74aa4600-8276-11eb-9e96-894962894408.png" width="300">

### 詳細
<img src="https://user-images.githubusercontent.com/78333980/110740557-9acfe600-8276-11eb-85bb-4223b83c309b.png" width="300">

2021-03-22 06:03 UTC, uzushino commented on yaraneba/app/controllers/application_controller.rb
>    private def rescue404()
引数なしの場合、`()` は不要です。

```suggestion
  private def rescue404
```

2021-03-22 06:04 UTC, uzushino commented on yaraneba/app/controllers/application_controller.rb
> +  end
```suggestion
  private
  
  def login_check
    redirect_to login_path if session[:user_id].blank?
  end

  def not_logged_in_check
    redirect_to tasks_path if session[:user_id].present?
  end
```

private は 1箇所でまとめれます

2021-03-22 06:04 UTC, uzushino commented on yaraneba/app/views/login/new.html.erb
> +    <%= form.text_field :password, class: 'form-control' %>
パスワード入力欄 は password_field 使った方が良さそう。（修正判断はお任せ）

2021-03-22 06:04 UTC, uzushino commented on yaraneba/app/views/tasks/_form.html.erb
> +  <%= form.hidden_field :user_id, :value => session[:user_id] %>
ここを直接変えると、別の人のタスクが作れます。

2021-03-22 06:06 UTC, uzushino requested changes
hidden で user_id を持たせてるのは危険なので、保存時にログイン時のユーザーの
IDを登録してください

2021-03-22 06:18 UTC, zackey-y commented on yaraneba/app/controllers/application_controller.rb
> +  private def not_logged_in_check
実際にやっているのは「ログインしていること」のチェックとログインしている際の動作なのでメソッドの命名に違和感があります

2021-03-22 06:18 UTC, zackey-y commented on yaraneba/app/controllers/login_controller.rb
> +    redirect_to tasks_path if session[:user_id].present?
これ `before_action` で走る `not_logged_in_check ` と同じ処理ではないでしょうか？

2021-03-22 06:21 UTC, zackey-y commented on yaraneba/app/controllers/login_controller.rb
> +  before_action :not_logged_in_check, except: :destroy
`destroy` を除外する意味が特にないように思います

2021-03-22 06:22 UTC, zackey-y commented on yaraneba/app/controllers/users_controller.rb
> +    redirect_to tasks_path if session[:user_id].present?
これも `before_action` で走る `not_logged_in_check ` と同じ処理ではないでしょうか？

2021-03-22 06:24 UTC, UYO123 commented on yaraneba/app/controllers/login_controller.rb
> +  before_action :not_logged_in_check, except: :destroy
こちらはdestroyを除外しない限り永遠にログアウトすることができなくなるため除いています。

2021-03-22 06:26 UTC, zackey-y commented on yaraneba/app/controllers/login_controller.rb
> +    if @user && @user&.authenticate(params[:password])
手前で `@user` の存在を確認しているので `&` を付ける必要はなさそうです

2021-03-22 06:28 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +  before_action :login_check, except: :index
`index` を除外しているのはなぜでしょうか？
`session[:user_id]` を使用しているのでチェック必要な気がしますが

2021-03-22 06:31 UTC, zackey-y commented on yaraneba/spec/factories/tasks.rb
> +    user_id { '1' }
`user_id` は文字列型ではなさそうです

2021-03-22 06:33 UTC, zackey-y commented on yaraneba/spec/factories/users.rb
> +    id { 1 }
ここに限らずですが、少なくともID カラムは `sequence` を利用してテストのたびに変化するようにしてほしいです
特定のIDを期待するSpecができてしまったりすると、修正や追加が面倒になることがあるので

2021-03-22 06:34 UTC, UYO123 commented on yaraneba/app/controllers/tasks_controller.rb
> +  before_action :login_check, except: :index
TOPページも兼ねているためです。
session情報がない場合はTOPページをある場合はタスク一覧を表示します。

2021-03-22 06:49 UTC, zackey-y commented on yaraneba/app/controllers/login_controller.rb
> +  before_action :not_logged_in_check, except: :destroy
あぁ、`not_logged_in_check` がただのチェックではなく、「タスク一覧画面を表示するとき専用」のチェックなんですね
これに汎用っぽい名前がついているのが良くないと思うので、専用とわかる命名にするか処理を見直して汎用的に使えるようにすると良さそうに思いますー

2021-03-22 07:01 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +  before_action :login_check, except: :index
すみません、View見たらその部分が追加されていますね
ただ、このURLがトップページなのはおかしな感じがするので、トップページをログインページに変更してそちらにリダイレクトするほうが素直なように思います

2021-03-22 09:06 UTC, UYO123 commented
修正事項
- TOPページ分離
  - yaraneba/app/controllers/top_controller.rb
  - yaraneba/app/views/top/index.html.erb
  - yaraneba/config/routes.rb
- [()不要、privateをまとめる、メソッド名変更](yaraneba/app/controllers/application_controller.rb)
- [password_fieldに変更](yaraneba/app/views/login/new.html.erb)
- [hiddenパラメータ変更](yaraneba/app/controllers/tasks_controller.rb)
- 不要な処理削除
  - yaraneba/app/controllers/login_controller.rb
  - yaraneba/app/controllers/users_controller.rb
- stepなど各種変更
  - 実行後のspec & rubocop
  ![スクリーンショット 2021-03-22 17 43 22](https://user-images.githubusercontent.com/78333980/111965571-37c53580-8b39-11eb-97b6-ae71e40f4b35.png)

2021-03-22 23:12 UTC, zackey-y commented on yaraneba/app/controllers/application_controller.rb
> +    redirect_back fallback_location: root_path if session[:user_id].present?
http://localhost:3000/users/

2021-03-22 23:13 UTC, zackey-y commented on yaraneba/app/controllers/application_controller.rb
> +    redirect_back fallback_location: root_path if session[:user_id].present?
http://localhost:3000/users/

2021-03-22 23:32 UTC, zackey-y commented on yaraneba/app/controllers/application_controller.rb
> +    redirect_back fallback_location: root_path if session[:user_id].present?
`redirect_back` は動線を追いにくくなったり、シークレットモードで意図しない動作になったりしそうなので、素直にタスク一覧あたりに遷移させてしまうのが良いように思いますがどうでしょうか？

例えば↓のリンクを押下したときに「このページ」に戻る・・・気がしたけどリファラが送出されないな・・・
http://localhost:3000/users/

2021-03-22 23:38 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +    params.require(:task).permit(:title, :detail, :status, :end_date, :user_id)
パラメータに `user_id` を入れていますが使っていない気がします

2021-03-22 23:48 UTC, zackey-y commented on yaraneba/app/models/task.rb
> +    Task.where('title LIKE ?', "%#{params[:search_title]}%").where('status LIKE ?', "%#{Task.statuses[params[:search_status]]}%").where(user_id: user_id)
・タイトルを入力していなくても `(title LIKE '%%')` のようなSQLが生成されるのはイケてないと思います
・`status` は integer なので通常はLIKE検索ではないと思います。LIKE検索をしている理由がある場合はお知らせください

2021-03-22 23:56 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +    params.require(:task).permit(:title, :detail, :status, :end_date, :user_id)
いちおう `update` で使われているといえば使われているか
ただ
・ユーザAでログイン、タスクAを作成しタスク編集を開いておく・・・タブ1
・別タブを開いてログアウト→ユーザBでログイン
・タブ1で編集実行
するとタスクがユーザBのものになりますね
タスク削除も他ユーザでできてしまいます

2021-03-23 00:23 UTC, uzushino commented on yaraneba/app/views/users/new.html.erb
> +    <%= form.text_field :password, class: 'form-control' %>
ここもpassword_field で良さそう。（修正はお任せ）

2021-03-23 00:23 UTC, uzushino commented on yaraneba/app/controllers/login_controller.rb
> +    redirect_to tasks_path
destroy はログアウトと思うんですが、ログアウト後に
タスク管理一覧に飛ばしてるのは何故でしょう？

2021-03-23 00:30 UTC, uzushino commented on yaraneba/spec/requests/login_request_spec.rb
> +        expect(response.status).to eq(200)
こういう書き方もあります。
```suggestion
        expect(response).to have_http_status(200)
```

2021-03-23 00:31 UTC, uzushino reviewed
LoginController#destroy の確認をお願いします

2021-03-23 02:45 UTC, zackey-y commented on yaraneba/spec/requests/login_request_spec.rb
> +        expect(response.status).to eq(200)
`expect(response).to have_http_status :ok` のような書き方もできて、4xx系の確認をしたいときなどにステータスコードの内容がわかりやすくて便利です

2021-03-23 05:29 UTC, UYO123 commented
修正後 spec & rubocop
![スクリーンショット 2021-03-23 14 21 25](https://user-images.githubusercontent.com/78333980/112097594-a52da080-8be3-11eb-8678-851c34c72156.png)

修正事項
- [他のユーザが変更できる問題](https://github.com/Fablic/training/pull/933/commits/a8d2f1ec0289ab9688c11d6ac512b60f6b7ce6ba#diff-2ede942527d2fc0b11b96ae028979b9936649c7b2aa034c22164926fe0a4afc6)
- [search変更](https://github.com/Fablic/training/pull/933/commits/a8d2f1ec0289ab9688c11d6ac512b60f6b7ce6ba#diff-4440d9d28df518b3af26b5e53b6e58a8d648d1a4d7f7242c471b669c7f897f80)
  - 不安部分
- redirctのおかしな部分や上記の変更に伴うspec修正

2021-03-23 06:55 UTC, uzushino approved these changes
LGTM です！

2021-03-23 23:34 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +    redirect_to tasks_path if @task.user_id != session[:user_id]
ここも `redirect_if_user_not_allowed` で良さそう

2021-03-23 23:36 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +  def redirect_if_user_not_allowed(task_id)
このメソッドの利用箇所ではどこも `@task.id` を渡していると思いますが、`@task` を渡せば改めて取得する必要がなくなると思います

2021-03-23 23:38 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +    params.require(:task).permit(:title, :detail, :status, :end_date, :user_id)
パラメータに入れた `user_id` は今度こそ使われていないと思うのですが・・・

2021-03-24 00:03 UTC, zackey-y commented on yaraneba/app/models/task.rb
> +    @tasks
こんな形を想定していましたが、これはこれで良さそうｂ
```
@tasks = Task.where(user_id: user_id)
@tasks = @tasks.where('title LIKE ?', "%#{title}%") if title.present?
@tasks = @tasks.where(status: status) if status.present?
```

2021-03-24 00:11 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +    task = Task.find_by(id: @task.id)
↑ここで改めて取得する必要はなくて
↓で `@task.user_id` で良いと思います。また、 `@task` は `find` で検索されているため、nilのままこのメソッドに入ることはないため `&`は不要です

2021-03-24 00:12 UTC, zackey-y commented on yaraneba/app/controllers/tasks_controller.rb
> +    task = Task.find_by(id: @task.id)
あとこれ `before_action` にしたほうが良さそう

2021-03-24 00:45 UTC, zackey-y approved these changes
LGTM！
あと少しですね。頑張ってください！
![ale](https://user-images.githubusercontent.com/38234955/112237220-926ba800-8c85-11eb-8ad1-b311ac03f037.jpg)

2021-03-24 00:46 UTC, merged