Feature/taewon gu step11 13
Fablic/training pull request #938
Opened 2021-04-16 08:08 UTC by TaewonGu

レビュー中のブランチがあるため、feature/taewon_gu_step07から作成しました。
コンパクトバージョンのステップ１１、１３です。
https://github.com/Fablic/training/tree/super-compact-version

実施内容
ステップ11: 複数人で利用できるようにしよう（ユーザの導入）
    [O] ユーザモデルを作成してみましょう
    [O] 最初のユーザをseedで作成してみましょう
    [O] ユーザとタスクが紐づくようにしましょう
    [O] 関連に対してインデックスを貼りましょう
    [O] N+1問題を回避するための仕組みを取り入れましょう
ステップ13: ログイン/ログアウト機能を実装しよう
    [O] 追加のGemを使わず、自分で実装してみましょう
    [O] DeviseなどのGemを使わないことで、HTTPのCookieやRailsにおけるSessionなどの仕組みについて理解を深めることが目的です
    また、一般的な認証についての理解を深めることも目的にしています（パスワードの取り扱いについてなど）
    [O] ログイン画面を実装しましょう
    [O] ログインしていない場合は、タスク管理のページに遷移できないようにしましょう
    [O] 自分が作成したタスクだけを表示するようにしましょう
    [O] ログアウト機能を実装しましょう

2021-04-19 02:52 UTC, uzushino commented on minimini/app/controllers/application_controller.rb
> +      end
一行でできますかね。
```suggestion
      redirect_to login_path unless is_logged_in?
```

2021-04-19 02:54 UTC, uzushino commented on minimini/app/controllers/application_controller.rb
> +      User.find_by(id: session[:current_user_id])
ユーザーの情報が変更された場合は、インスタンス変数の値と違いが出そう

2021-04-19 02:56 UTC, uzushino commented on minimini/app/controllers/sessions_controller.rb
> +    if user && (BCrypt::Password.new(user.password_digest) == params[:password])
`has_secure_password` を使っている場合は、`authenticate` メソッドが使えるので
検討してはどうでしょう？

2021-04-19 02:57 UTC, uzushino commented on minimini/app/controllers/tasks_controller.rb
> +    @tasks = Task.all.preload(:user).where(user_id: session[:current_user_id])
`where` をしているので、`all` はいらないですね。

2021-04-19 02:58 UTC, uzushino commented on minimini/app/controllers/application_controller.rb
> +  include SessionsHelper
`SessionsHelper` は特に何も記載がないようですが、
include をしているのはどうしてでしょうか？

2021-04-19 02:59 UTC, uzushino commented on minimini/app/controllers/tasks_controller.rb
>      @task = Task.new()
引数がない場合は、カッコはいらないですね
```suggestion
    @task = Task.new
```

2021-04-19 02:59 UTC, uzushino commented on minimini/db/migrate/20210414100148_add_index_tasks_user_id.rb
> +  def change
使ってない？

2021-04-19 03:23 UTC, uzushino commented on minimini/spec/models/user_spec.rb
> +    user = FactoryBot.build(:user)
複数の箇所で使われているので、beforeでまとめた方が良さそう

2021-04-19 03:32 UTC, uzushino requested changes
レビュー範囲外ですが、タスクの登録をするときに user_id を直接入力すると
他人のタスクを登録できます。

https://github.com/Fablic/training/pull/938/files#diff-1602fc27780023764e01177deb5cb4415321c4f6ff6491e869dcc87e2484301aL52-L62

2021-04-19 04:43 UTC, TaewonGu commented on minimini/app/controllers/application_controller.rb
> +      end
対応しました。

2021-04-19 04:52 UTC, TaewonGu commented on minimini/app/controllers/sessions_controller.rb
> +    if user && (BCrypt::Password.new(user.password_digest) == params[:password])
コードがすっきりしましたね。対応しました。

2021-04-19 05:00 UTC, TaewonGu commented on minimini/app/controllers/tasks_controller.rb
> +    @tasks = Task.all.preload(:user).where(user_id: session[:current_user_id])
対応しました。

2021-04-19 05:03 UTC, TaewonGu commented on minimini/app/controllers/application_controller.rb
> +  include SessionsHelper
使ってないですね。削除しました。

2021-04-19 05:07 UTC, TaewonGu commented on minimini/app/controllers/tasks_controller.rb
>      @task = Task.new()
()は書く必要ないんですね。対応しました。

2021-04-19 05:16 UTC, TaewonGu commented on minimini/spec/models/user_spec.rb
> +    user = FactoryBot.build(:user)
task_specにも同様のコードがあったのでbeforeにまとめました。

2021-04-19 06:29 UTC, TaewonGu commented on minimini/app/controllers/application_controller.rb
> +      User.find_by(id: session[:current_user_id])
コンパクトバージョンではユーザ情報変更はスコープ外ですがユーザ情報変更時、current_userを削除すれば安全かと思います。

2021-04-20 02:51 UTC, TaewonGu commented on minimini/db/migrate/20210414100148_add_index_tasks_user_id.rb
> +  def change
いいえ、インデックス追加用で修正しました。

2021-04-20 04:14 UTC, uzushino commented on minimini/app/controllers/application_controller.rb
> +      User.find_by(id: session[:current_user_id])
OKです！

2021-04-20 04:15 UTC, uzushino commented on minimini/app/views/tasks/edit.erb
> -    <%= form.hidden_field :user_id, :value => @task.user_id %>
例えば、hidden を追加した場合、まだ他人のタスクが作れます。
![Screen Shot 2021-04-20 at 13 13 27](https://user-images.githubusercontent.com/40757555/115336553-68e96200-a1da-11eb-8c2a-10d64a2ee6fb.png)

2021-04-20 04:37 UTC, TaewonGu commented on minimini/app/views/tasks/edit.erb
> -    <%= form.hidden_field :user_id, :value => @task.user_id %>
user_idをリクエストからツケ取らないで、タスク登録の際セッションからとるように変更しました。

2021-04-20 13:57 UTC, TaewonGu commented on minimini/app/views/tasks/edit.erb
> -    <%= form.hidden_field :user_id, :value => @task.user_id %>
すみません。違うブランチにコミットしてました。修正しましたが他にいい方法ありますか？

2021-04-21 02:15 UTC, uzushino commented on minimini/app/controllers/tasks_controller.rb
>          :id,
id もPOSTで受け取る必要はありますか？

2021-04-21 02:16 UTC, uzushino commented on minimini/app/views/tasks/edit.erb
> -    <%= form.hidden_field :user_id, :value => @task.user_id %>
strong parameter で制限する方法で良いかと思います。

2021-04-21 02:29 UTC, TaewonGu commented on minimini/app/controllers/tasks_controller.rb
>          :id,
パスパラメーターで受け取ってるから不要ですね。削除しました。

2021-04-21 02:32 UTC, uzushino approved these changes
LGTMです

2021-04-21 02:34 UTC, merged