Step-3：railsプロジェクトの作成
Fablic/training pull request #996
Opened 2021-06-17 08:03 UTC by connectShinyaOno-0039

**課題**
https://github.com/Fablic/training#readme
上記の「ステップ3: Railsプロジェクトを作成しよう」

**実装内容**
・rails newコマンドでプロジェクトの作成
・プロジェクト名「tasks」
・「docs」リポジトリを追加し、その中に「README.md」をコピー
・GemfileのRubyのバージョンは「2.5.7」

**共有事項**
・railsのバージョンは「6.1.3.2」
・railsのバージョンが6系のため以下をインストール 
　①Node.js
　②yarn

お手数おかけしますが、よろしくお願いいたします。

2021-06-17 10:19 UTC, R-KazumaInazaki requested changes
Gitアカウントの設定が正しくできていないかもです。CommitのOutherが `connectShinyaOno-0039` ではなく、 `CON-MNA-0039` になってます！

あと、1つだけコメントしたので対応お願いします！

2021-06-17 23:54 UTC, connectShinyaOno-0039 commented on tasks/.gitignore
> +.yarn-integrity
Gitアカウントの設定確認してみます！
/vendor/bundleの追加します！

2021-06-18 00:54 UTC, R-KazumaInazaki commented on tasks/.gitignore
> +.yarn-integrity
追加されているのを確認しました。OKです！

2021-06-18 01:10 UTC, R-KazumaInazaki approved these changes
LGTM!


![LGTM](https://firebasestorage.googleapis.com/v0/b/lgtmgen.appspot.com/o/images%2F5113c17c-e4eb-4ee8-87ec-9fc16237fe9d.jpg?alt=media&token=3759594f-0e36-4c6e-abed-c6506f90958c)

トレーニングの手順には書いてなかったのですが、
`rails new`でプロジェクトを作成した後に、
`bundle exec rails server`でサーバーを立ち上げて、`localhost:3000`にアクセスできるところまで確認できてるといい感じですね！

また余談ですが、
`rails new`で大量のファイルができたと思います。
これらの中にはrailsを動かす最低限のファイルから、拡張機能的なものを含まれており、
`rails new`に何もオプションをつけないと全ての機能が含まれた状態でプロジェクトが作成されます。
今回はこのままで良いと思いますが、
時間がある時にどんな機能があるか見てみるといいかもですね！
（自分も知らないものがちらほらありました…）
https://railsguides.jp/action_cable_overview.html
https://railsguides.jp/webpacker.html
https://railsguides.jp/active_job_basics.html
https://railsguides.jp/action_mailer_basics.html
等々

2021-06-18 01:24 UTC, merged